### ISSUE TITLE
x/vulndb: potential Go vuln in collectd.org: CVE-2010-4336

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#144]
In [CVE-2010-4336](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2010/4xxx/CVE-2010-4336.json), the reference URL [collectd.org](collectd.org) (and possibly others) refers to something in Go.

```
module: collectd.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The cu_rrd_create_file function (src/utils_rrdcreate.c) in collectd 4.x before 4.9.4 and before 4.10.2 allow remote attackers to cause a denial of service (assertion failure) via a packet with a timestamp whose value is 10 or less, as demonstrated by creating RRD files using the (1) RRDtool and (2) RRDCacheD plugins.

cve: CVE-2010-4336
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
