### ISSUE TITLE
x/vulndb: potential Go vuln in debug/gosym: CVE-2012-2666

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#145]
In [CVE-2012-2666](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2012/2xxx/CVE-2012-2666.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  golang/go in 1.0.2 fixes all.bash on shared machines. dotest() in src/pkg/debug/gosym/pclntab_test.go creates a temporary file with predicable name and executes it as shell script.

cve: CVE-2012-2666
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
