### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2013-1909

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#146]
In [CVE-2013-1909](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2013/1xxx/CVE-2013-1909.json), the reference URL [qpid.apache.org](qpid.apache.org) (and possibly others) refers to something in Go.

```
module: qpid.apache.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The Python client in Apache Qpid before 2.2 does not verify that the server hostname matches a domain name in the subject's Common Name (CN) or subjectAltName field of the X.509 certificate, which allows man-in-the-middle attackers to spoof SSL servers via an arbitrary valid certificate.

cve: CVE-2013-1909
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
