### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2013-4450

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#147]
In [CVE-2013-4450](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2013/4xxx/CVE-2013-4450.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The HTTP server in Node.js 0.10.x before 0.10.21 and 0.8.x before 0.8.26 allows remote attackers to cause a denial of service (memory and CPU consumption) by sending a large number of pipelined requests without reading the response.

cve: CVE-2013-4450
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
