### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2013-4546

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#148]
In [CVE-2013-4546](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2013/4xxx/CVE-2013-4546.json), the reference URL [gitlab.com/gitlab-org/gitlab-shell](gitlab.com/gitlab-org/gitlab-shell) (and possibly others) refers to something in Go.

```
module: gitlab.com/gitlab-org/gitlab-shell
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The repository import feature in gitlab-shell before 1.7.4, as used in GitLab, allows remote authenticated users to execute arbitrary commands via the import URL.

cve: CVE-2013-4546
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
