### ISSUE TITLE
x/vulndb: potential Go vuln in net: CVE-2013-7423

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#149]
In [CVE-2013-7423](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2013/7xxx/CVE-2013-7423.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The send_dg function in resolv/res_send.c in GNU C Library (aka glibc or libc6) before 2.20 does not properly reuse file descriptors, which allows remote attackers to send DNS queries to unintended locations via a large number of requests that trigger a call to the getaddrinfo function.

cve: CVE-2013-7423
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
