### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2014-4877

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#150]
In [CVE-2014-4877](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2014/4xxx/CVE-2014-4877.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Absolute path traversal vulnerability in GNU Wget before 1.16, when recursion is enabled, allows remote FTP servers to write to arbitrary files, and consequently execute arbitrary code, via a LIST response that references the same filename within two entries, one of which indicates that the filename is for a symlink.

cve: CVE-2014-4877
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
