### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2014-5445

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#151]
In [CVE-2014-5445](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2014/5xxx/CVE-2014-5445.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Multiple absolute path traversal vulnerabilities in ZOHO ManageEngine Netflow Analyzer 8.6 through 10.2 and IT360 10.3 allow remote attackers or remote authenticated users to read arbitrary files via a full pathname in the schFilePath parameter to the (1) CSVServlet or (2) CReportPDFServlet servlet.

cve: CVE-2014-5445
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
