### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2014-6037

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#152]
In [CVE-2014-6037](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2014/6xxx/CVE-2014-6037.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Directory traversal vulnerability in the agentUpload servlet in ZOHO ManageEngine EventLog Analyzer 9.0 build 9002 and 8.2 build 8020 allows remote attackers to execute arbitrary code by uploading a ZIP file which contains an executable file with .. (dot dot) sequences in its name, then accessing the executable via a direct request to the file under the web root. Fixed in Build 11072.

cve: CVE-2014-6037
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
