### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2014-6287

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#153]
In [CVE-2014-6287](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2014/6xxx/CVE-2014-6287.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The findMacroMarker function in parserLib.pas in Rejetto HTTP File Server (aks HFS or HttpFileServer) 2.3x before 2.3c allows remote attackers to execute arbitrary programs via a %00 sequence in a search action.

cve: CVE-2014-6287
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
