### ISSUE TITLE
x/vulndb: potential Go vuln in crpyto/tls: CVE-2014-7189

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#154]
In [CVE-2014-7189](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2014/7xxx/CVE-2014-7189.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  crpyto/tls in Go 1.1 before 1.3.2, when SessionTicketsDisabled is enabled, allows man-in-the-middle attackers to spoof clients via unspecified vectors.

cve: CVE-2014-7189
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
