### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2015-0779

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#156]
In [CVE-2015-0779](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2015/0xxx/CVE-2015-0779.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  Directory traversal vulnerability in UploadServlet in Novell ZENworks Configuration Management (ZCM) 10 and 11 before 11.3.2 allows remote attackers to execute arbitrary code via a crafted directory name in the uid parameter, in conjunction with a WAR filename in the filename parameter and WAR content in the POST data, a different vulnerability than CVE-2010-5323 and CVE-2010-5324.

cve: CVE-2015-0779
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
