### ISSUE TITLE
x/vulndb: potential Go vuln in net/http: CVE-2015-5739

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#157]
In [CVE-2015-5739](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2015/5xxx/CVE-2015-5739.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The net/http library in net/textproto/reader.go in Go before 1.4.3 does not properly parse HTTP header keys, which allows remote attackers to conduct HTTP request smuggling attacks via a space instead of a hyphen, as demonstrated by "Content Length" instead of "Content-Length."

cve: CVE-2015-5739
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
