### ISSUE TITLE
x/vulndb: potential Go vuln in math/big: CVE-2015-8618

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#160]
In [CVE-2015-8618](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2015/8xxx/CVE-2015-8618.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: Go Standard Library (package not identified)
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The Int.Exp Montgomery code in the math/big library in Go 1.5.x before 1.5.3 mishandles carry propagation and produces incorrect output, which makes it easier for attackers to obtain private RSA keys via unspecified vectors.

cve: CVE-2015-8618
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
