### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-2166

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#161]
In [CVE-2016-2166](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/2xxx/CVE-2016-2166.json), the reference URL [qpid.apache.org](qpid.apache.org) (and possibly others) refers to something in Go.

```
module: qpid.apache.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  The (1) proton.reactor.Connector, (2) proton.reactor.Container, and (3) proton.utils.BlockingConnection classes in Apache Qpid Proton before 0.12.1 improperly use an unencrypted connection for an amqps URI scheme when SSL support is unavailable, which might allow man-in-the-middle attackers to obtain sensitive information or modify data via unspecified vectors.

cve: CVE-2016-2166
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
