### ISSUE TITLE
x/vulndb: potential Go vulnerability found from CVE List: CVE-2016-3094

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#162]
In [CVE-2016-3094](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/3xxx/CVE-2016-3094.json), the reference URL [qpid.apache.org](qpid.apache.org) (and possibly others) refers to something in Go.

```
module: qpid.apache.org
package:
stdlib:
versions:
  - introduced:
  - fixed:
description: |
  PlainSaslServer.java in Apache Qpid Java before 6.0.3, when the broker is configured to allow plaintext passwords, allows remote attackers to cause a denial of service (broker termination) via a crafted authentication attempt, which triggers an uncaught exception.

cve: CVE-2016-3094
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
