### ISSUE TITLE
x/vulndb: potential Go vuln in syscall: CVE-2016-3958

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#163]
In [CVE-2016-3958](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/3xxx/CVE-2016-3958.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
package: syscall
stdlib: true
versions:
  - fixed:
    - go1.6.1
    - go1.5.4
description: |
  Untrusted search path vulnerability in Go before 1.5.4 and 1.6.x before 1.6.1 on Windows allows local users to gain privileges via a Trojan horse DLL in the current working directory, related to use of the LoadLibrary function.

cve: CVE-2016-3958
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
