### ISSUE TITLE
x/vulndb: potential Go vuln in crypto/dsa: CVE-2016-3959

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#166]
In [CVE-2016-3959](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/3xxx/CVE-2016-3959.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: std
package: Go Standard Library (package not identified)
description: |
  The Verify function in crypto/dsa/dsa.go in Go before 1.5.4 and 1.6.x before 1.6.1 does not properly check parameters passed to the big integer library, which might allow remote attackers to cause a denial of service (infinite loop) via a crafted public key to a program that uses HTTPS client certificates or SSH server libraries.
cves:
- CVE-2016-3959
links:
  pr: https://go-review.googlesource.com/#/c/21533/
  context:
  - http://lists.fedoraproject.org/pipermail/package-announce/2016-April/182526.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2016-April/183106.html
  - http://lists.fedoraproject.org/pipermail/package-announce/2016-April/183137.html
  - http://lists.opensuse.org/opensuse-updates/2016-05/msg00077.html
  - http://rhn.redhat.com/errata/RHSA-2016-1538.html
  - http://www.openwall.com/lists/oss-security/2016/04/05/1
  - http://www.openwall.com/lists/oss-security/2016/04/05/2
  - https://groups.google.com/g/golang-announce/c/9eqIHqaWvck

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
