### ISSUE TITLE
x/vulndb: potential Go vuln in collectd.org: CVE-2016-6254

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#168]
In [CVE-2016-6254](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/6xxx/CVE-2016-6254.json), the reference URL [collectd.org](collectd.org) (and possibly others) refers to something in Go.

```
module: collectd.org
package: n/a
description: |
  Heap-based buffer overflow in the parse_packet function in network.c in collectd before 5.4.3 and 5.x before 5.5.2 allows remote attackers to cause a denial of service (daemon crash) or possibly execute arbitrary code via a crafted network packet.
cves:
- CVE-2016-6254
links:
  commit: https://github.com/collectd/collectd/commit/b589096f907052b3a4da2b9ccc9b0e2e888dfc18
  context:
  - http://collectd.org/news.shtml
  - http://www.debian.org/security/2016/dsa-3636
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CM4W5SJ4OTBGINGIN4NJLXCUZAZANO6J/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UIZ5UXDOB7BA5NGE2F2I2BL4K6763DHW/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
