### ISSUE TITLE
x/vulndb: potential Go vuln in "github.com/rapid7/metasploit-framework": CVE-2016-7547

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#169]
In [CVE-2016-7547](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2016/7xxx/CVE-2016-7547.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package: n/a
description: |
  A command execution flaw on the Trend Micro Threat Discovery Appliance 2.6.1062r1 exists with the timezone parameter in the admin_sys_time.cgi interface.
cves:
- CVE-2016-7547
links:
  commit: https://github.com/rapid7/metasploit-framework/pull/8216/commits/0f07875a2ddb0bfbb4e985ab074e9fc56da1dcf6
  context:
  - http://www.securityfocus.com/bid/97610

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
