### ISSUE TITLE
x/vulndb: potential Go vuln in "github.com/rapid7/metasploit-framework": CVE-2017-13872

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#173]
In [CVE-2017-13872](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/13xxx/CVE-2017-13872.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package: macOS High Sierra
description: |
  An issue was discovered in certain Apple products. macOS High Sierra before Security Update 2017-001 is affected. The issue involves the "Directory Utility" component. It allows attackers to obtain administrator access without a password via certain interactions involving entry of the root user name.
cves:
- CVE-2017-13872
links:
  pr: https://github.com/rapid7/metasploit-framework/pull/9302
  context:
  - http://www.securityfocus.com/bid/101981
  - http://www.securitytracker.com/id/1039875
  - https://arstechnica.com/information-technology/2017/11/macos-bug-lets-you-log-in-as-admin-with-no-password-required/
  - https://objective-see.com/blog/blog_0x24.html
  - https://support.apple.com/HT208315
  - https://support.apple.com/HT208331
  - https://www.exploit-db.com/exploits/43201/
  - https://www.exploit-db.com/exploits/43248/
  - https://www.wired.com/story/macos-update-undoes-apple-root-bug-patch/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
