### ISSUE TITLE
x/vulndb: potential Go vuln in "github.com/rapid7/metasploit-framework": CVE-2017-14705

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#174]
In [CVE-2017-14705](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/14xxx/CVE-2017-14705.json), the reference URL [github.com/rapid7/metasploit-framework](github.com/rapid7/metasploit-framework) (and possibly others) refers to something in Go.

```
module: github.com/rapid7/metasploit-framework
package: n/a
description: |
  DenyAll WAF before 6.4.1 allows unauthenticated remote command execution via TCP port 3001 because shell metacharacters can be inserted into the type parameter to the tailDateFile function in /webservices/stream/tail.php. An iToken authentication parameter is required but can be obtained by exploiting CVE-2017-14706. This affects DenyAll i-Suite LTS 5.5.0 through 5.5.12, i-Suite 5.6, Web Application Firewall 5.7, and Web Application Firewall 6.x before 6.4.1, with On Premises or AWS/Azure cloud deployments.
cves:
- CVE-2017-14705
links:
  pr: https://github.com/rapid7/metasploit-framework/pull/8980
  context:
  - https://pentest.blog/advisory-denyall-web-application-firewall-unauthenticated-remote-code-execution/
  - https://www.denyall.com/blog/advisories/advisory-unauthenticated-remote-code-execution-denyall-web-application-firewall/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
