### ISSUE TITLE
x/vulndb: potential Go vuln in "gitweb.gentoo.org/repo/gentoo.git": CVE-2017-14730

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#176]
In [CVE-2017-14730](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/14xxx/CVE-2017-14730.json), the reference URL [gitweb.gentoo.org/repo/gentoo.git](gitweb.gentoo.org/repo/gentoo.git) (and possibly others) refers to something in Go.

```
module: gitweb.gentoo.org/repo/gentoo.git
package: n/a
description: |
  The init script in the Gentoo app-admin/logstash-bin package before 5.5.3 and 5.6.x before 5.6.1 has "chown -R" calls for user-writable directory trees, which allows local users to gain privileges by leveraging access to a $LS_USER account for creation of a hard link.
cves:
- CVE-2017-14730
links:
  pr: https://github.com/gentoo/gentoo/pull/5665
  commit: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=18f97c851c209f291b31ae7a902719f1c17c79fa
  context:
  - https://bugs.gentoo.org/628558

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
