### ISSUE TITLE
x/vulndb: potential Go vuln in "gitweb.gentoo.org/repo/gentoo.git": CVE-2017-5677

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#185]
In [CVE-2017-5677](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/5xxx/CVE-2017-5677.json), the reference URL [gitweb.gentoo.org/repo/gentoo.git](gitweb.gentoo.org/repo/gentoo.git) (and possibly others) refers to something in Go.

```
module: gitweb.gentoo.org/repo/gentoo.git
package: n/a
description: |
  PEAR HTML_AJAX 0.3.0 through 0.5.7 has a PHP Object Injection Vulnerability in the PHP Serializer. It allows remote code execution. In one viewpoint, the root cause is an incorrect regular expression.
cves:
- CVE-2017-5677
links:
  commit: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=f5acb5adcd195f9a06b732794cb0de7620def646
  context:
  - http://blog.pear.php.net/2017/02/02/security-html_ajax-058/
  - http://karmainsecurity.com/KIS-2017-01
  - http://seclists.org/fulldisclosure/2017/Feb/12
  - http://www.securityfocus.com/bid/96044
  - https://pear.php.net/bugs/bug.php?id=21165

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
