### ISSUE TITLE
x/vulndb: potential Go vuln in crypto/elliptic: CVE-2017-8932

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#187]
In [CVE-2017-8932](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2017/8xxx/CVE-2017-8932.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: std
package: Go Standard Library (package not identified)
description: |
  A bug in the standard library ScalarMult implementation of curve P-256 for amd64 architectures in Go before 1.7.6 and 1.8.x before 1.8.2 causes incorrect results to be generated for specific input points. An adaptive attack can be mounted to progressively extract the scalar input to ScalarMult by submitting crafted points and observing failures to the derive correct output. This leads to a full key recovery attack against static ECDH, as used in popular JWT libraries.
cves:
- CVE-2017-8932
links:
  pr: https://go-review.googlesource.com/c/41070/
  commit: https://go.googlesource.com/go/+/9294fa2749ffee7edbbb817a0ef9fe633136fa9c
  context:
  - http://lists.opensuse.org/opensuse-updates/2017-06/msg00079.html
  - http://lists.opensuse.org/opensuse-updates/2017-06/msg00080.html
  - https://access.redhat.com/errata/RHSA-2017:1859
  - https://bugzilla.redhat.com/show_bug.cgi?id=1455191
  - https://go.dev/issue/20040
  - https://groups.google.com/d/msg/golang-announce/B5ww0iFt1_Q/TgUFJV14BgAJ
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/LZH4T47ROLZ6YEZBDVXVS2KISTDMXAPS/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
