### ISSUE TITLE
x/vulndb: potential Go vuln in "Go Standard Library (package not identified)": CVE-2019-19602

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#214]
In [CVE-2019-19602](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/19xxx/CVE-2019-19602.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: std
package: Go Standard Library (package not identified)
description: |
  fpregs_state_valid in arch/x86/include/asm/fpu/internal.h in the Linux kernel before 5.4.2, when GCC 9 is used, allows context-dependent attackers to cause a denial of service (memory corruption) or possibly have unspecified other impact because of incorrect fpu_fpregs_owner_ctx caching, as demonstrated by mishandling of signal-based non-cooperative preemption in Go 1.14 prereleases on amd64, aka CID-59c4bd853abc.
cves:
- CVE-2019-19602
links:
  commit: https://github.com/torvalds/linux/commit/59c4bd853abcea95eccc167a7d7fd5f1a5f47b98
  context:
  - https://bugzilla.kernel.org/show_bug.cgi?id=205663
  - https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.4.2
  - https://go.dev/issue/35777#issuecomment-561935388
  - https://security.netapp.com/advisory/ntap-20200103-0001/
  - https://usn.ubuntu.com/4284-1/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
