### ISSUE TITLE
x/vulndb: potential Go vuln in "Go Standard Library (package not identified)": CVE-2019-6486

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#217]
In [CVE-2019-6486](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2019/6xxx/CVE-2019-6486.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.

```
module: std
package: Go Standard Library (package not identified)
description: |
  Go before 1.10.8 and 1.11.x before 1.11.5 mishandles P-521 and P-384 elliptic curves, which allows attackers to cause a denial of service (CPU consumption) or possibly conduct ECDH private key recovery attacks.
cves:
- CVE-2019-6486
links:
  commit: https://go.googlesource.com/go/+/42b42f71cf8f5956c09e66230293dfb5db652360
  context:
  - http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00042.html
  - http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00060.html
  - http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00011.html
  - http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00015.html
  - http://www.securityfocus.com/bid/106740
  - https://go.dev/issue/29903
  - https://github.com/google/wycheproof
  - https://groups.google.com/g/golang-announce/c/mVeX35iXuSw
  - https://lists.debian.org/debian-lts-announce/2019/02/msg00009.html
  - https://www.debian.org/security/2019/dsa-4379
  - https://www.debian.org/security/2019/dsa-4380

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md)
for instructions on how to triage this report.
