### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pires/go-proxyproto: CVE-2021-23409

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#233]
In [CVE-2021-23409](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/23xxx/CVE-2021-23409.json), the reference URL [github.com/pires/go-proxyproto](github.com/pires/go-proxyproto) (and possibly others) refers to something in Go.
- Commit: https://github.com/pires/go-proxyproto/pull/74/commits/cdc63867da24fc609b727231f682670d0d1cd346
- PR: https://github.com/pires/go-proxyproto/pull/74

```
module: github.com/pires/go-proxyproto
package: github.com/pires/go-proxyproto
description: |
  The package github.com/pires/go-proxyproto before 0.6.0 are vulnerable to Denial of Service (DoS) via creating connections without the proxy protocol header.
cves:
- CVE-2021-23409
links:
  pr: https://github.com/pires/go-proxyproto/pull/74
  commit: https://github.com/pires/go-proxyproto/pull/74/commits/cdc63867da24fc609b727231f682670d0d1cd346
  context:
  - https://github.com/pires/go-proxyproto/issues/65
  - https://github.com/pires/go-proxyproto/releases/tag/v0.6.0
  - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMPIRESGOPROXYPROTO-1316439

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
