### ISSUE TITLE
x/vulndb: potential Go vuln in Go Standard Library (package not identified): CVE-2021-3114

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#235]
In [CVE-2021-3114](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/3xxx/CVE-2021-3114.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.
- Commit: https://go.googlesource.com/go/+/d95ca9138026cbe40e0857d76a81a16d03230871

```
module: std
package: Go Standard Library (package not identified)
description: |
  In Go before 1.14.14 and 1.15.x before 1.15.7, crypto/elliptic/p224.go can generate incorrect outputs, related to an underflow of the lowest limb during the final complete reduction in the P-224 field.
cves:
- CVE-2021-3114
links:
  commit: https://go.googlesource.com/go/+/d95ca9138026cbe40e0857d76a81a16d03230871
  context:
  - https://groups.google.com/g/golang-announce/c/mperVMGa98w
  - https://lists.debian.org/debian-lts-announce/2021/03/msg00014.html
  - https://lists.debian.org/debian-lts-announce/2021/03/msg00015.html
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YWAYJGXWC232SG3UR3TR574E6BP3OSQQ/
  - https://security.netapp.com/advisory/ntap-20210219-0001/
  - https://www.debian.org/security/2021/dsa-4848

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
