### ISSUE TITLE
x/vulndb: potential Go vuln in Go Standard Library (package not identified): CVE-2021-33194

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#238]
In [CVE-2021-33194](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/33xxx/CVE-2021-33194.json), the reference URL [Go Standard Library (package not identified)](Go Standard Library (package not identified)) (and possibly others) refers to something in Go.
- Commit: https://go.googlesource.com/net/+/37e1c6afe02340126705deced573a85ab75209d7

```
module: std
package: Go Standard Library (package not identified)
description: |
  golang.org/x/net before v0.0.0-20210520170846-37e1c6afe023 allows attackers to cause a denial of service (infinite loop) via crafted ParseFragment input.
cves:
- CVE-2021-33194
links:
  commit: https://go.googlesource.com/net/+/37e1c6afe02340126705deced573a85ab75209d7
  context:
  - https://groups.google.com/g/golang-announce/c/wPunbCPkWUg

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
