### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/cosmos/cosmos-sdk: CVE-2021-41135

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#255]
In [CVE-2021-41135](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41135.json), the reference URL [github.com/cosmos/cosmos-sdk](github.com/cosmos/cosmos-sdk) (and possibly others) refers to something in Go.
- Commit: https://github.com/cosmos/cosmos-sdk/commit/68ab790a761e80d3674f821794cf18ccbfed45ee

```
module: github.com/cosmos/cosmos-sdk
package: cosmos-sdk
description: |
  The Cosmos-SDK is a framework for building blockchain applications in Golang. Affected versions of the SDK were vulnerable to a consensus halt due to non-deterministic behaviour in a ValidateBasic method in the x/authz module. The MsgGrant of the x/authz module contains a Grant field which includes a user-defined expiration time for when the authorization grant expires. In Grant.ValidateBasic(), that time is compared to the node’s local clock time. Any chain running an affected version of the SDK with the authz module enabled could be halted by anyone with the ability to send transactions on that chain. Recovery would require applying the patch and rolling back the latest block. Users are advised to update to version 0.44.2.
cves:
- CVE-2021-41135
links:
  commit: https://github.com/cosmos/cosmos-sdk/commit/68ab790a761e80d3674f821794cf18ccbfed45ee
  context:
  - https://forum.cosmos.network/t/cosmos-sdk-vulnerability-retrospective-security-advisory-jackfruit-october-12-2021/5349
  - https://github.com/cosmos/cosmos-sdk/security/advisories/GHSA-2p6r-37p9-89p2

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
