### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ethereum/go-ethereum: CVE-2021-41173

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#256]
In [CVE-2021-41173](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41173.json), the reference URL [github.com/ethereum/go-ethereum](github.com/ethereum/go-ethereum) (and possibly others) refers to something in Go.
- Commit: https://github.com/ethereum/go-ethereum/commit/e40b37718326b8b4873b3b00a0db2e6c6d9ea738
- PR: https://github.com/ethereum/go-ethereum/pull/23801

```
module: github.com/ethereum/go-ethereum
package: go-ethereum
description: |
  Go Ethereum is the official Golang implementation of the Ethereum protocol. Prior to version 1.10.9, a vulnerable node is susceptible to crash when processing a maliciously crafted message from a peer. Version v1.10.9 contains patches to the vulnerability. There are no known workarounds aside from upgrading.
cves:
- CVE-2021-41173
links:
  pr: https://github.com/ethereum/go-ethereum/pull/23801
  commit: https://github.com/ethereum/go-ethereum/commit/e40b37718326b8b4873b3b00a0db2e6c6d9ea738
  context:
  - https://github.com/ethereum/go-ethereum/releases/tag/v1.10.9
  - https://github.com/ethereum/go-ethereum/security/advisories/GHSA-59hh-656j-3p7v

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
