### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/opencontainers/distribution-spec: CVE-2021-41190

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#257]
In [CVE-2021-41190](https://github.com/CVEProject/cvelist/tree/4a19c9874a0af312665d79112de85dd296d6e510/2021/41xxx/CVE-2021-41190.json), the reference URL [github.com/opencontainers/distribution-spec](github.com/opencontainers/distribution-spec) (and possibly others) refers to something in Go.
- Commit: https://github.com/opencontainers/distribution-spec/commit/ac28cac0557bcd3084714ab09f9f2356fe504923

```
module: github.com/opencontainers/distribution-spec
package: distribution-spec
description: |
  The OCI Distribution Spec project defines an API protocol to facilitate and standardize the distribution of content. In the OCI Distribution Specification version 1.0.0 and prior, the Content-Type header alone was used to determine the type of document during push and pull operations. Documents that contain both “manifests” and “layers” fields could be interpreted as either a manifest or an index in the absence of an accompanying Content-Type header. If a Content-Type header changed between two pulls of the same digest, a client may interpret the resulting content differently. The OCI Distribution Specification has been updated to require that a mediaType value present in a manifest or index match the Content-Type header used during the push and pull operations. Clients pulling from a registry may distrust the Content-Type header and reject an ambiguous document that contains both “manifests” and “layers” fields or “manifests” and “config” fields if they are unable to update to version 1.0.1 of the spec.
cves:
- CVE-2021-41190
links:
  commit: https://github.com/opencontainers/distribution-spec/commit/ac28cac0557bcd3084714ab09f9f2356fe504923
  context:
  - http://www.openwall.com/lists/oss-security/2021/11/19/10
  - https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/A2RRFNTMFYKOTRKD37F5ANMCIO3GGJML/
  - https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DX63GRWFEI5RVMYV6XLMCG4OHPWZML27/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
