### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/minio/console: CVE-2021-41266

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#261]
In [CVE-2021-41266](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/41xxx/CVE-2021-41266.json), the reference URL [github.com/minio/console](github.com/minio/console) (and possibly others) refers to something in Go.
- PR: https://github.com/minio/console/pull/1217

```
module: github.com/minio/console
package: console
description: |
  Minio console is a graphical user interface for the for MinIO operator. Minio itself is a multi-cloud object storage project. Affected versions are subject to an authentication bypass issue in the Operator Console when an external IDP is enabled. All users on release v0.12.2 and before are affected and are advised to update to 0.12.3 or newer. Users unable to upgrade should add automountServiceAccountToken: false to the operator-console deployment in Kubernetes so no service account token will get mounted inside the pod, then disable the external identity provider authentication by unset the CONSOLE_IDP_URL, CONSOLE_IDP_CLIENT_ID, CONSOLE_IDP_SECRET and CONSOLE_IDP_CALLBACK environment variable and instead use the Kubernetes service account token.
cves:
- CVE-2021-41266
links:
  pr: https://github.com/minio/console/pull/1217
  context:
  - https://github.com/minio/console/security/advisories/GHSA-4999-659w-mq36

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
