### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/tidwall/gjson: CVE-2021-42836

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#265]
In [CVE-2021-42836](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/42xxx/CVE-2021-42836.json), the reference URL [github.com/tidwall/gjson](github.com/tidwall/gjson) (and possibly others) refers to something in Go.
- Commit: https://github.com/tidwall/gjson/commit/590010fdac311cc8990ef5c97448d4fec8f29944

```
module: github.com/tidwall/gjson
package: n/a
description: |
  GJSON before 1.9.3 allows a ReDoS (regular expression denial of service) attack.
cves:
- CVE-2021-42836
links:
  commit: https://github.com/tidwall/gjson/commit/590010fdac311cc8990ef5c97448d4fec8f29944
  context:
  - https://github.com/tidwall/gjson/compare/v1.9.2...v1.9.3
  - https://github.com/tidwall/gjson/issues/236
  - https://github.com/tidwall/gjson/issues/237

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
