### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hyperledger/fabric: CVE-2021-43667

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#266]
In [CVE-2021-43667](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/43xxx/CVE-2021-43667.json), the reference URL [github.com/hyperledger/fabric](github.com/hyperledger/fabric) (and possibly others) refers to something in Go.
- PR: https://github.com/hyperledger/fabric/pull/2844

```
module: github.com/hyperledger/fabric
package: n/a
description: |
  A vulnerability has been detected in HyperLedger Fabric v1.4.0, v2.0.0, v2.1.0. This bug can be leveraged by constructing a message whose payload is nil and sending this message with the method 'forwardToLeader'. This bug has been admitted and fixed by the developers of Fabric. If leveraged, any leader node will crash.
cves:
- CVE-2021-43667
links:
  pr: https://github.com/hyperledger/fabric/pull/2844
  context:
  - https://jira.hyperledger.org/browse/FAB-18529

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
