### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hyperledger/fabric: CVE-2021-43669

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#267]
In [CVE-2021-43669](https://github.com/CVEProject/cvelist/tree/cb2d8ae8ac0afed043d0fd99669e1aaac42e8b69/2021/43xxx/CVE-2021-43669.json), the reference URL [github.com/hyperledger/fabric](github.com/hyperledger/fabric) (and possibly others) refers to something in Go.
- PR: https://github.com/hyperledger/fabric/pull/2828

```
module: github.com/hyperledger/fabric
package: n/a
description: |
  A vulnerability has been detected in HyperLedger Fabric v1.4.0, v2.0.0, v2.0.1, v2.3.0. It can easily break down as many orderers as the attacker wants. This bug can be leveraged by constructing a message whose header is invalid to the interface Order. This bug has been admitted and fixed by the developers of Fabric.
cves:
- CVE-2021-43669
links:
  pr: https://github.com/hyperledger/fabric/pull/2828
  context:
  - https://jira.hyperledger.org/browse/FAB-18528

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
