### ISSUE TITLE
x/vulndb: potential Go vuln in Path is unknown: CVE-2021-23772

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#272]
In [CVE-2021-23772](https://github.com/CVEProject/cvelist/tree/157720d8e88af5af5b32c66aab38d0248ca036c5/2021/23xxx/CVE-2021-23772.json), the reference URL [Path is unknown](Path is unknown) (and possibly others) refers to something in Go.
- Commit: https://github.com/kataras/iris/commit/e213dba0d32ff66653e0ef124bc5088817264b08

```
module: std
package: Path is unknown
description: |
    This affects all versions of package github.com/kataras/iris; all versions of package github.com/kataras/iris/v12. The unsafe handling of file names during upload using UploadFormFiles method may enable attackers to write to arbitrary locations outside the designated target folder.
cves:
  - CVE-2021-23772
credit: Snyk Security Team
links:
    commit: https://github.com/kataras/iris/commit/e213dba0d32ff66653e0ef124bc5088817264b08
    context:
      - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMKATARASIRIS-2325169
      - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMKATARASIRISV12-2325170

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
