### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/opencontainers/runc: CVE-2021-43784

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#274]
In [CVE-2021-43784](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43784.json), the reference URL [github.com/opencontainers/runc](github.com/opencontainers/runc) (and possibly others) refers to something in Go.
- Commit: https://github.com/opencontainers/runc/commit/f50369af4b571e358f20b139eea52d612eb55eed

```
module: github.com/opencontainers/runc
package: runc
description: |
    runc is a CLI tool for spawning and running containers on Linux according to the OCI specification. In runc, netlink is used internally as a serialization system for specifying the relevant container configuration to the `C` portion of the code (responsible for the based namespace setup of containers). In all versions of runc prior to 1.0.3, the encoder did not handle the possibility of an integer overflow in the 16-bit length field for the byte array attribute type, meaning that a large enough malicious byte array attribute could result in the length overflowing and the attribute contents being parsed as netlink messages for container configuration. This vulnerability requires the attacker to have some control over the configuration of the container and would allow the attacker to bypass the namespace restrictions of the container by simply adding their own netlink payload which disables all namespaces. The main users impacted are those who allow untrusted images with untrusted configurations to run on their machines (such as with shared cloud infrastructure). runc version 1.0.3 contains a fix for this bug. As a workaround, one may try disallowing untrusted namespace paths from your container. It should be noted that untrusted namespace paths would allow the attacker to disable namespace protections entirely even in the absence of this bug.
cves:
  - CVE-2021-43784
links:
    commit: https://github.com/opencontainers/runc/commit/f50369af4b571e358f20b139eea52d612eb55eed
    context:
      - https://bugs.chromium.org/p/project-zero/issues/detail?id=2241
      - https://github.com/opencontainers/runc/security/advisories/GHSA-v95c-p5hm-xq8f
      - https://lists.debian.org/debian-lts-announce/2021/12/msg00005.html

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
