### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2021-43798

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#275]
In [CVE-2021-43798](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43798.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- Commit: https://github.com/grafana/grafana/commit/c798c0e958d15d9cc7f27c72113d572fa58545ce

```
module: github.com/grafana/grafana
package: grafana
description: |
    Grafana is an open-source platform for monitoring and observability. Grafana versions 8.0.0-beta1 through 8.3.0 (except for patched versions) iss vulnerable to directory traversal, allowing access to local files. The vulnerable URL path is: `<grafana_host_url>/public/plugins//`, where is the plugin ID for any installed plugin. At no time has Grafana Cloud been vulnerable. Users are advised to upgrade to patched versions 8.0.7, 8.1.8, 8.2.7, or 8.3.1. The GitHub Security Advisory contains more information about vulnerable URL paths, mitigation, and the disclosure timeline.
cves:
  - CVE-2021-43798
links:
    commit: https://github.com/grafana/grafana/commit/c798c0e958d15d9cc7f27c72113d572fa58545ce
    context:
      - http://packetstormsecurity.com/files/165198/Grafana-Arbitrary-File-Reading.html
      - http://packetstormsecurity.com/files/165221/Grafana-8.3.0-Directory-Traversal-Arbitrary-File-Read.html
      - http://www.openwall.com/lists/oss-security/2021/12/09/2
      - http://www.openwall.com/lists/oss-security/2021/12/10/4
      - https://github.com/grafana/grafana/security/advisories/GHSA-8pjx-jj86-j47p
      - https://grafana.com/blog/2021/12/08/an-update-on-0day-cve-2021-43798-grafana-directory-traversal/
      - https://security.netapp.com/advisory/ntap-20211229-0004/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
