### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2021-43813

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#276]
In [CVE-2021-43813](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43813.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- Commit: https://github.com/grafana/grafana/commit/fd48aee61e4328aae8d5303a9efd045fa0ca308d

```
module: github.com/grafana/grafana
package: grafana
description: |
    Grafana is an open-source platform for monitoring and observability. Grafana prior to versions 8.3.2 and 7.5.12 contains a directory traversal vulnerability for fully lowercase or fully uppercase .md files. The vulnerability is limited in scope, and only allows access to files with the extension .md to authenticated users only. Grafana Cloud instances have not been affected by the vulnerability. Users should upgrade to patched versions 8.3.2 or 7.5.12. For users who cannot upgrade, running a reverse proxy in front of Grafana that normalizes the PATH of the request will mitigate the vulnerability. The proxy will have to also be able to handle url encoded paths. Alternatively, for fully lowercase or fully uppercase .md files, users can block /api/plugins/.*/markdown/.* without losing any functionality beyond inlined plugin help text.
cves:
  - CVE-2021-43813
links:
    commit: https://github.com/grafana/grafana/commit/fd48aee61e4328aae8d5303a9efd045fa0ca308d
    context:
      - http://www.openwall.com/lists/oss-security/2021/12/10/4
      - https://github.com/grafana/grafana/security/advisories/GHSA-c3q8-26ph-9g2q
      - https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/
      - https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-5-12/
      - https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-3-2/
      - https://security.netapp.com/advisory/ntap-20220107-0006/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
