### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2021-43815

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#277]
In [CVE-2021-43815](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43815.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- Commit: https://github.com/grafana/grafana/commit/d6ec6f8ad28f0212e584406730f939105ff6c6d3

```
module: github.com/grafana/grafana
package: grafana
description: |
    Grafana is an open-source platform for monitoring and observability. Grafana prior to versions 8.3.2 and 7.5.12 has a directory traversal for arbitrary .csv files. It only affects instances that have the developer testing tool called TestData DB data source enabled and configured. The vulnerability is limited in scope, and only allows access to files with the extension .csv to authenticated users only. Grafana Cloud instances have not been affected by the vulnerability. Versions 8.3.2 and 7.5.12 contain a patch for this issue. There is a workaround available for users who cannot upgrade. Running a reverse proxy in front of Grafana that normalizes the PATH of the request will mitigate the vulnerability. The proxy will have to also be able to handle url encoded paths.
cves:
  - CVE-2021-43815
links:
    commit: https://github.com/grafana/grafana/commit/d6ec6f8ad28f0212e584406730f939105ff6c6d3
    context:
      - http://www.openwall.com/lists/oss-security/2021/12/10/4
      - https://github.com/grafana/grafana/releases/tag/v8.3.2
      - https://github.com/grafana/grafana/security/advisories/GHSA-7533-c8qv-jm9m
      - https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/
      - https://security.netapp.com/advisory/ntap-20220107-0006/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
