### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sourcegraph/sourcegraph: CVE-2021-43823

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#279]
In [CVE-2021-43823](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43823.json), the reference URL [github.com/sourcegraph/sourcegraph](github.com/sourcegraph/sourcegraph) (and possibly others) refers to something in Go.
- Commit: https://github.com/sourcegraph/sourcegraph/commit/a88d90a8302c492282186d39718cd8fb093c14fa

```
module: github.com/sourcegraph/sourcegraph
package: sourcegraph
description: |
    Sourcegraph is a code search and navigation engine. Sourcegraph prior to version 3.33.2 is vulnerable to a side-channel attack where strings in private source code could be guessed by an authenticated but unauthorized actor. This issue affects the Saved Searches and Code Monitoring features. A successful attack would require an authenticated bad actor to create many Saved Searches or Code Monitors to receive confirmation that a specific string exists. This could allow an attacker to guess formatted tokens in source code, such as API keys. This issue was patched in version 3.33.2 and any future versions of Sourcegraph. We strongly encourage upgrading to secure versions. If you are unable to, you may disable Saved Searches and Code Monitors.
cves:
  - CVE-2021-43823
links:
    commit: https://github.com/sourcegraph/sourcegraph/commit/a88d90a8302c492282186d39718cd8fb093c14fa
    context:
      - https://github.com/sourcegraph/sourcegraph/security/advisories/GHSA-cpq7-hmvv-29w9

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
