### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/crypto-org-chain/cronos: CVE-2021-43839

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#283]
In [CVE-2021-43839](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43839.json), the reference URL [github.com/crypto-org-chain/cronos](github.com/crypto-org-chain/cronos) (and possibly others) refers to something in Go.
- Commit: https://github.com/crypto-org-chain/cronos/commit/150ef237b37ac28c8136e1c0f494932860b9ebe8
- PR: https://github.com/crypto-org-chain/cronos/pull/270

```
module: github.com/crypto-org-chain/cronos
package: cronos
description: |
    Cronos is a commercial implementation of a blockchain. In Cronos nodes running versions before v0.6.5, it is possible to take transaction fees from Cosmos SDK's FeeCollector for the current block by sending a custom crafted MsgEthereumTx. This problem has been patched in Cronos v0.6.5. There are no tested workarounds. All validator node operators are recommended to upgrade to Cronos v0.6.5 at their earliest possible convenience.
cves:
  - CVE-2021-43839
links:
    pr: https://github.com/crypto-org-chain/cronos/pull/270
    commit: https://github.com/crypto-org-chain/cronos/commit/150ef237b37ac28c8136e1c0f494932860b9ebe8
    context:
      - https://github.com/crypto-org-chain/cronos/security/advisories/GHSA-f854-hpxv-cw9r

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
