### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/minio/minio: CVE-2021-43858

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#285]
In [CVE-2021-43858](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/43xxx/CVE-2021-43858.json), the reference URL [github.com/minio/minio](github.com/minio/minio) (and possibly others) refers to something in Go.
- Commit: https://github.com/minio/minio/commit/5a96cbbeaabd0a82b0fe881378e7c21c85091abf
- PR: https://github.com/minio/minio/pull/7949

```
module: github.com/minio/minio
package: minio
description: |
    MinIO is a Kubernetes native application for cloud storage. Prior to version `RELEASE.2021-12-27T07-23-18Z`, a malicious client can hand-craft an HTTP API call that allows for updating policy for a user and gaining higher privileges. The patch in version `RELEASE.2021-12-27T07-23-18Z` changes the accepted request body type and removes the ability to apply policy changes through this API. There is a workaround for this vulnerability: Changing passwords can be disabled by adding an explicit `Deny` rule to disable the API for users.
cves:
  - CVE-2021-43858
links:
    pr: https://github.com/minio/minio/pull/7949
    commit: https://github.com/minio/minio/commit/5a96cbbeaabd0a82b0fe881378e7c21c85091abf
    context:
      - https://github.com/minio/minio/releases/tag/RELEASE.2021-12-27T07-23-18Z
      - https://github.com/minio/minio/security/advisories/GHSA-j6jc-jqqc-p6cx

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
