### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/unicorn-engine/unicorn: CVE-2021-44078

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#286]
In [CVE-2021-44078](https://github.com/CVEProject/cvelist/tree/4ea21dc0de9810f415419d4f79b4107c275ca371/2021/44xxx/CVE-2021-44078.json), the reference URL [github.com/unicorn-engine/unicorn](github.com/unicorn-engine/unicorn) (and possibly others) refers to something in Go.
- Commit: https://github.com/unicorn-engine/unicorn/commit/c733bbada356b0373fa8aa72c044574bb855fd24

```
module: github.com/unicorn-engine/unicorn
package: n/a
description: |
    An issue was discovered in split_region in uc.c in Unicorn Engine before 2.0.0-rc5. It allows local attackers to escape the sandbox. An attacker must first obtain the ability to execute crafted code in the target sandbox in order to exploit this vulnerability. The specific flaw exists within the virtual memory manager. The issue results from the faulty comparison of GVA and GPA while calling uc_mem_map_ptr to free part of a claimed memory block. An attacker can leverage this vulnerability to escape the sandbox and execute arbitrary code on the host machine.
cves:
  - CVE-2021-44078
links:
    commit: https://github.com/unicorn-engine/unicorn/commit/c733bbada356b0373fa8aa72c044574bb855fd24
    context:
      - https://gist.github.com/jwang-a/cb4b6e9551457aa299066076b836a2cd
      - https://github.com/jwang-a/CTF/blob/master/MyChallenges/Pwn/Unicorns_Aisle/UnicornsAisle.pdf
      - https://github.com/unicorn-engine/unicorn/compare/2.0.0-rc4...2.0.0-rc5
      - https://www.unicorn-engine.org/changelog/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
