### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/Ericsson/codechecker: CVE-2021-44217

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#287]
In [CVE-2021-44217](https://github.com/CVEProject/cvelist/tree/a7787075663b6fc5d38ce4e211e43bfeb1838cfd/2021/44xxx/CVE-2021-44217.json), the reference URL [github.com/Ericsson/codechecker](github.com/Ericsson/codechecker) (and possibly others) refers to something in Go.
- PR: https://github.com/Ericsson/codechecker/pull/3549

```
module: github.com/Ericsson/codechecker
package: n/a
description: |
    In Ericsson CodeChecker through 6.18.0, a Stored Cross-site scripting (XSS) vulnerability in the comments component of the reports viewer allows remote attackers to inject arbitrary web script or HTML via the POST JSON data of the /CodeCheckerService API.
cves:
  - CVE-2021-44217
links:
    pr: https://github.com/Ericsson/codechecker/pull/3549
    context:
      - https://codechecker-demo.eastus.cloudapp.azure.com/
      - https://github.com/Ericsson/codechecker/releases
      - https://github.com/Hyperkopite/CVE-2021-44217/blob/main/README.md
      - https://user-images.githubusercontent.com/9525971/142965091-e118b012-a7fc-4c2f-ad0c-80aeed6f7ec9.png

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
