### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/authzed/spicedb: CVE-2022-21646

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#295]
In [CVE-2022-21646](https://github.com/CVEProject/cvelist/tree/e956d9d5b816c91371f21f82178cf9a9c52f040a/2022/21xxx/CVE-2022-21646.json), the reference URL [github.com/authzed/spicedb](github.com/authzed/spicedb) (and possibly others) refers to something in Go.
- Commit: https://github.com/authzed/spicedb/commit/15bba2e2d2a4bda336a37a7fe8ef8a35028cd970

```
module: github.com/authzed/spicedb
package: spicedb
description: |
    SpiceDB is a database system for managing security-critical application permissions. Any user making use of a wildcard relationship under the right hand branch of an `exclusion` or within an `intersection` operation will see `Lookup`/`LookupResources` return a resource as "accessible" if it is *not* accessible by virtue of the inclusion of the wildcard in the intersection or the right side of the exclusion. In `v1.3.0`, the wildcard is ignored entirely in lookup's dispatch, resulting in the `banned` wildcard being ignored in the exclusion. Version 1.4.0 contains a patch for this issue. As a workaround, don't make use of wildcards on the right side of intersections or within exclusions.
cves:
  - CVE-2022-21646
links:
    commit: https://github.com/authzed/spicedb/commit/15bba2e2d2a4bda336a37a7fe8ef8a35028cd970
    context:
      - https://github.com/authzed/spicedb/issues/358
      - https://github.com/authzed/spicedb/releases/tag/v1.4.0
      - https://github.com/authzed/spicedb/security/advisories/GHSA-7p8f-8hjm-wm92

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
