### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/github/gh-ost: CVE-2022-21687

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#298]
In [CVE-2022-21687](https://github.com/CVEProject/cvelist/tree/a7787075663b6fc5d38ce4e211e43bfeb1838cfd/2022/21xxx/CVE-2022-21687.json), the reference URL [github.com/github/gh-ost](github.com/github/gh-ost) (and possibly others) refers to something in Go.
- Commit: https://github.com/github/gh-ost/commit/a91ab042de013cfd8fbb633763438932d9080d8f

```
module: github.com/github/gh-ost
package: n/a
description: |
    gh-ost is a triggerless online schema migration solution for MySQL. Versions prior to 1.1.3 are subject to an arbitrary file read vulnerability. The attacker must have access to the target host or trick an administrator into executing a malicious gh-ost command on a host running gh-ost, plus network access from host running gh-ost to the attack's malicious MySQL server. The `-database` parameter does not properly sanitize user input which can lead to arbitrary file reads.
cves:
  - CVE-2022-21687
links:
    commit: https://github.com/github/gh-ost/commit/a91ab042de013cfd8fbb633763438932d9080d8f
    context:
      - https://github.com/github/gh-ost/security/advisories/GHSA-rrp4-2xx3-mv29

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
