### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/graph-gophers/graphql-go: CVE-2022-21708

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#300]
In [CVE-2022-21708](https://github.com/CVEProject/cvelist/tree/a7787075663b6fc5d38ce4e211e43bfeb1838cfd/2022/21xxx/CVE-2022-21708.json), the reference URL [github.com/graph-gophers/graphql-go](github.com/graph-gophers/graphql-go) (and possibly others) refers to something in Go.
- Commit: https://github.com/graph-gophers/graphql-go/commit/eae31ca73eb3473c544710955d1dbebc22605bfe

```
module: github.com/graph-gophers/graphql-go
package: graphql-go
description: |
    graphql-go is a GraphQL server with a focus on ease of use. In versions prior to 1.3.0 there exists a DoS vulnerability that is possible due to a bug in the library that would allow an attacker with specifically designed queries to cause stack overflow panics. Any user with access to the GraphQL handler can send these queries and cause stack overflows. This in turn could potentially compromise the ability of the server to serve data to its users. The issue has been patched in version `v1.3.0`. The only known workaround for this issue is to disable the `graphql.MaxDepth` option from your schema which is not recommended.
cves:
  - CVE-2022-21708
links:
    commit: https://github.com/graph-gophers/graphql-go/commit/eae31ca73eb3473c544710955d1dbebc22605bfe
    context:
      - https://github.com/graph-gophers/graphql-go/security/advisories/GHSA-mh3m-8c74-74xh

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
