### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/navidrome/navidrome: CVE-2022-23857

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#302]
In [CVE-2022-23857](https://github.com/CVEProject/cvelist/tree/a7787075663b6fc5d38ce4e211e43bfeb1838cfd/2022/23xxx/CVE-2022-23857.json), the reference URL [github.com/navidrome/navidrome](github.com/navidrome/navidrome) (and possibly others) refers to something in Go.
- Commit: https://github.com/navidrome/navidrome/commit/9e79b5cbf2a48c1e4344df00fea4ed3844ea965d

```
module: github.com/navidrome/navidrome
package: n/a
description: |
    model/criteria/criteria.go in Navidrome before 0.47.5 is vulnerable to SQL injection attacks when processing crafted Smart Playlists. An authenticated user could abuse this to extract arbitrary data from the database, including the user table (which contains sensitive information such as the users' encrypted passwords).
cves:
  - CVE-2022-23857
links:
    commit: https://github.com/navidrome/navidrome/commit/9e79b5cbf2a48c1e4344df00fea4ed3844ea965d
    context:
      - https://github.com/navidrome/navidrome/releases/tag/v0.47.5

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
