### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/casdoor/casdoor: CVE-2022-24124

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#303]
In [CVE-2022-24124](https://github.com/CVEProject/cvelist/tree/a7787075663b6fc5d38ce4e211e43bfeb1838cfd/2022/24xxx/CVE-2022-24124.json), the reference URL [github.com/casdoor/casdoor](github.com/casdoor/casdoor) (and possibly others) refers to something in Go.
- PR: https://github.com/casdoor/casdoor/pull/442

```
module: github.com/casdoor/casdoor
package: n/a
description: |
    The query API in Casdoor before 1.13.1 has a SQL injection vulnerability related to the field and value parameters, as demonstrated by api/get-organizations.
cves:
  - CVE-2022-24124
links:
    pr: https://github.com/casdoor/casdoor/pull/442
    context:
      - https://github.com/casdoor/casdoor/compare/v1.13.0...v1.13.1
      - https://github.com/casdoor/casdoor/issues/439

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
