### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/agent: CVE-2021-41090

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#305]
In [CVE-2021-41090](https://github.com/CVEProject/cvelist/tree/dcc06c8e122507d6080bf313e8be9e3aeb912109/2021/41xxx/CVE-2021-41090.json), the reference URL [github.com/grafana/agent](github.com/grafana/agent) (and possibly others) refers to something in Go.
- Commit: https://github.com/grafana/agent/commit/af7fb01e31fe2d389e5f1c36b399ddc46b412b21
- PR: https://github.com/grafana/agent/pull/1152

```
module: github.com/grafana/agent
package: agent
description: |
    Grafana Agent is a telemetry collector for sending metrics, logs, and trace data to the opinionated Grafana observability stack. Prior to versions 0.20.1 and 0.21.2, inline secrets defined within a metrics instance config are exposed in plaintext over two endpoints: metrics instance configs defined in the base YAML file are exposed at `/-/config` and metrics instance configs defined for the scraping service are exposed at `/agent/api/v1/configs/:key`. Inline secrets will be exposed to anyone being able to reach these endpoints. If HTTPS with client authentication is not configured, these endpoints are accessible to unauthenticated users. Secrets found in these sections are used for delivering metrics to a Prometheus Remote Write system, authenticating against a system for discovering Prometheus targets, and authenticating against a system for collecting metrics. This does not apply for non-inlined secrets, such as `*_file` based secrets. This issue is patched in Grafana Agent versions 0.20.1 and 0.21.2. A few workarounds are available. Users who cannot upgrade should use non-inline secrets where possible. Users may also desire to restrict API access to Grafana Agent with some combination of restricting the network interfaces Grafana Agent listens on through `http_listen_address` in the `server` block, configuring Grafana Agent to use HTTPS with client authentication, and/or using firewall rules to restrict external access to Grafana Agent's API.
cves:
  - CVE-2021-41090
links:
    pr: https://github.com/grafana/agent/pull/1152
    commit: https://github.com/grafana/agent/commit/af7fb01e31fe2d389e5f1c36b399ddc46b412b21
    context:
      - https://github.com/grafana/agent/releases/tag/v0.20.1
      - https://github.com/grafana/agent/releases/tag/v0.21.2
      - https://github.com/grafana/agent/security/advisories/GHSA-9c4x-5hgq-q3wh
      - https://security.netapp.com/advisory/ntap-20211229-0004/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
