### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-45325

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#308]
In [CVE-2021-45325](https://github.com/CVEProject/cvelist/tree/303996bf6630e0d73e077f5024e606d02de4d855/2021/45xxx/CVE-2021-45325.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/5705

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    Server Side Request Forgery (SSRF) vulneraility exists in Gitea before 1.7.0 using the OpenID URL.
cves:
  - CVE-2021-45325
links:
    pr: https://github.com/go-gitea/gitea/pull/5705
    context:
      - https://blog.gitea.io/2019/01/gitea-1.7.0-is-released/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
