### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-45326

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#309]
In [CVE-2021-45326](https://github.com/CVEProject/cvelist/tree/303996bf6630e0d73e077f5024e606d02de4d855/2021/45xxx/CVE-2021-45326.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/4840

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    Cross Site Request Forgery (CSRF) vulnerability exists in Gitea before 1.5.2 via API routes.This can be dangerous especially with state altering POST requests.
cves:
  - CVE-2021-45326
links:
    pr: https://github.com/go-gitea/gitea/pull/4840
    context:
      - https://blog.gitea.io/2018/10/gitea-1.5.2-is-released/
      - https://github.com/go-gitea/gitea/issues/4838

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
