### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-45327

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#310]
In [CVE-2021-45327](https://github.com/CVEProject/cvelist/tree/303996bf6630e0d73e077f5024e606d02de4d855/2021/45xxx/CVE-2021-45327.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/10582

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    Gitea before 1.11.2 is affected by Trusting HTTP Permission Methods on the Server Side when referencing the vulnerable admin or user API. which could let a remote malisious user execute arbitrary code.
cves:
  - CVE-2021-45327
links:
    pr: https://github.com/go-gitea/gitea/pull/10582
    context:
      - https://blog.gitea.io/2020/03/gitea-1.11.2-is-released/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
