### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2022-21702

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#311]
In [CVE-2022-21702](https://github.com/CVEProject/cvelist/tree/e306876e7726400c8ff4d8ce9f90bda8f097ab16/2022/21xxx/CVE-2022-21702.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- Commit: https://github.com/grafana/grafana/commit/27726868b3d7c613844b55cd209ca93645c99b85

```
module: github.com/grafana/grafana
package: grafana
description: |
    Grafana is an open-source platform for monitoring and observability. In affected versions an attacker could serve HTML content thru the Grafana datasource or plugin proxy and trick a user to visit this HTML page using a specially crafted link and execute a Cross-site Scripting (XSS) attack. The attacker could either compromise an existing datasource for a specific Grafana instance or either set up its own public service and instruct anyone to set it up in their Grafana instance. To be impacted, all of the following must be applicable. For the data source proxy: A Grafana HTTP-based datasource configured with Server as Access Mode and a URL set, the attacker has to be in control of the HTTP server serving the URL of above datasource, and a specially crafted link pointing at the attacker controlled data source must be clicked on by an authenticated user. For the plugin proxy: A Grafana HTTP-based app plugin configured and enabled with a URL set, the attacker has to be in control of the HTTP server serving the URL of above app, and a specially crafted link pointing at the attacker controlled plugin must be clocked on by an authenticated user. For the backend plugin resource: An attacker must be able to navigate an authenticated user to a compromised plugin through a crafted link. Users are advised to update to a patched version. There are no known workarounds for this vulnerability.
cves:
  - CVE-2022-21702
links:
    commit: https://github.com/grafana/grafana/commit/27726868b3d7c613844b55cd209ca93645c99b85
    context:
      - https://github.com/grafana/grafana/security/advisories/GHSA-xc3p-28hw-q24g
      - https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
