### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2022-21713

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#313]
In [CVE-2022-21713](https://github.com/CVEProject/cvelist/tree/1e11dd56a6e0b9506c401abd6473ed7fbaae351b/2022/21xxx/CVE-2022-21713.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- PR: https://github.com/grafana/grafana/pull/45083

```
module: github.com/grafana/grafana
package: grafana
description: |
    Grafana is an open-source platform for monitoring and observability. Affected versions of Grafana expose multiple API endpoints which do not properly handle user authorization. `/teams/:teamId` will allow an authenticated attacker to view unintended data by querying for the specific team ID, `/teams/:search` will allow an authenticated attacker to search for teams and see the total number of available teams, including for those teams that the user does not have access to, and `/teams/:teamId/members` when editors_can_admin flag is enabled, an authenticated attacker can see unintended data by querying for the specific team ID. Users are advised to upgrade as soon as possible. There are no known workarounds for this issue.
cves:
  - CVE-2022-21713
links:
    pr: https://github.com/grafana/grafana/pull/45083
    context:
      - https://github.com/grafana/grafana/security/advisories/GHSA-63g3-9jq3-mccv
      - https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
