### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-45329

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#314]
In [CVE-2021-45329](https://github.com/CVEProject/cvelist/tree/ea3690375ec0b3af81e9ff306f1c474d5b4f806e/2021/45xxx/CVE-2021-45329.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/4710

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    Cross Site Scripting (XSS) vulnerability exists in Gitea before 1.5.1 via the repository settings inside the external wiki/issue tracker URL field.
cves:
  - CVE-2021-45329
links:
    pr: https://github.com/go-gitea/gitea/pull/4710
    context:
      - https://blog.gitea.io/2018/09/gitea-1.5.1-is-released/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
