### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-45331

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#315]
In [CVE-2021-45331](https://github.com/CVEProject/cvelist/tree/5b5b7ef00726821d01df0d8cf5b5174dd5596d77/2021/45xxx/CVE-2021-45331.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/3878

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    An Authentication Bypass vulnerability exists in Gitea before 1.5.0, which could let a malicious user gain privileges. If captured, the TOTP code for the 2FA can be submitted correctly more than once.
cves:
  - CVE-2021-45331
links:
    pr: https://github.com/go-gitea/gitea/pull/3878
    context:
      - https://blog.gitea.io/2018/08/gitea-1.5.0-is-released/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
