### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/portainer/agent: CVE-2022-24961

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#320]
In [CVE-2022-24961](https://github.com/CVEProject/cvelist/tree/09c7a983f2b1d5b7f96e0ce2e72cad340e359be3/2022/24xxx/CVE-2022-24961.json), the reference URL [github.com/portainer/agent](github.com/portainer/agent) (and possibly others) refers to something in Go.
- Commit: https://github.com/portainer/agent/pull/225/commits/a66977c76043fcff4a8f69c4b65988272d27c01f

```
module: github.com/portainer/agent
package: n/a
description: |
    In Portainer Agent before 2.11.1, an API server can continue running even if not associated with a Portainer instance in the past few days.
cves:
  - CVE-2022-24961
links:
    commit: https://github.com/portainer/agent/pull/225/commits/a66977c76043fcff4a8f69c4b65988272d27c01f
    context:
      - https://github.com/portainer/agent/compare/2.11.0...2.11.1
      - https://github.com/portainer/portainer/issues/6420
      - https://www.portainer.io/blog/should-you-expose-portainer-or-agent-to-the-internet

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
