### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sourcegraph/sourcegraph: CVE-2022-23643

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#324]
In [CVE-2022-23643](https://github.com/CVEProject/cvelist/tree/44434f26ca69dec585cf77aae5c404de44fc8c29/2022/23xxx/CVE-2022-23643.json), the reference URL [github.com/sourcegraph/sourcegraph](github.com/sourcegraph/sourcegraph) (and possibly others) refers to something in Go.
- PR: https://github.com/sourcegraph/sourcegraph/pull/30547

```
module: github.com/sourcegraph/sourcegraph
package: sourcegraph
description: |
    Sourcegraph is a code search and navigation engine. Sourcegraph versions 3.35 and 3.36 reintroduced a previously fixed side-channel vulnerabilitity in the Code Monitoring feature where strings in private source code could be guessed by an authenticated but unauthorized actor. This issue affects only the Code Monitoring feature, whereas CVE-2021-43823 also affected saved searches. A successful attack would require an authenticated bad actor to create many Code Monitors to receive confirmation that a specific string exists. This could allow an attacker to guess formatted tokens in source code, such as API keys. This issue was patched in versions 3.35.2 and 3.36.3 of Sourcegraph. Those who are unable to upgrade may disable the Code Monitor feature in their installation.
cves:
  - CVE-2022-23643
links:
    pr: https://github.com/sourcegraph/sourcegraph/pull/30547
    context:
      - https://github.com/sourcegraph/sourcegraph/security/advisories/GHSA-xqv2-x6f2-w3pf

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
