### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/traefik/traefik: CVE-2022-23632

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#325]
In [CVE-2022-23632](https://github.com/CVEProject/cvelist/tree/4b60dd8aceab0b15c69a18a2914b7d560b0d5107/2022/23xxx/CVE-2022-23632.json), the reference URL [github.com/traefik/traefik](github.com/traefik/traefik) (and possibly others) refers to something in Go.
- PR: https://github.com/traefik/traefik/pull/8764

```
module: github.com/traefik/traefik
package: traefik
description: |
    Traefik is an HTTP reverse proxy and load balancer. Prior to version 2.6.1, Traefik skips the router transport layer security (TLS) configuration when the host header is a fully qualified domain name (FQDN). For a request, the TLS configuration choice can be different than the router choice, which implies the use of a wrong TLS configuration. When sending a request using FQDN handled by a router configured with a dedicated TLS configuration, the TLS configuration falls back to the default configuration that might not correspond to the configured one. If the CNAME flattening is enabled, the selected TLS configuration is the SNI one and the routing uses the CNAME value, so this can skip the expected TLS configuration. Version 2.6.1 contains a patch for this issue. As a workaround, one may add the FDQN to the host rule. However, there is no workaround if the CNAME flattening is enabled.
cves:
  - CVE-2022-23632
links:
    pr: https://github.com/traefik/traefik/pull/8764
    context:
      - https://github.com/traefik/traefik/releases/tag/v2.6.1
      - https://github.com/traefik/traefik/security/advisories/GHSA-hrhx-6h34-j5hc

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
