### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sigstore/cosign: CVE-2022-23649

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#326]
In [CVE-2022-23649](https://github.com/CVEProject/cvelist/tree/9c8d2a99a565d86ae4f517c7b042629c592e3c26/2022/23xxx/CVE-2022-23649.json), the reference URL [github.com/sigstore/cosign](github.com/sigstore/cosign) (and possibly others) refers to something in Go.
- Commit: https://github.com/sigstore/cosign/commit/96d410a6580e4e81d24d112a0855c70ca3fb5b49

```
module: github.com/sigstore/cosign
package: cosign
description: |
    Cosign provides container signing, verification, and storage in an OCI registry for the sigstore project. Prior to version 1.5.2, Cosign can be manipulated to claim that an entry for a signature exists in the Rekor transparency log even if it doesn't. This requires the attacker to have pull and push permissions for the signature in OCI. This can happen with both standard signing with a keypair and "keyless signing" with Fulcio. If an attacker has access to the signature in OCI, they can manipulate cosign into believing the entry was stored in Rekor even though it wasn't. The vulnerability has been patched in v1.5.2 of Cosign. The `signature` in the `signedEntryTimestamp` provided by Rekor is now compared to the `signature` that is being verified. If these don't match, then an error is returned. If a valid bundle is copied to a different signature, verification should fail.  Cosign output now only informs the user that certificates were verified if a certificate was in fact verified. There is currently no known workaround.
cves:
  - CVE-2022-23649
links:
    commit: https://github.com/sigstore/cosign/commit/96d410a6580e4e81d24d112a0855c70ca3fb5b49
    context:
      - https://github.com/sigstore/cosign/security/advisories/GHSA-ccxc-vr6p-4858

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
