### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sourcegraph/sourcegraph: CVE-2022-23642

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#327]
In [CVE-2022-23642](https://github.com/CVEProject/cvelist/tree/55281222cf863a3a05468dabae13704c44fe2ca3/2022/23xxx/CVE-2022-23642.json), the reference URL [github.com/sourcegraph/sourcegraph](github.com/sourcegraph/sourcegraph) (and possibly others) refers to something in Go.
- PR: https://github.com/sourcegraph/sourcegraph/pull/30833

```
module: github.com/sourcegraph/sourcegraph
package: sourcegraph
description: |
    Sourcegraph is a code search and navigation engine. Sourcegraph prior to version 3.37 is vulnerable to remote code execution in the `gitserver` service. The service acts as a git exec proxy, and fails to properly restrict calling `git config`. This allows an attacker to set the git `core.sshCommand` option, which sets git to use the specified command instead of ssh when they need to connect to a remote system.  Exploitation of this vulnerability depends on how Sourcegraph is deployed. An attacker able to make HTTP requests to internal services like gitserver is able to exploit it. This issue is patched in Sourcegraph version 3.37. As a workaround, ensure that requests to gitserver are properly protected.
cves:
  - CVE-2022-23642
links:
    pr: https://github.com/sourcegraph/sourcegraph/pull/30833
    context:
      - https://github.com/sourcegraph/sourcegraph/security/advisories/GHSA-qcmp-fx72-q8q9

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
