### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/gravitl/netmaker: CVE-2022-23650

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#328]
In [CVE-2022-23650](https://github.com/CVEProject/cvelist/tree/55281222cf863a3a05468dabae13704c44fe2ca3/2022/23xxx/CVE-2022-23650.json), the reference URL [github.com/gravitl/netmaker](github.com/gravitl/netmaker) (and possibly others) refers to something in Go.
- Commit: https://github.com/gravitl/netmaker/commit/e9bce264719f88c30e252ecc754d08f422f4c080

```
module: github.com/gravitl/netmaker
package: netmaker
description: |
    Netmaker is a platform for creating and managing virtual overlay networks using WireGuard. Prior to versions 0.8.5, 0.9.4, and 010.0, there is a hard-coded cryptographic key in the code base which can be exploited to run admin commands on a remote server if the exploiter know the address and username of the admin. This effects the server (netmaker) component, and not clients. This has been patched in Netmaker v0.8.5, v0.9.4, and v0.10.0. There are currently no known workarounds.
cves:
  - CVE-2022-23650
links:
    commit: https://github.com/gravitl/netmaker/commit/e9bce264719f88c30e252ecc754d08f422f4c080
    context:
      - https://github.com/gravitl/netmaker/security/advisories/GHSA-86f3-hf24-76q4

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
