### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/clastix/capsule-proxy: CVE-2022-23652

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#329]
In [CVE-2022-23652](https://github.com/CVEProject/cvelist/tree/da3f10dd9d364bd20ecc034798acbe68451ead59/2022/23xxx/CVE-2022-23652.json), the reference URL [github.com/clastix/capsule-proxy](github.com/clastix/capsule-proxy) (and possibly others) refers to something in Go.
- Commit: https://github.com/clastix/capsule-proxy/commit/efe91f68ebf8a9e3d21491dc57da7b8a746415d8

```
module: github.com/clastix/capsule-proxy
package: capsule-proxy
description: |+
    capsule-proxy is a reverse proxy for Capsule Operator which provides multi-tenancy in Kubernetes. In versions prior to 0.2.1 an attacker with a proper authentication mechanism may use a malicious `Connection` header to start a privilege escalation attack towards the Kubernetes API Server. This vulnerability allows for an exploit of the `cluster-admin` Role bound to `capsule-proxy`. There are no known workarounds for this issue.

cves:
  - CVE-2022-23652
links:
    commit: https://github.com/clastix/capsule-proxy/commit/efe91f68ebf8a9e3d21491dc57da7b8a746415d8
    context:
      - https://github.com/clastix/capsule-proxy/issues/188
      - https://github.com/clastix/capsule-proxy/security/advisories/GHSA-9cwv-cppx-mqjm

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
