### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2021-43824

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#330]
In [CVE-2021-43824](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2021/43xxx/CVE-2021-43824.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/9371333230b1a6e1be2eccf4868771e11af6253a

```
module: github.com/envoyproxy/envoy
package: envoy
description: |+
    Envoy is an open source edge and service proxy, designed for cloud-native applications. In affected versions a crafted request crashes Envoy when a CONNECT request is sent to JWT filter configured with regex match. This provides a denial of service attack vector. The only workaround is to not use regex in the JWT filter. Users are advised to upgrade.

cves:
  - CVE-2021-43824
links:
    commit: https://github.com/envoyproxy/envoy/commit/9371333230b1a6e1be2eccf4868771e11af6253a
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-vj5m-rch8-5r2p

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
