### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2021-43825

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#331]
In [CVE-2021-43825](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2021/43xxx/CVE-2021-43825.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/148de954ed3585d8b4298b424aa24916d0de6136

```
module: github.com/envoyproxy/envoy
package: envoy
description: |
    Envoy is an open source edge and service proxy, designed for cloud-native applications. Sending a locally generated response must stop further processing of request or response data. Envoy tracks the amount of buffered request and response data and aborts the request if the amount of buffered data is over the limit by sending 413 or 500 responses. However when the buffer overflows while response is processed by the filter chain the operation may not be aborted correctly and result in accessing a freed memory block. If this happens Envoy will crash resulting in a denial of service.
cves:
  - CVE-2021-43825
links:
    commit: https://github.com/envoyproxy/envoy/commit/148de954ed3585d8b4298b424aa24916d0de6136
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-h69p-g6xg-mhhh

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
