### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2021-43826

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#332]
In [CVE-2021-43826](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2021/43xxx/CVE-2021-43826.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/ce0ae309057a216aba031aff81c445c90c6ef145

```
module: github.com/envoyproxy/envoy
package: envoy
description: |
    Envoy is an open source edge and service proxy, designed for cloud-native applications. In affected versions of Envoy a crash occurs when configured for :ref:`upstream tunneling <envoy_v3_api_field_extensions.filters.network.tcp_proxy.v3.TcpProxy.tunneling_config>` and the downstream connection disconnects while the the upstream connection or http/2 stream is still being established. There are no workarounds for this issue. Users are advised to upgrade.
cves:
  - CVE-2021-43826
links:
    commit: https://github.com/envoyproxy/envoy/commit/ce0ae309057a216aba031aff81c445c90c6ef145
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-cmx3-fvgf-83mf

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
