### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2022-21654

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#333]
In [CVE-2022-21654](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2022/21xxx/CVE-2022-21654.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/e9f936d85dc1edc34fabd0a1725ec180f2316353

```
module: github.com/envoyproxy/envoy
package: envoy
description: |+
    Envoy is an open source edge and service proxy, designed for cloud-native applications. Envoy's tls allows re-use when some cert validation settings have changed from their default configuration. The only workaround for this issue is to ensure that default tls settings are used. Users are advised to upgrade.

cves:
  - CVE-2022-21654
links:
    commit: https://github.com/envoyproxy/envoy/commit/e9f936d85dc1edc34fabd0a1725ec180f2316353
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-5j4x-g36v-m283

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
