### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2022-21655

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#334]
In [CVE-2022-21655](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2022/21xxx/CVE-2022-21655.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/177d608155ba8b11598b9bbf8240e90d8c350682

```
module: github.com/envoyproxy/envoy
package: envoy
description: |
    Envoy is an open source edge and service proxy, designed for cloud-native applications. The envoy common router will segfault if an internal redirect selects a route configured with direct response or redirect actions. This will result in a denial of service. As a workaround turn off internal redirects if direct response entries are configured on the same listener.
cves:
  - CVE-2022-21655
links:
    commit: https://github.com/envoyproxy/envoy/commit/177d608155ba8b11598b9bbf8240e90d8c350682
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-7r5p-7fmh-jxpg

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
