### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2022-23606

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#337]
In [CVE-2022-23606](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2022/23xxx/CVE-2022-23606.json), the reference URL [github.com/envoyproxy/envoy](github.com/envoyproxy/envoy) (and possibly others) refers to something in Go.
- Commit: https://github.com/envoyproxy/envoy/commit/4b6dd3b53cd5c6d4d4df378a2fc62c1707522b31

```
module: github.com/envoyproxy/envoy
package: envoy
description: |+
    Envoy is an open source edge and service proxy, designed for cloud-native applications. When a cluster is deleted via Cluster Discovery Service (CDS) all idle connections established to endpoints in that cluster are disconnected. A recursion was introduced in the procedure of disconnecting idle connections that can lead to stack exhaustion and abnormal process termination when a cluster has a large number of idle connections. This infinite recursion causes Envoy to crash. Users are advised to upgrade.

cves:
  - CVE-2022-23606
links:
    commit: https://github.com/envoyproxy/envoy/commit/4b6dd3b53cd5c6d4d4df378a2fc62c1707522b31
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-9vp2-4cp7-vvxf

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
