### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/istio/istio/security: CVE-2022-23635

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#338]
In [CVE-2022-23635](https://github.com/CVEProject/cvelist/tree/bb8724309c97800cd1d6624ad1ad903409c3e949/2022/23xxx/CVE-2022-23635.json), the reference URL [github.com/istio/istio/security](github.com/istio/istio/security) (and possibly others) refers to something in Go.
- Commit: https://github.com/istio/istio/commit/5f3b5ed958ae75156f8656fe7b3794f78e94db84

```
module: github.com/istio/istio/security
package: istio
description: |+
    Istio is an open platform to connect, manage, and secure microservices. In affected versions the Istio control plane, `istiod`, is vulnerable to a request processing error, allowing a malicious attacker that sends a specially crafted message which results in the control plane crashing. This endpoint is served over TLS port 15012, but does not require any authentication from the attacker. For simple installations, Istiod is typically only reachable from within the cluster, limiting the blast radius. However, for some deployments, especially [multicluster](https://istio.io/latest/docs/setup/install/multicluster/primary-remote/) topologies, this port is exposed over the public internet. There are no effective workarounds, beyond upgrading. Limiting network access to Istiod to the minimal set of clients can help lessen the scope of the vulnerability to some extent.

cves:
  - CVE-2022-23635
links:
    commit: https://github.com/istio/istio/commit/5f3b5ed958ae75156f8656fe7b3794f78e94db84
    context:
      - https://github.com/istio/istio/security/advisories/GHSA-856q-xv3c-7f2f
      - https://istio.io/latest/news/security/istio-security-2022-003

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
