### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/grafana/grafana: CVE-2018-18623

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#342]
In [CVE-2018-18623](https://github.com/CVEProject/cvelist/tree/cfbeb9aae0d0119f6af8c342e1a17cdfd138fb70/2018/18xxx/CVE-2018-18623.json), the reference URL [github.com/grafana/grafana](github.com/grafana/grafana) (and possibly others) refers to something in Go.
- PR: https://github.com/grafana/grafana/pull/11813

```
module: github.com/grafana/grafana
package: n/a
description: |
    Grafana 5.3.1 has XSS via the "Dashboard > Text Panel" screen. NOTE: this issue exists because of an incomplete fix for CVE-2018-12099.
cves:
  - CVE-2018-18623
links:
    pr: https://github.com/grafana/grafana/pull/11813
    context:
      - https://github.com/grafana/grafana/issues/15293
      - https://github.com/grafana/grafana/releases/tag/v6.0.0
      - https://security.netapp.com/advisory/ntap-20200608-0008/

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
