### ISSUE TITLE
x/vulndb: potential Go vuln in gitlab.com/nbdkit/nbdkit: CVE-2021-3716

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#343]
In [CVE-2021-3716](https://github.com/CVEProject/cvelist/tree/b8f53bf767d8c04d90dfebd86d11b3dcc9264e41/2021/3xxx/CVE-2021-3716.json), the reference URL [gitlab.com/nbdkit/nbdkit](gitlab.com/nbdkit/nbdkit) (and possibly others) refers to something in Go.
- Commit: https://gitlab.com/nbdkit/nbdkit/-/commit/6c5faac6a37077cf2366388a80862bb00616d0d8

```
module: gitlab.com/nbdkit/nbdkit
package: nbdkit
description: |
    A flaw was found in nbdkit due to to improperly caching plaintext state across the STARTTLS encryption boundary. A MitM attacker could use this flaw to inject a plaintext NBD_OPT_STRUCTURED_REPLY before proxying everything else a client sends to the server, potentially leading the client to terminate the NBD session. The highest threat from this vulnerability is to system availability.
cves:
  - CVE-2021-3716
links:
    commit: https://gitlab.com/nbdkit/nbdkit/-/commit/6c5faac6a37077cf2366388a80862bb00616d0d8
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=1994695
      - https://listman.redhat.com/archives/libguestfs/2021-August/msg00083.html
      - https://www.openwall.com/lists/oss-security/2021/08/18/2

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
