### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containerd/containerd: CVE-2022-23648

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#344]
In [CVE-2022-23648](https://github.com/CVEProject/cvelist/tree/3caa6d4bdc0e7818a9de4364c59a36d806f9fdb3/2022/23xxx/CVE-2022-23648.json), the reference URL [github.com/containerd/containerd](github.com/containerd/containerd) (and possibly others) refers to something in Go.
- Commit: https://github.com/containerd/containerd/commit/10f428dac7cec44c864e1b830a4623af27a9fc70

```
module: github.com/containerd/containerd
package: containerd
description: |
    containerd is a container runtime available as a daemon for Linux and Windows. A bug was found in containerd prior to versions 1.6.1, 1.5.10, and 1.14.12 where containers launched through containerd’s CRI implementation on Linux with a specially-crafted image configuration could gain access to read-only copies of arbitrary files and directories on the host.  This may bypass any policy-based enforcement on container setup (including a Kubernetes Pod Security Policy) and expose potentially sensitive information.  Kubernetes and crictl can both be configured to use containerd’s CRI implementation. This bug has been fixed in containerd 1.6.1, 1.5.10, and 1.4.12.  Users should update to these versions to resolve the issue.
cves:
  - CVE-2022-23648
links:
    commit: https://github.com/containerd/containerd/commit/10f428dac7cec44c864e1b830a4623af27a9fc70
    context:
      - https://github.com/containerd/containerd/releases/tag/v1.4.13
      - https://github.com/containerd/containerd/releases/tag/v1.5.10
      - https://github.com/containerd/containerd/releases/tag/v1.6.1
      - https://github.com/containerd/containerd/security/advisories/GHSA-crp2-qrr5-8pq7

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
