### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containers/buildah: CVE-2021-3602

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#345]
In [CVE-2021-3602](https://github.com/CVEProject/cvelist/tree/c853f3681e0b16e04ca8c81d787a90d4d9286f83/2021/3xxx/CVE-2021-3602.json), the reference URL [github.com/containers/buildah](github.com/containers/buildah) (and possibly others) refers to something in Go.
- Commit: https://github.com/containers/buildah/commit/a468ce0ffd347035d53ee0e26c205ef604097fb0

```
module: github.com/containers/buildah
package: buildah
description: |
    An information disclosure flaw was found in Buildah, when building containers using chroot isolation. Running processes in container builds (e.g. Dockerfile RUN commands) can access environment variables from parent and grandparent processes. When run in a container in a CI/CD environment, environment variables may include sensitive information that was shared with the container in order to be used only by Buildah itself (e.g. container registry credentials).
cves:
  - CVE-2021-3602
links:
    commit: https://github.com/containers/buildah/commit/a468ce0ffd347035d53ee0e26c205ef604097fb0
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=1969264
      - https://github.com/containers/buildah/security/advisories/GHSA-7638-r9r3-rmjj
      - https://ubuntu.com/security/CVE-2021-3602

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
