### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/quay/claircore: CVE-2021-3762

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#346]
In [CVE-2021-3762](https://github.com/CVEProject/cvelist/tree/0fb26f86144b171c617c091b6961230b98005ea6/2021/3xxx/CVE-2021-3762.json), the reference URL [github.com/quay/claircore](github.com/quay/claircore) (and possibly others) refers to something in Go.
- Commit: https://github.com/quay/claircore/commit/691f2023a1720a0579e688b69a2f4bfe1f4b7821
- PR: https://github.com/quay/clair/pull/1380

```
module: github.com/quay/claircore
package: quay/claircore
description: |
    A directory traversal vulnerability was found in the ClairCore engine of Clair. An attacker can exploit this by supplying a crafted container image which, when scanned by Clair, allows for arbitrary file write on the filesystem, potentially allowing for remote code execution.
cves:
  - CVE-2021-3762
links:
    pr: https://github.com/quay/clair/pull/1380
    commit: https://github.com/quay/claircore/commit/691f2023a1720a0579e688b69a2f4bfe1f4b7821
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=2000795
      - https://vulmon.com/exploitdetails?qidtp=maillist_oss_security&qid=d19fce9ede06e13dfb5630ece7f14f83

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
