### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/tharsis/evmos: CVE-2022-24738

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#348]
In [CVE-2022-24738](https://github.com/CVEProject/cvelist/tree/259b3867fd3a58f212e0791c376a509a137a3cf4/2022/24xxx/CVE-2022-24738.json), the reference URL [github.com/tharsis/evmos](github.com/tharsis/evmos) (and possibly others) refers to something in Go.
- Commit: https://github.com/tharsis/evmos/commit/28870258d4ee9f1b8aeef5eba891681f89348f71

```
module: github.com/tharsis/evmos
package: evmos
description: |
    Evmos is the Ethereum Virtual Machine (EVM) Hub on the Cosmos Network. In versions of evmos prior to 2.0.1 attackers are able to drain unclaimed funds from user addresses. To do this an attacker must create a new chain which does not enforce signature verification and connects it to the target evmos instance. The attacker can use this joined chain to transfer unclaimed funds. Users are advised to upgrade. There are no known workarounds for this issue.
cves:
  - CVE-2022-24738
links:
    commit: https://github.com/tharsis/evmos/commit/28870258d4ee9f1b8aeef5eba891681f89348f71
    context:
      - https://github.com/tharsis/evmos/releases/tag/v2.0.1
      - https://github.com/tharsis/evmos/security/advisories/GHSA-5jgq-x857-p8xw

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
