### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/foxcpp/maddy: CVE-2022-24732

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#349]
In [CVE-2022-24732](https://github.com/CVEProject/cvelist/tree/04902521c6ceac69f6efbbb1a96e997a7e6f076f/2022/24xxx/CVE-2022-24732.json), the reference URL [github.com/foxcpp/maddy](github.com/foxcpp/maddy) (and possibly others) refers to something in Go.
- Commit: https://github.com/foxcpp/maddy/commit/7ee6a39c6a1939b376545f030a5efd6f90913583

```
module: github.com/foxcpp/maddy
package: maddy
description: |
    Maddy Mail Server is an open source SMTP compatible email server. Versions of maddy prior to 0.5.4 do not implement password expiry or account expiry checking when authenticating using PAM. Users are advised to upgrade. Users unable to upgrade should manually remove expired accounts via existing filtering mechanisms.
cves:
  - CVE-2022-24732
links:
    commit: https://github.com/foxcpp/maddy/commit/7ee6a39c6a1939b376545f030a5efd6f90913583
    context:
      - https://github.com/foxcpp/maddy/security/advisories/GHSA-6cp7-g972-w9m9

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
