### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/istio/istio/security: CVE-2022-24726

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#352]
In [CVE-2022-24726](https://github.com/CVEProject/cvelist/tree/f69fa6614140c8a4a869b8ad04e404636481a63e/2022/24xxx/CVE-2022-24726.json), the reference URL [github.com/istio/istio/security](github.com/istio/istio/security) (and possibly others) refers to something in Go.
- Commit: https://github.com/istio/istio/commit/6ca5055a4db6695ef5504eabdfde3799f2ea91fd

```
module: github.com/istio/istio/security
package: istio
description: |
    Istio is an open platform to connect, manage, and secure microservices. In affected versions the Istio control plane, istiod, is vulnerable to a request processing error, allowing a malicious attacker that sends a specially crafted message which results in the control plane crashing when the validating webhook for a cluster is exposed publicly. This endpoint is served over TLS port 15017, but does not require any authentication from the attacker. For simple installations, Istiod is typically only reachable from within the cluster, limiting the blast radius. However, for some deployments, especially [external istiod](https://istio.io/latest/docs/setup/install/external-controlplane/) topologies, this port is exposed over the public internet. This issue has been patched in versions 1.13.2, 1.12.5 and 1.11.8. Users are advised to upgrade. Users unable to upgrade should disable access to a validating webhook that is exposed to the public internet or restrict the set of IP addresses that can query it to a set of known, trusted entities.
cves:
  - CVE-2022-24726
links:
    commit: https://github.com/istio/istio/commit/6ca5055a4db6695ef5504eabdfde3799f2ea91fd
    context:
      - https://go.dev/issue/51112
      - https://github.com/istio/istio/security/advisories/GHSA-8w5h-qr4r-2h6g

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
