### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: CVE-2021-29134

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#353]
In [CVE-2021-29134](https://github.com/CVEProject/cvelist/tree/1f9a4d2f96d4f2c4a57516dc25210be152499313/2021/29xxx/CVE-2021-29134.json), the reference URL [github.com/go-gitea/gitea](github.com/go-gitea/gitea) (and possibly others) refers to something in Go.
- PR: https://github.com/go-gitea/gitea/pull/15125/files

```
module: github.com/go-gitea/gitea
package: n/a
description: |
    The avatar middleware in Gitea before 1.13.6 allows Directory Traversal via a crafted URL.
cves:
  - CVE-2021-29134
links:
    pr: https://github.com/go-gitea/gitea/pull/15125/files
    context:
      - https://github.com/go-gitea/gitea/releases
      - https://github.com/go-gitea/gitea/releases/tag/v1.13.6

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
