### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/valyala/fasthttp: CVE-2022-21221

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#355]
In [CVE-2022-21221](https://github.com/CVEProject/cvelist/tree/faf46801d895e70ff4c689311c7d1ef327630817/2022/21xxx/CVE-2022-21221.json), the reference URL [github.com/valyala/fasthttp](github.com/valyala/fasthttp) (and possibly others) refers to something in Go.
- Commit: https://github.com/valyala/fasthttp/commit/15262ecf3c602364639d465daba1e7f3604d00e8

```
module: github.com/valyala/fasthttp
package: github.com/valyala/fasthttp
description: "The package github.com/valyala/fasthttp before 1.34.0 are vulnerable
    to Directory Traversal via the ServeFile function, due to improper sanitization.
    It is possible to be exploited by using a backslash %5c character in the path.\r\n\r\n**Note:**
    This security issue impacts Windows users only.\n\n"
cves:
  - CVE-2022-21221
credit: egovorukhin
links:
    commit: https://github.com/valyala/fasthttp/commit/15262ecf3c602364639d465daba1e7f3604d00e8
    context:
      - https://github.com/valyala/fasthttp/issues/1226
      - https://github.com/valyala/fasthttp/releases/tag/v1.34.0
      - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMVALYALAFASTHTTP-2407866

```

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.
