### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containerd/containerd: GHSA-5j5w-g665-5m35

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#360]
In GitHub Security Advisory [GHSA-5j5w-g665-5m35](https://github.com/advisories/GHSA-5j5w-g665-5m35), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/containerd/containerd](https://pkg.go.dev/github.com/containerd/containerd) | 1.5.8 | >= 1.5.0, < 1.5.8 || [github.com/containerd/containerd](https://pkg.go.dev/github.com/containerd/containerd) | 1.4.12 | < 1.4.12 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/containerd/containerd
additional_packages:
  - package: github.com/containerd/containerd
    versions:
      - introduced: v0.0.0
        fixed: v1.4.12
versions:
  - introduced: v1.5.0
    fixed: v1.5.8
description: |-
    ### Impact

    In the OCI Distribution Specification version 1.0.0 and prior and in the OCI Image Specification version 1.0.1 and prior, manifest and index documents are ambiguous without an accompanying Content-Type HTTP header.  Versions of containerd prior to 1.4.12 and 1.5.8 treat the Content-Type header as trusted and deserialize the document according to that header.  If the Content-Type header changed between pulls of the same ambiguous document (with the same digest), the document may be interpreted differently, meaning that the digest alone is insufficient to unambiguously identify the content of the image.

    ### Patches

    This issue has been fixed in containerd 1.4.12 and 1.5.8.  Image pulls for manifests that contain a “manifests” field or indices which contain a “layers” field are rejected.

    ### Workarounds

    Ensure you only pull images from trusted sources.

    ### References

    https://github.com/opencontainers/distribution-spec/security/advisories/GHSA-mc8v-mgrf-8f4m
    https://github.com/opencontainers/image-spec/security/advisories/GHSA-77vh-xpmg-72qh

    ### For more information
    If you have any questions or comments about this advisory:
    * Open an issue in [containerd](https://github.com/containerd/containerd/issues/new/choose)
    * Email us at [security@containerd.io](mailto:security@containerd.io)
published: 2021-11-18T16:08:58Z
last_modified: 2021-11-18T16:08:58Z
ghsas:
  - GHSA-5j5w-g665-5m35

```
