### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/google/fscrypt: GHSA-w4f8-fxq2-j35v

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#364]
In GitHub Security Advisory [GHSA-w4f8-fxq2-j35v](https://github.com/advisories/GHSA-w4f8-fxq2-j35v), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/google/fscrypt](https://pkg.go.dev/github.com/google/fscrypt) | 0.3.3 | < 0.3.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/google/fscrypt
versions:
  - introduced: v0.0.0
    fixed: v0.3.3
description: |-
    The bash completion script for `fscrypt` through v0.3.2 allows injection of commands via crafted mountpoint paths, allowing privilege escalation under a specific set of circumstances. A local user who has control over mountpoint paths could potentially escalate their privileges if they create a malicious mountpoint path and if the system administrator happens to be using the `fscrypt` bash completion script to complete mountpoint paths. We recommend upgrading to v0.3.3 or above.

    For more details, see [CVE-2022-25328](https://www.cve.org/CVERecord?id=CVE-2022-25328).
published: 2022-03-01T21:04:57Z
last_modified: 2022-03-01T22:16:48Z
ghsas:
  - GHSA-w4f8-fxq2-j35v

```
