### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/google/fscrypt: GHSA-chxf-fjcf-7fwp

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#366]
In GitHub Security Advisory [GHSA-chxf-fjcf-7fwp](https://github.com/advisories/GHSA-chxf-fjcf-7fwp), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/google/fscrypt](https://pkg.go.dev/github.com/google/fscrypt) | 0.3.3 | < 0.3.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/google/fscrypt
versions:
  - introduced: v0.0.0
    fixed: v0.3.3
description: |
    `fscrypt` through v0.3.2 creates a world-writable directory by default when setting up a filesystem, allowing unprivileged users to exhaust filesystem space. We recommend upgrading to `fscrypt` v0.3.3 or above and adjusting the permissions on existing `fscrypt` metadata directories where applicable.

    For more details, see [CVE-2022-25326](https://www.cve.org/CVERecord?id=CVE-2022-25326) and https://github.com/google/fscrypt#setting-up-fscrypt-on-a-filesystem.
published: 2022-03-01T21:04:07Z
last_modified: 2022-03-01T22:16:21Z
ghsas:
  - GHSA-chxf-fjcf-7fwp

```
