### ISSUE TITLE
x/vulndb: potential Go vuln in mellium.im/xmpp/websocket: GHSA-h289-x5wc-xcv8

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#370]
In GitHub Security Advisory [GHSA-h289-x5wc-xcv8](https://github.com/advisories/GHSA-h289-x5wc-xcv8), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [mellium.im/xmpp/websocket](https://pkg.go.dev/mellium.im/xmpp/websocket) | 0.21.1 | < 0.21.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: mellium.im/xmpp/websocket
versions:
  - introduced: v0.0.0
    fixed: v0.21.1
description: |
    ### Impact

    If no TLS configuration is provided by the user, the websocket package constructs its own TLS configuration using recommended defaults. When looking up a WSS endpoint using the DNS TXT record method described in [XEP-0156: Discovering Alternative XMPP Connection Methods](https://xmpp.org/extensions/xep-0156.html) the ServerName field was incorrectly being set to the name of the server returned by the TXT record request, not the name of the initial server we were attempting to connect to. This means that any attacker that can spoof a DNS record (ie. in the absence of DNSSEC, DNS-over-TLS, DNS-over-HTTPS, or similar technologies) could redirect the user to a server of their choosing and as long as it had a valid TLS certificate for itself the connection would succeed, resulting in a MITM situation.

    ### Patches

    All users should upgrade to v0.21.1.

    ### Workarounds

    To work around the issue, manually specify a TLS configuration with the correct hostname.

    ### References

    - https://mellium.im/cve/cve-2022-24968/
    - https://nvd.nist.gov/vuln/detail/CVE-2022-24968

    ### For more information

    If you have any questions or comments about this advisory:
    * Reach out on XMPP to [sam@samwhited.com](xmpp:sam@samwhited.com?msg)
    * Email us at [sam@samwhited.com](mailto:sam@samwhited.com)
published: 2022-02-16T22:56:21Z
last_modified: 2022-02-17T14:16:34Z
ghsas:
  - GHSA-h289-x5wc-xcv8

```
