### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/traefik/traefik: GHSA-vrch-868g-9jx5

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#3719]
Advisory [GHSA-vrch-868g-9jx5](https://github.com/advisories/GHSA-vrch-868g-9jx5) references a vulnerability in the following Go modules:

| Module |
| - |
| [github.com/traefik/traefik](https://pkg.go.dev/github.com/traefik/traefik) |

Description:
## Impact

There is a potential vulnerability in Traefik managing the requests using a `PathPrefix`, `Path` or `PathRegex` matcher.

When Traefik is configured to route the requests to a backend using a matcher based on the path, if the URL contains a URL encoded string in its path, it’s possible to target a backend, exposed using another router, by-passing the middlewares chain.

## Example

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: my-service
spec:
  routes:
    - match: PathPrefix(‘/service’)
      kind: Rule
      services:
        - name: service-a...

References:
- ADVISORY: https://github.com/advisories/GHSA-vrch-868g-9jx5
- ADVISORY: https://github.com/traefik/traefik/security/advisories/GHSA-vrch-868g-9jx5
- FIX: https://github.com/traefik/traefik/commit/08d5dfee0164aa54dd44a467870042e18e8d3f00
- WEB: https://github.com/traefik/traefik/releases/tag/v2.11.25
- WEB: https://github.com/traefik/traefik/releases/tag/v3.4.1

Cross references:
- github.com/traefik/traefik appears in 22 other report(s):
  - data/excluded/GO-2023-2117.yaml    (https://github.com/golang/vulndb/issues/2117)    DEPENDENT_VULNERABILITY
  - data/reports/GO-2022-0325.yaml    (https://github.com/golang/vulndb/issues/325)
  - data/reports/GO-2022-0808.yaml    (https://github.com/golang/vulndb/issues/808)
  - data/reports/GO-2022-0923.yaml    (https://github.com/golang/vulndb/issues/923)
  - data/reports/GO-2022-1152.yaml    (https://github.com/golang/vulndb/issues/1152)
  - data/reports/GO-2022-1154.yaml    (https://github.com/golang/vulndb/issues/1154)
  - data/reports/GO-2023-1919.yaml    (https://github.com/golang/vulndb/issues/1919)
  - data/reports/GO-2023-1950.yaml    (https://github.com/golang/vulndb/issues/1950)
  - data/reports/GO-2023-2376.yaml    (https://github.com/golang/vulndb/issues/2376)
  - data/reports/GO-2023-2377.yaml    (https://github.com/golang/vulndb/issues/2377)
  - data/reports/GO-2023-2381.yaml    (https://github.com/golang/vulndb/issues/2381)
  - data/reports/GO-2024-2722.yaml    (https://github.com/golang/vulndb/issues/2722)
  - data/reports/GO-2024-2726.yaml    (https://github.com/golang/vulndb/issues/2726)
  - data/reports/GO-2024-2880.yaml    (https://github.com/golang/vulndb/issues/2880)
  - data/reports/GO-2024-2917.yaml    (https://github.com/golang/vulndb/issues/2917)
  - data/reports/GO-2024-2941.yaml    (https://github.com/golang/vulndb/issues/2941)
  - data/reports/GO-2024-2973.yaml    (https://github.com/golang/vulndb/issues/2973)
  - data/reports/GO-2024-3135.yaml    (https://github.com/golang/vulndb/issues/3135)
  - data/reports/GO-2024-3299.yaml    (https://github.com/golang/vulndb/issues/3299)
  - data/reports/GO-2024-3342.yaml    (https://github.com/golang/vulndb/issues/3342)
  - data/reports/GO-2025-3627.yaml    (https://github.com/golang/vulndb/issues/3627)
  - data/reports/GO-2025-3634.yaml    (https://github.com/golang/vulndb/issues/3634)

See [doc/quickstart.md](https://github.com/golang/vulndb/blob/master/doc/quickstart.md) for instructions on how to triage this report.

```
id: GO-ID-PENDING
modules:
    - module: github.com/traefik/traefik
      non_go_versions:
        - introduced: TODO (earliest fixed "2.11.25", vuln range "<= 2.11.24")
        - introduced: TODO (earliest fixed "3.4.1", vuln range "<= 3.4.0")
      vulnerable_at: 1.7.34
summary: Traefik allows path traversal using url encoding in github.com/traefik/traefik
cves:
    - CVE-2025-47952
ghsas:
    - GHSA-vrch-868g-9jx5
references:
    - advisory: https://github.com/advisories/GHSA-vrch-868g-9jx5
    - advisory: https://github.com/traefik/traefik/security/advisories/GHSA-vrch-868g-9jx5
    - fix: https://github.com/traefik/traefik/commit/08d5dfee0164aa54dd44a467870042e18e8d3f00
    - web: https://github.com/traefik/traefik/releases/tag/v2.11.25
    - web: https://github.com/traefik/traefik/releases/tag/v3.4.1
source:
    id: GHSA-vrch-868g-9jx5
    created: 2025-05-28T15:01:37.501954659Z
review_status: UNREVIEWED

```
