### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/projectdiscovery/interactsh: GHSA-m36x-mgfh-8g78

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#372]
In GitHub Security Advisory [GHSA-m36x-mgfh-8g78](https://github.com/advisories/GHSA-m36x-mgfh-8g78), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/projectdiscovery/interactsh](https://pkg.go.dev/github.com/projectdiscovery/interactsh) | 1.0.0 | < 1.0.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/projectdiscovery/interactsh
versions:
  - introduced: v0.0.0
    fixed: v1.0.0
description: |
    A domain configured with interactsh server was vulnerable to subdomain takeover for specfic subdomain, i.e `app`, Interactsh server before `< 1.0.0` used to create cname entries for `app` pointing to `projectdiscovery.github.io` as default which intended to used for hosting interactsh [web client](https://github.com/projectdiscovery/interactsh-web) using GitHub pages. It turns out to be a security issue with a self-hosted interactsh server in which the user may not have configured a web client but still have a cname entry pointing to GitHub pages, making them vulnerable to subdomain takeover.

    This issue was initially reported to us as a subdomain takeover for one of our domains that runs interactsh server by **Melih** at `security@projectdiscovery.io`, and after conducting an internal investigation, we determined that it was an issue with the default config of interactsh server affecting all the server running self-hosted instance of interactsh, as a result - cname entry has been removed in the latest release.

    #### Impact
    This allows one to host / run arbitrary client side code (XSS) in a user's browser when browsing the vulnerable subdomain, for more details on the impact, please read this [detailed blogpost](https://labs.detectify.com/2014/10/21/hostile-subdomain-takeover-using-herokugithubdesk-more/) from Detectify.
    #### Patches
    Update to [Interactsh server v1.0.0 ](https://github.com/projectdiscovery/interactsh/releases/tag/v1.0.0)with `go install -v github.com/projectdiscovery/interactsh/cmd/interactsh-server@latest`

    #### References
    https://github.com/projectdiscovery/interactsh/issues/136

    #### For more information
    If you have any questions or comments about this advisory:
    * Email us at [security@projectdiscovery.io](mailto:security@projectdiscovery.io)
published: 2022-01-27T15:15:25Z
last_modified: 2022-01-27T15:15:25Z
ghsas:
  - GHSA-m36x-mgfh-8g78

```
