### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/foxcpp/maddy: GHSA-m6m5-pp4g-fcc8

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#374]
In GitHub Security Advisory [GHSA-m6m5-pp4g-fcc8](https://github.com/advisories/GHSA-m6m5-pp4g-fcc8), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/foxcpp/maddy](https://pkg.go.dev/github.com/foxcpp/maddy) | 0.5.1 | < 0.5.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/foxcpp/maddy
versions:
  - introduced: v0.0.0
    fixed: v0.5.1
description: |-
    ### Impact

    Anyone using storage.blob.s3 introduced in 0.5.0 with storage.imapsql.
    ```
    storage.imapsql local_mailboxes {
      ...
      msg_store s3 {
        ...
      }
    }
    ```

    ### Patches

    The relevant commit is pushed to master and will be included in the 0.5.1 release.

    No special handling of the issue has been done due to the small amount of affected users.

    ### Workarounds

    None.

    ### References

    * Original report: https://github.com/foxcpp/maddy/issues/395
    * Fix: https://github.com/foxcpp/maddy/commit/07c8495ee4394fabbf5aac4df8aebeafb2fb29d8
published: 2021-10-06T17:47:35Z
last_modified: 2021-10-06T17:47:35Z
ghsas:
  - GHSA-m6m5-pp4g-fcc8

```
