### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/google/fscrypt: GHSA-p93v-m2r2-4387

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#376]
In GitHub Security Advisory [GHSA-p93v-m2r2-4387](https://github.com/advisories/GHSA-p93v-m2r2-4387), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/google/fscrypt](https://pkg.go.dev/github.com/google/fscrypt) | 0.3.3 | < 0.3.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/google/fscrypt
versions:
  - introduced: v0.0.0
    fixed: v0.3.3
description: |-
    The PAM module for `fscrypt` through v0.3.2 doesn't adequately validate `fscrypt` metadata files, allowing users to create malicious metadata files that prevent other users from logging in. A local user can cause a denial of service by creating a `fscrypt` metadata file that prevents other users from logging into the system. We recommend upgrading to v0.3.3 or above.

    For more details, see [CVE-2022-25327](https://www.cve.org/CVERecord?id=CVE-2022-25327).
published: 2022-03-01T21:05:01Z
last_modified: 2022-03-01T22:16:33Z
ghsas:
  - GHSA-p93v-m2r2-4387

```
