### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/foxcpp/maddy: GHSA-qh54-9vc5-m9fg

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#378]
In GitHub Security Advisory [GHSA-qh54-9vc5-m9fg](https://github.com/advisories/GHSA-qh54-9vc5-m9fg), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/foxcpp/maddy](https://pkg.go.dev/github.com/foxcpp/maddy) | 0.5.2 | >= 0.5.0, < 0.5.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/foxcpp/maddy
versions:
  - introduced: v0.5.0
    fixed: v0.5.2
description: "### Impact\n\nThis vulnerability affects maddy 0.5.1, 0.5.0 users using
    auth.shadow module\nand an extremely outdated system that still allows MD5 hashes
    in \n/etc/shadows.\n\n### Patches\n\nPatch is available as part of the 0.5.2 release.\n\n###
    Workarounds\n\nEnsure MD5 hashes are not present in /etc/shadow.\n"
published: 2021-10-12T16:06:30Z
last_modified: 2021-10-12T16:06:30Z
ghsas:
  - GHSA-qh54-9vc5-m9fg

```
