### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/netlify/gotrue: GHSA-433w-mm6h-rv9p

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#382]
In GitHub Security Advisory [GHSA-433w-mm6h-rv9p](https://github.com/advisories/GHSA-433w-mm6h-rv9p), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/netlify/gotrue](https://pkg.go.dev/github.com/netlify/gotrue) | 1.0.0 | < 1.0.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/netlify/gotrue
versions:
  - introduced: v0.0.0
    fixed: v1.0.0
description: |-
    ### Impact

    The following vulnerabilities have been disclosed, which impact users leveraging the SAML auth provider:

    - [`goxmldsig` - Signature Validation Bypass](https://github.com/russellhaering/goxmldsig/security/advisories/GHSA-q547-gmf8-8jr7)
    - [`gosaml2` - Authentication Bypass](https://github.com/russellhaering/gosaml2/security/advisories/GHSA-xhqq-x44f-9fgg)

    ### Patches

    [Patch available](https://github.com/netlify/gotrue/pull/274)

    Please upgrade to v1.0.0 or commit hash `a2b4dd6bc4ef7562d1df044098b303f564eefa90`

    ### Workarounds

    No known workarounds.

    ### For more information
    If you have any questions or comments about this advisory:
    * Open an issue in [gotrue](https://github.com/netlify/gotrue/issues)
    * Email us at [security@netlify.com](mailto:security@netlify.com)
published: 2021-06-23T17:29:06Z
last_modified: 2021-06-23T17:29:06Z
ghsas:
  - GHSA-433w-mm6h-rv9p

```
