### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: GHSA-6w87-g839-9wv7

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#387]
In GitHub Security Advisory [GHSA-6w87-g839-9wv7](https://github.com/advisories/GHSA-6w87-g839-9wv7), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/argoproj/argo-cd](https://pkg.go.dev/github.com/argoproj/argo-cd) | 1.8.7 | >= 1.8.0, < 1.8.7 || [github.com/argoproj/argo-cd](https://pkg.go.dev/github.com/argoproj/argo-cd) | 1.7.14 | < 1.7.14 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
package: github.com/argoproj/argo-cd
additional_packages:
  - package: github.com/argoproj/argo-cd
    versions:
      - introduced: v0.0.0
        fixed: v1.7.14
versions:
  - introduced: v1.8.0
    fixed: v1.8.7
description: |-
    ### Impact

    When Argo CD was connected to a Helm OCI repository with authentication enabled, the credentials used for accessing the remote repository were logged.

    Anyone with access to the pod logs - either via access with appropriate permissions to the Kubernetes control plane or a third party log management system where the logs from Argo CD were aggregated - could have potentially obtained the credentials to the Helm OCI repository.

    If you are using Helm OCI repositories with Argo CD, it is strongly recommended to upgrade Argo CD to the latest patch version and to change the credentials used to access the repositories.

    ### Patches

    A patch for this vulnerability is available with the v1.8.7 and v1.7.14 releases of Argo CD.

    ### Workarounds

    No workaround available

    ### References

    N/A

    ### For more information

    If you have any questions or comments about this advisory:

    * Open an issue in [the Argo CD issue tracker](https://github.com/argoproj/argo-cd/issues) or [discussions](https://github.com/argoproj/argo-cd/discussions)
    * Join us on [Slack](https://argoproj.github.io/community/join-slack) in channel `#argo-cd`

    ### Credits

    This vulnerability was found and reported by a third-party who wishes to stay anonymous. We want to thank this third-party for disclosing this vulnerability to us in a responsible manner.
published: 2021-05-21T14:31:28Z
last_modified: 2021-10-05T16:35:57Z
ghsas:
  - GHSA-6w87-g839-9wv7

```
