### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/moby/moby: CVE-2022-24769

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#390]
CVE-2022-24769 references [github.com/moby/moby](https://github.com/moby/moby), which may be a Go module.

Description:
Moby is an open-source project created by Docker to enable and accelerate software containerization. A bug was found in Moby (Docker Engine) prior to version 20.10.14 where containers were incorrectly started with non-empty inheritable Linux process capabilities, creating an atypical Linux environment and enabling programs with inheritable file capabilities to elevate those capabilities to the permitted set during `execve(2)`. Normally, when executable programs have specified permitted file capabilities, otherwise unprivileged users and processes can execute those programs and gain the specified file capabilities up to the bounding set. Due to this bug, containers which included executable programs with inheritable file capabilities allowed otherwise unprivileged users and processes to additionally gain these inheritable file capabilities up to the container's bounding set. Containers which use Linux users and groups to perform privilege separation inside the container are most directly impacted. This bug did not affect the container security sandbox as the inheritable set never contained more capabilities than were included in the container's bounding set. This bug has been fixed in Moby (Docker Engine) 20.10.14. Running containers should be stopped, deleted, and recreated for the inheritable capabilities to be reset. This fix changes Moby (Docker Engine) behavior such that containers are started with a more typical Linux environment. As a workaround, the entry point of a container can be modified to use a utility like `capsh(1)` to drop inheritable capabilities prior to the primary process starting.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24769
- JSON: https://github.com/CVEProject/cvelist/tree/7ab209ca12561da42c010f58fd8f3ebc52e318d4/2022/24xxx/CVE-2022-24769.json
- Commit: https://github.com/moby/moby/commit/2bbc786e4c59761d722d2d1518cd0a32829bc07f
- https://github.com/moby/moby/releases/tag/v20.10.14
- https://github.com/moby/moby/security/advisories/GHSA-2mm7-x5h6-5pvq

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/moby/moby
package: moby
description: |
    Moby is an open-source project created by Docker to enable and accelerate software containerization. A bug was found in Moby (Docker Engine) prior to version 20.10.14 where containers were incorrectly started with non-empty inheritable Linux process capabilities, creating an atypical Linux environment and enabling programs with inheritable file capabilities to elevate those capabilities to the permitted set during `execve(2)`. Normally, when executable programs have specified permitted file capabilities, otherwise unprivileged users and processes can execute those programs and gain the specified file capabilities up to the bounding set. Due to this bug, containers which included executable programs with inheritable file capabilities allowed otherwise unprivileged users and processes to additionally gain these inheritable file capabilities up to the container's bounding set. Containers which use Linux users and groups to perform privilege separation inside the container are most directly impacted. This bug did not affect the container security sandbox as the inheritable set never contained more capabilities than were included in the container's bounding set. This bug has been fixed in Moby (Docker Engine) 20.10.14. Running containers should be stopped, deleted, and recreated for the inheritable capabilities to be reset. This fix changes Moby (Docker Engine) behavior such that containers are started with a more typical Linux environment. As a workaround, the entry point of a container can be modified to use a utility like `capsh(1)` to drop inheritable capabilities prior to the primary process starting.
cves:
  - CVE-2022-24769
links:
    commit: https://github.com/moby/moby/commit/2bbc786e4c59761d722d2d1518cd0a32829bc07f
    context:
      - https://github.com/moby/moby/releases/tag/v20.10.14
      - https://github.com/moby/moby/security/advisories/GHSA-2mm7-x5h6-5pvq

```
