### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containerd/imgcrypt: CVE-2022-24778

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#412]
CVE-2022-24778 references [github.com/containerd/imgcrypt](https://github.com/containerd/imgcrypt), which may be a Go module.

Description:
The imgcrypt library provides API exensions for containerd to support encrypted container images and implements the ctd-decoder command line tool for use by containerd to decrypt encrypted container images. The imgcrypt function `CheckAuthorization` is supposed to check whether the current used is authorized to access an encrypted image and prevent the user from running an image that another user previously decrypted on the same system. In versions prior to 1.1.4, a failure occurs when an image with a ManifestList is used and the architecture of the local host is not the first one in the ManifestList. Only the first architecture in the list was tested, which may not have its layers available locally since it could not be run on the host architecture. Therefore, the verdict on unavailable layers was that the image could be run anticipating that image run failure would occur later due to the layers not being available. However, this verdict to allow the image to run enabled other architectures in the ManifestList to run an image without providing keys if that image had previously been decrypted. A patch has been applied to imgcrypt 1.1.4. Workarounds may include usage of different namespaces for each remote user.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24778
- JSON: https://github.com/CVEProject/cvelist/tree/989626ac7e568c4df26ff6cda8e3962affbe3e8a/2022/24xxx/CVE-2022-24778.json
- Commit: https://github.com/containerd/imgcrypt/commit/6fdd9818a4d8142107b7ecd767d839c9707700d9
- https://github.com/containerd/imgcrypt/issues/69
- https://github.com/containerd/imgcrypt/releases/tag/v1.1.4
- https://github.com/containerd/imgcrypt/security/advisories/GHSA-8v99-48m9-c8pm

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/containerd/imgcrypt
package: imgcrypt
description: |
    The imgcrypt library provides API exensions for containerd to support encrypted container images and implements the ctd-decoder command line tool for use by containerd to decrypt encrypted container images. The imgcrypt function `CheckAuthorization` is supposed to check whether the current used is authorized to access an encrypted image and prevent the user from running an image that another user previously decrypted on the same system. In versions prior to 1.1.4, a failure occurs when an image with a ManifestList is used and the architecture of the local host is not the first one in the ManifestList. Only the first architecture in the list was tested, which may not have its layers available locally since it could not be run on the host architecture. Therefore, the verdict on unavailable layers was that the image could be run anticipating that image run failure would occur later due to the layers not being available. However, this verdict to allow the image to run enabled other architectures in the ManifestList to run an image without providing keys if that image had previously been decrypted. A patch has been applied to imgcrypt 1.1.4. Workarounds may include usage of different namespaces for each remote user.
cves:
  - CVE-2022-24778
links:
    commit: https://github.com/containerd/imgcrypt/commit/6fdd9818a4d8142107b7ecd767d839c9707700d9
    context:
      - https://github.com/containerd/imgcrypt/issues/69
      - https://github.com/containerd/imgcrypt/releases/tag/v1.1.4
      - https://github.com/containerd/imgcrypt/security/advisories/GHSA-8v99-48m9-c8pm

```
