### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pomerium/pomerium: CVE-2022-24797

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#413]
CVE-2022-24797 references [github.com/pomerium/pomerium](https://github.com/pomerium/pomerium), which may be a Go module.

Description:
Pomerium is an identity-aware access proxy. In distributed service mode, Pomerium's Authenticate service exposes pprof debug and prometheus metrics handlers to untrusted traffic.  This can leak potentially sensitive environmental information or lead to limited denial of service conditions. This issue is patched in version v0.17.1 Workarounds: Block access to `/debug` and `/metrics` paths on the authenticate service.  This can be done with any L7 proxy, including Pomerium's own proxy service.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24797
- JSON: https://github.com/CVEProject/cvelist/tree/2703f5d11e8d904e061b358a511c26064246ed5a/2022/24xxx/CVE-2022-24797.json
- Commit: https://github.com/pomerium/pomerium/commit/b435f73e2b54088da2aca5e8c3aa1808293d6903
- PR: https://github.com/pomerium/pomerium/pull/3212
- https://github.com/pomerium/pomerium/security/advisories/GHSA-q98f-2x4p-prjr

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/pomerium/pomerium
package: pomerium
description: |
    Pomerium is an identity-aware access proxy. In distributed service mode, Pomerium's Authenticate service exposes pprof debug and prometheus metrics handlers to untrusted traffic.  This can leak potentially sensitive environmental information or lead to limited denial of service conditions. This issue is patched in version v0.17.1 Workarounds: Block access to `/debug` and `/metrics` paths on the authenticate service.  This can be done with any L7 proxy, including Pomerium's own proxy service.
cves:
  - CVE-2022-24797
links:
    pr: https://github.com/pomerium/pomerium/pull/3212
    commit: https://github.com/pomerium/pomerium/commit/b435f73e2b54088da2aca5e8c3aa1808293d6903
    context:
      - https://github.com/pomerium/pomerium/security/advisories/GHSA-q98f-2x4p-prjr

```
