### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containers/podman: CVE-2022-27649

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#416]
CVE-2022-27649 references [github.com/containers/podman](https://github.com/containers/podman), which may be a Go module.

Description:
A flaw was found in Podman, where containers were started incorrectly with non-empty default permissions. A vulnerability was found in Moby (Docker Engine), where containers were started incorrectly with non-empty inheritable Linux process capabilities. This flaw allows an attacker with access to programs with inheritable file capabilities to elevate those capabilities to the permitted set when execve(2) runs.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-27649
- JSON: https://github.com/CVEProject/cvelist/tree/ad1f76deaf3f6b7414fd20390506b5da3fd88cb3/2022/27xxx/CVE-2022-27649.json
- Commit: https://github.com/containers/podman/commit/aafa80918a245edcbdaceb1191d749570f1872d0
- https://bugzilla.redhat.com/show_bug.cgi?id=2066568
- https://github.com/containers/podman/security/advisories/GHSA-qvf8-p83w-v58j

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/containers/podman
package: podman
description: |
    A flaw was found in Podman, where containers were started incorrectly with non-empty default permissions. A vulnerability was found in Moby (Docker Engine), where containers were started incorrectly with non-empty inheritable Linux process capabilities. This flaw allows an attacker with access to programs with inheritable file capabilities to elevate those capabilities to the permitted set when execve(2) runs.
cves:
  - CVE-2022-27649
links:
    commit: https://github.com/containers/podman/commit/aafa80918a245edcbdaceb1191d749570f1872d0
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=2066568
      - https://github.com/containers/podman/security/advisories/GHSA-qvf8-p83w-v58j

```
