### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containers/buildah: CVE-2022-27651

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#417]
CVE-2022-27651 references [github.com/containers/buildah](https://github.com/containers/buildah), which may be a Go module.

Description:
A flaw was found in buildah where containers were incorrectly started with non-empty default permissions. A bug was found in Moby (Docker Engine) where containers were incorrectly started with non-empty inheritable Linux process capabilities, enabling an attacker with access to programs with inheritable file capabilities to elevate those capabilities to the permitted set when execve(2) runs. This has the potential to impact confidentiality and integrity.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-27651
- JSON: https://github.com/CVEProject/cvelist/tree/ad1f76deaf3f6b7414fd20390506b5da3fd88cb3/2022/27xxx/CVE-2022-27651.json
- Commit: https://github.com/containers/buildah/commit/e7e55c988c05dd74005184ceb64f097a0cfe645b
- https://bugzilla.redhat.com/show_bug.cgi?id=2066840
- https://github.com/containers/buildah/security/advisories/GHSA-c3g4-w6cv-6v7h

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/containers/buildah
package: buildah
description: |
    A flaw was found in buildah where containers were incorrectly started with non-empty default permissions. A bug was found in Moby (Docker Engine) where containers were incorrectly started with non-empty inheritable Linux process capabilities, enabling an attacker with access to programs with inheritable file capabilities to elevate those capabilities to the permitted set when execve(2) runs. This has the potential to impact confidentiality and integrity.
cves:
  - CVE-2022-27651
links:
    commit: https://github.com/containers/buildah/commit/e7e55c988c05dd74005184ceb64f097a0cfe645b
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=2066840
      - https://github.com/containers/buildah/security/advisories/GHSA-c3g4-w6cv-6v7h

```
