### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/swaggo/http-swagger: CVE-2022-24863

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#427]
CVE-2022-24863 references [github.com/swaggo/http-swagger](https://github.com/swaggo/http-swagger), which may be a Go module.

Description:
http-swagger is an open source wrapper to automatically generate RESTful API documentation with Swagger 2.0. In versions of http-swagger prior to 1.2.6 an attacker may perform a denial of service attack consisting of memory exhaustion on the host system. The cause of the memory exhaustion is down to improper handling of http methods. Users are advised to upgrade.  Users unable to upgrade may to restrict the path prefix to the "GET" method as a workaround.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24863
- JSON: https://github.com/CVEProject/cvelist/tree/d855890b7ea7f5cef27af49e2e13bc246faecb39/2022/24xxx/CVE-2022-24863.json
- Commit: https://github.com/swaggo/http-swagger/commit/b7d83e8fba85a7a51aa7e45e8244b4173f15049e
- PR: https://github.com/swaggo/http-swagger/pull/62
- https://github.com/swaggo/http-swagger/releases/tag/v1.2.6
- https://github.com/swaggo/http-swagger/security/advisories/GHSA-xg75-q3q5-cqmv

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/swaggo/http-swagger
package: http-swagger
description: |+
    http-swagger is an open source wrapper to automatically generate RESTful API documentation with Swagger 2.0. In versions of http-swagger prior to 1.2.6 an attacker may perform a denial of service attack consisting of memory exhaustion on the host system. The cause of the memory exhaustion is down to improper handling of http methods. Users are advised to upgrade.  Users unable to upgrade may to restrict the path prefix to the "GET" method as a workaround.

cves:
  - CVE-2022-24863
links:
    pr: https://github.com/swaggo/http-swagger/pull/62
    commit: https://github.com/swaggo/http-swagger/commit/b7d83e8fba85a7a51aa7e45e8244b4173f15049e
    context:
      - https://github.com/swaggo/http-swagger/releases/tag/v1.2.6
      - https://github.com/swaggo/http-swagger/security/advisories/GHSA-xg75-q3q5-cqmv

```
