### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/fleetdm/fleet: CVE-2022-24841

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#428]
CVE-2022-24841 references [github.com/fleetdm/fleet](https://github.com/fleetdm/fleet), which may be a Go module.

Description:
fleetdm/fleet is an open source device management, built on osquery. All versions of fleet making use of the teams feature are affected by this authorization bypass issue. Fleet instances without teams, or with teams but without restricted team accounts are not affected. In affected versions a team admin can erroneously add themselves as admin, maintainer or observer on other teams. Users are advised to upgrade to version 4.13. There are no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24841
- JSON: https://github.com/CVEProject/cvelist/tree/3ffeb08ff61b77a88aaa951cea07c6f334bc36a2/2022/24xxx/CVE-2022-24841.json
- Commit: https://github.com/fleetdm/fleet/commit/da171d3b8d149c30b8307723cbe6b6e8847cb30c
- https://github.com/fleetdm/fleet/security/advisories/GHSA-pr2g-j78h-84cr

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/fleetdm/fleet
package: fleet
description: |+
    fleetdm/fleet is an open source device management, built on osquery. All versions of fleet making use of the teams feature are affected by this authorization bypass issue. Fleet instances without teams, or with teams but without restricted team accounts are not affected. In affected versions a team admin can erroneously add themselves as admin, maintainer or observer on other teams. Users are advised to upgrade to version 4.13. There are no known workarounds for this issue.

cves:
  - CVE-2022-24841
links:
    commit: https://github.com/fleetdm/fleet/commit/da171d3b8d149c30b8307723cbe6b6e8847cb30c
    context:
      - https://github.com/fleetdm/fleet/security/advisories/GHSA-pr2g-j78h-84cr

```
