### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/aws/amazon-ssm-agent: CVE-2022-29527

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#436]
CVE-2022-29527 references [github.com/aws/amazon-ssm-agent](https://github.com/aws/amazon-ssm-agent), which may be a Go module.

Description:
Amazon AWS amazon-ssm-agent before 3.1.1208.0 creates a world-writable sudoers file, which allows local attackers to inject Sudo rules and escalate privileges to root. This occurs in certain situations involving a race condition.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29527
- JSON: https://github.com/CVEProject/cvelist/tree/0d7091658eb8eba29f9e46a999cb77d95a9ad075/2022/29xxx/CVE-2022-29527.json
- Commit: https://github.com/aws/amazon-ssm-agent/commit/0fe8ae99b2ff25649c7b86d3bc05fc037400aca7
- https://bugzilla.suse.com/show_bug.cgi?id=1196556
- https://github.com/aws/amazon-ssm-agent/releases/tag/3.1.1208.0

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/aws/amazon-ssm-agent
package: n/a
description: |
    Amazon AWS amazon-ssm-agent before 3.1.1208.0 creates a world-writable sudoers file, which allows local attackers to inject Sudo rules and escalate privileges to root. This occurs in certain situations involving a race condition.
cves:
  - CVE-2022-29527
links:
    commit: https://github.com/aws/amazon-ssm-agent/commit/0fe8ae99b2ff25649c7b86d3bc05fc037400aca7
    context:
      - https://bugzilla.suse.com/show_bug.cgi?id=1196556
      - https://github.com/aws/amazon-ssm-agent/releases/tag/3.1.1208.0

```
