### ISSUE TITLE
x/vulndb: potential Go vuln in Path is unknown: CVE-2022-25850

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#441]
CVE-2022-25850 references [Path is unknown](https://Path is unknown), which may be a Go module.

Description:
The package github.com/hoppscotch/proxyscotch before 1.0.0 are vulnerable to Server-side Request Forgery (SSRF) when interceptor mode is set to proxy. It occurs when an HTTP request is made by a backend server to an untrusted URL submitted by a user. It leads to a leakage of sensitive information from the server.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-25850
- JSON: https://github.com/CVEProject/cvelist/tree/c8932539ca4e8dfa41db04a60646523e454ea30c/2022/25xxx/CVE-2022-25850.json
- Commit: https://github.com/hoppscotch/proxyscotch/commit/de67380f62f907f201d75854b76024ba4885fab7
- https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHOPPSCOTCHPROXYSCOTCH-2435228

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: std
package: Path is unknown
description: |+
    The package github.com/hoppscotch/proxyscotch before 1.0.0 are vulnerable to Server-side Request Forgery (SSRF) when interceptor mode is set to proxy. It occurs when an HTTP request is made by a backend server to an untrusted URL submitted by a user. It leads to a leakage of sensitive information from the server.

cves:
  - CVE-2022-25850
credit: Yadhu Krishna M
links:
    commit: https://github.com/hoppscotch/proxyscotch/commit/de67380f62f907f201d75854b76024ba4885fab7
    context:
      - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMHOPPSCOTCHPROXYSCOTCH-2435228

```
