### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-workflows: CVE-2022-29164

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#445]
CVE-2022-29164 references [github.com/argoproj/argo-workflows](https://github.com/argoproj/argo-workflows), which may be a Go module.

Description:
Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. In affected versions an attacker can create a workflow which produces a HTML artifact containing an HTML file that contains a script which uses XHR calls to interact with the Argo Server API. The attacker emails the deep-link to the artifact to their victim. The victim opens the link, the script starts running. As the script has access to the Argo Server API (as the victim), so may read information about the victim’s workflows, or create and delete workflows. Note the attacker must be an insider: they must have access to the same cluster as the victim and must already be able to run their own workflows. The attacker must have an understanding of the victim’s system. We have seen no evidence of this in the wild. We urge all users to upgrade to the fixed versions.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29164
- JSON: https://github.com/CVEProject/cvelist/tree/583577f6fdfd79ec634650d7f08c2cccadde2714/2022/29xxx/CVE-2022-29164.json
- Commit: https://github.com/argoproj/argo-workflows/commit/87470e1c2bf703a9110e97bb755614ce8757fdcc
- PR: https://github.com/argoproj/argo-workflows/pull/8585
- https://github.com/argoproj/argo-workflows/security/advisories/GHSA-cmv8-6362-r5w9

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/argoproj/argo-workflows
package: argo-workflows
description: |+
    Argo Workflows is an open source container-native workflow engine for orchestrating parallel jobs on Kubernetes. In affected versions an attacker can create a workflow which produces a HTML artifact containing an HTML file that contains a script which uses XHR calls to interact with the Argo Server API. The attacker emails the deep-link to the artifact to their victim. The victim opens the link, the script starts running. As the script has access to the Argo Server API (as the victim), so may read information about the victim’s workflows, or create and delete workflows. Note the attacker must be an insider: they must have access to the same cluster as the victim and must already be able to run their own workflows. The attacker must have an understanding of the victim’s system. We have seen no evidence of this in the wild. We urge all users to upgrade to the fixed versions.

cves:
  - CVE-2022-29164
links:
    pr: https://github.com/argoproj/argo-workflows/pull/8585
    commit: https://github.com/argoproj/argo-workflows/commit/87470e1c2bf703a9110e97bb755614ce8757fdcc
    context:
      - https://github.com/argoproj/argo-workflows/security/advisories/GHSA-cmv8-6362-r5w9

```
