### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/charmbracelet/charm: CVE-2022-29180

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#449]
CVE-2022-29180 references [github.com/charmbracelet/charm](https://github.com/charmbracelet/charm), which may be a Go module.

Description:
A vulnerability in which attackers could forge HTTP requests to manipulate the `charm` data directory to access or delete anything on the server. This has been patched and is available in release [v0.12.1](https://github.com/charmbracelet/charm/releases/tag/v0.12.1). We recommend that all users running self-hosted `charm` instances update immediately. This vulnerability was found in-house and we haven't been notified of any potential exploiters.

### Additional notes

* Encrypted user data uploaded to the Charm server is safe as Charm servers cannot decrypt user data. This includes filenames, paths, and all key-value data.
* Users running the official Charm [Docker images](https://github.com/charmbracelet/charm/blob/main/docker.md) are at minimal risk because the exploit is limited to the containerized filesystem.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29180
- JSON: https://github.com/CVEProject/cvelist/tree/0cdda1381eaf9a653f7c3e88d2a872f6c9e9ae47/2022/29xxx/CVE-2022-29180.json
- Commit: https://github.com/charmbracelet/charm/commit/3c90668f955c7ce5ef721e4fc9faee7053232fd3
- https://github.com/charmbracelet/charm/security/advisories/GHSA-4wpp-w5r4-7v5v

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/charmbracelet/charm
package: charm
description: |
    A vulnerability in which attackers could forge HTTP requests to manipulate the `charm` data directory to access or delete anything on the server. This has been patched and is available in release [v0.12.1](https://github.com/charmbracelet/charm/releases/tag/v0.12.1). We recommend that all users running self-hosted `charm` instances update immediately. This vulnerability was found in-house and we haven't been notified of any potential exploiters.

    ### Additional notes

    * Encrypted user data uploaded to the Charm server is safe as Charm servers cannot decrypt user data. This includes filenames, paths, and all key-value data.
    * Users running the official Charm [Docker images](https://github.com/charmbracelet/charm/blob/main/docker.md) are at minimal risk because the exploit is limited to the containerized filesystem.
cves:
  - CVE-2022-29180
links:
    commit: https://github.com/charmbracelet/charm/commit/3c90668f955c7ce5ef721e4fc9faee7053232fd3
    context:
      - https://github.com/charmbracelet/charm/security/advisories/GHSA-4wpp-w5r4-7v5v

```
