### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/coreos/ignition: CVE-2022-1706

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#451]
CVE-2022-1706 references [github.com/coreos/ignition](https://github.com/coreos/ignition), which may be a Go module.

Description:
A vulnerability was found in Ignition where ignition configs are accessible from unprivileged containers in VMs running on VMware products. This issue is only relevant in user environments where the Ignition config contains secrets. The highest threat from this vulnerability is to data confidentiality. Possible workaround is to not put secrets in the Ignition config.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-1706
- JSON: https://github.com/CVEProject/cvelist/tree/b53f4181d2d4a7d13c6d2830c3466cc65d20fa7b/2022/1xxx/CVE-2022-1706.json
- Commit: https://github.com/coreos/ignition/commit/4b70b44b430ecf8377a276e89b5acd3a6957d4ea
- PR: https://github.com/coreos/ignition/pull/1350
- https://bugzilla.redhat.com/show_bug.cgi?id=2082274
- https://github.com/coreos/ignition/issues/1300
- https://github.com/coreos/ignition/issues/1315

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/coreos/ignition
package: coreos/ignition
description: |
    A vulnerability was found in Ignition where ignition configs are accessible from unprivileged containers in VMs running on VMware products. This issue is only relevant in user environments where the Ignition config contains secrets. The highest threat from this vulnerability is to data confidentiality. Possible workaround is to not put secrets in the Ignition config.
cves:
  - CVE-2022-1706
links:
    pr: https://github.com/coreos/ignition/pull/1350
    commit: https://github.com/coreos/ignition/commit/4b70b44b430ecf8377a276e89b5acd3a6957d4ea
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=2082274
      - https://github.com/coreos/ignition/issues/1300
      - https://github.com/coreos/ignition/issues/1315

```
