### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/opencontainers/runc: CVE-2022-29162

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#452]
CVE-2022-29162 references [github.com/opencontainers/runc](https://github.com/opencontainers/runc), which may be a Go module.

Description:
runc is a CLI tool for spawning and running containers on Linux according to the OCI specification. A bug was found in runc prior to version 1.1.2 where `runc exec --cap` created processes with non-empty inheritable Linux process capabilities, creating an atypical Linux environment and enabling programs with inheritable file capabilities to elevate those capabilities to the permitted set during execve(2). This bug did not affect the container security sandbox as the inheritable set never contained more capabilities than were included in the container's bounding set. This bug has been fixed in runc 1.1.2. This fix changes `runc exec --cap` behavior such that the additional capabilities granted to the process being executed (as specified via `--cap` arguments) do not include inheritable capabilities. In addition, `runc spec` is changed to not set any inheritable capabilities in the created example OCI spec (`config.json`) file.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29162
- JSON: https://github.com/CVEProject/cvelist/tree/27f7990596cee34523668ba79a04dfb35a34f75f/2022/29xxx/CVE-2022-29162.json
- Commit: https://github.com/opencontainers/runc/commit/d04de3a9b72d7a2455c1885fc75eb36d02cd17b5
- https://github.com/opencontainers/runc/releases/tag/v1.1.2
- https://github.com/opencontainers/runc/security/advisories/GHSA-f3fp-gc8g-vw66

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/opencontainers/runc
package: runc
description: |
    runc is a CLI tool for spawning and running containers on Linux according to the OCI specification. A bug was found in runc prior to version 1.1.2 where `runc exec --cap` created processes with non-empty inheritable Linux process capabilities, creating an atypical Linux environment and enabling programs with inheritable file capabilities to elevate those capabilities to the permitted set during execve(2). This bug did not affect the container security sandbox as the inheritable set never contained more capabilities than were included in the container's bounding set. This bug has been fixed in runc 1.1.2. This fix changes `runc exec --cap` behavior such that the additional capabilities granted to the process being executed (as specified via `--cap` arguments) do not include inheritable capabilities. In addition, `runc spec` is changed to not set any inheritable capabilities in the created example OCI spec (`config.json`) file.
cves:
  - CVE-2022-29162
links:
    commit: https://github.com/opencontainers/runc/commit/d04de3a9b72d7a2455c1885fc75eb36d02cd17b5
    context:
      - https://github.com/opencontainers/runc/releases/tag/v1.1.2
      - https://github.com/opencontainers/runc/security/advisories/GHSA-f3fp-gc8g-vw66

```
