### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/stripe/smokescreen: CVE-2022-29188

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#459]
CVE-2022-29188 references [github.com/stripe/smokescreen](https://github.com/stripe/smokescreen), which may be a Go module.

Description:
Smokescreen is an HTTP proxy. The primary use case for Smokescreen is to prevent server-side request forgery (SSRF) attacks in which external attackers leverage the behavior of applications to connect to or scan internal infrastructure. Smokescreen also offers an option to deny access to additional (e.g., external) URLs by way of a deny list. There was an issue in Smokescreen that made it possible to bypass the deny list feature by surrounding the hostname with square brackets (e.g. `[example.com]`). This only impacted the HTTP proxy functionality of Smokescreen. HTTPS requests were not impacted. Smokescreen version 0.0.4 contains a patch for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29188
- JSON: https://github.com/CVEProject/cvelist/tree/c9ff73eb484748bc1f36210053e5d7ce7410f59e/2022/29xxx/CVE-2022-29188.json
- Commit: https://github.com/stripe/smokescreen/commit/dea7b3c89df000f4072ff9866d61d78e30df6a36
- https://github.com/stripe/smokescreen/security/advisories/GHSA-qwrf-gfpj-qvj6

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/stripe/smokescreen
package: smokescreen
description: |
    Smokescreen is an HTTP proxy. The primary use case for Smokescreen is to prevent server-side request forgery (SSRF) attacks in which external attackers leverage the behavior of applications to connect to or scan internal infrastructure. Smokescreen also offers an option to deny access to additional (e.g., external) URLs by way of a deny list. There was an issue in Smokescreen that made it possible to bypass the deny list feature by surrounding the hostname with square brackets (e.g. `[example.com]`). This only impacted the HTTP proxy functionality of Smokescreen. HTTPS requests were not impacted. Smokescreen version 0.0.4 contains a patch for this issue.
cves:
  - CVE-2022-29188
links:
    commit: https://github.com/stripe/smokescreen/commit/dea7b3c89df000f4072ff9866d61d78e30df6a36
    context:
      - https://github.com/stripe/smokescreen/security/advisories/GHSA-qwrf-gfpj-qvj6

```
