### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pion/dtls: CVE-2022-29190

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#460]
CVE-2022-29190 references [github.com/pion/dtls](https://github.com/pion/dtls), which may be a Go module.

Description:
Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.4, an attacker can send packets that sends Pion DTLS into an infinite loop when processing. Version 2.1.4 contains a patch for this issue. There are currently no known workarounds available.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29190
- JSON: https://github.com/CVEProject/cvelist/tree/c9ff73eb484748bc1f36210053e5d7ce7410f59e/2022/29xxx/CVE-2022-29190.json
- Commit: https://github.com/pion/dtls/commit/e0b2ce3592e8e7d73713ac67b363a2e192a4cecf
- https://github.com/pion/dtls/releases/tag/v2.1.4
- https://github.com/pion/dtls/security/advisories/GHSA-cm8f-h6j3-p25c

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/pion/dtls
package: dtls
description: |
    Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.4, an attacker can send packets that sends Pion DTLS into an infinite loop when processing. Version 2.1.4 contains a patch for this issue. There are currently no known workarounds available.
cves:
  - CVE-2022-29190
links:
    commit: https://github.com/pion/dtls/commit/e0b2ce3592e8e7d73713ac67b363a2e192a4cecf
    context:
      - https://github.com/pion/dtls/releases/tag/v2.1.4
      - https://github.com/pion/dtls/security/advisories/GHSA-cm8f-h6j3-p25c

```
