### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pion/dtls: CVE-2022-29189

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#461]
CVE-2022-29189 references [github.com/pion/dtls](https://github.com/pion/dtls), which may be a Go module.

Description:
Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.4, a buffer that was used for inbound network traffic had no upper limit. Pion DTLS would buffer all network traffic from the remote user until the handshake completes or timed out. An attacker could exploit this to cause excessive memory usage. Version 2.1.4 contains a patch for this issue. There are currently no known workarounds available.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29189
- JSON: https://github.com/CVEProject/cvelist/tree/ea52aedcc82c4da3872cb8e6ed16d68c69315991/2022/29xxx/CVE-2022-29189.json
- Commit: https://github.com/pion/dtls/commit/a6397ff7282bc56dc37a68ea9211702edb4de1de
- https://github.com/pion/dtls/releases/tag/v2.1.4
- https://github.com/pion/dtls/security/advisories/GHSA-cx94-mrg9-rq4j

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/pion/dtls
package: dtls
description: |
    Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.4, a buffer that was used for inbound network traffic had no upper limit. Pion DTLS would buffer all network traffic from the remote user until the handshake completes or timed out. An attacker could exploit this to cause excessive memory usage. Version 2.1.4 contains a patch for this issue. There are currently no known workarounds available.
cves:
  - CVE-2022-29189
links:
    commit: https://github.com/pion/dtls/commit/a6397ff7282bc56dc37a68ea9211702edb4de1de
    context:
      - https://github.com/pion/dtls/releases/tag/v2.1.4
      - https://github.com/pion/dtls/security/advisories/GHSA-cx94-mrg9-rq4j

```
