### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/pion/dtls: CVE-2022-29222

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#462]
CVE-2022-29222 references [github.com/pion/dtls](https://github.com/pion/dtls), which may be a Go module.

Description:
Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.5, a DTLS Client could provide a Certificate that it doesn't posses the private key for and Pion DTLS wouldn't reject it. This issue affects users that are using Client certificates only. The connection itself is still secure. The Certificate provided by clients can't be trusted when using a Pion DTLS server prior to version 2.1.5. Users should upgrade to version 2.1.5 to receive a patch. There are currently no known workarounds.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29222
- JSON: https://github.com/CVEProject/cvelist/tree/ea52aedcc82c4da3872cb8e6ed16d68c69315991/2022/29xxx/CVE-2022-29222.json
- Commit: https://github.com/pion/dtls/commit/d2f797183a9f044ce976e6df6f362662ca722412
- https://github.com/pion/dtls/releases/tag/v2.1.5
- https://github.com/pion/dtls/security/advisories/GHSA-w45j-f832-hxvh

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/pion/dtls
package: dtls
description: |
    Pion DTLS is a Go implementation of Datagram Transport Layer Security. Prior to version 2.1.5, a DTLS Client could provide a Certificate that it doesn't posses the private key for and Pion DTLS wouldn't reject it. This issue affects users that are using Client certificates only. The connection itself is still secure. The Certificate provided by clients can't be trusted when using a Pion DTLS server prior to version 2.1.5. Users should upgrade to version 2.1.5 to receive a patch. There are currently no known workarounds.
cves:
  - CVE-2022-29222
links:
    commit: https://github.com/pion/dtls/commit/d2f797183a9f044ce976e6df6f362662ca722412
    context:
      - https://github.com/pion/dtls/releases/tag/v2.1.5
      - https://github.com/pion/dtls/security/advisories/GHSA-w45j-f832-hxvh

```
