### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/unicorn-engine/unicorn: CVE-2022-29694

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#472]
CVE-2022-29694 references [github.com/unicorn-engine/unicorn](https://github.com/unicorn-engine/unicorn), which may be a Go module.

Description:
Unicorn Engine v2.0.0-rc7 and below was discovered to contain a NULL pointer dereference via qemu_ram_free.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29694
- JSON: https://github.com/CVEProject/cvelist/tree/9e18858322b72ac04d72ffbe2f873d0262352ac3/2022/29xxx/CVE-2022-29694.json
- Commit: https://github.com/unicorn-engine/unicorn/pull/1593/commits/31389e59457f304be3809f9679f91a42daa7ebaa
- https://github.com/unicorn-engine/unicorn/issues/1588
- https://violentbinary.github.io/posts/2-simple-analysis-of-software-virtualization-of-memory-in-unicorn-engine/

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/unicorn-engine/unicorn
package: n/a
description: |
    Unicorn Engine v2.0.0-rc7 and below was discovered to contain a NULL pointer dereference via qemu_ram_free.
cves:
  - CVE-2022-29694
links:
    commit: https://github.com/unicorn-engine/unicorn/pull/1593/commits/31389e59457f304be3809f9679f91a42daa7ebaa
    context:
      - https://github.com/unicorn-engine/unicorn/issues/1588
      - https://violentbinary.github.io/posts/2-simple-analysis-of-software-virtualization-of-memory-in-unicorn-engine/

```
