### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/cri-o/cri-o: CVE-2022-1708

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#480]
CVE-2022-1708 references [github.com/cri-o/cri-o](https://github.com/cri-o/cri-o), which may be a Go module.

Description:
A vulnerability was found in CRI-O that causes memory or disk space exhaustion on the node for anyone with access to the Kube API. The ExecSync request runs commands in a container and logs the output of the command. This output is then read by CRI-O after command execution, and it is read in a manner where the entire file corresponding to the output of the command is read in. Thus, if the output of the command is large it is possible to exhaust the memory or the disk space of the node when CRI-O reads the output of the command. The highest threat from this vulnerability is system availability.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-1708
- JSON: https://github.com/CVEProject/cvelist/tree/f6676f3927767a50599de186c968d381d6da6d36/2022/1xxx/CVE-2022-1708.json
- Commit: https://github.com/cri-o/cri-o/commit/f032cf649ecc7e0c46718bd9e7814bfb317cb544
- https://bugzilla.redhat.com/show_bug.cgi?id=2085361
- https://github.com/cri-o/cri-o/security/advisories/GHSA-fcm2-6c3h-pg6j

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
module: github.com/cri-o/cri-o
package: CRI-O
description: |
    A vulnerability was found in CRI-O that causes memory or disk space exhaustion on the node for anyone with access to the Kube API. The ExecSync request runs commands in a container and logs the output of the command. This output is then read by CRI-O after command execution, and it is read in a manner where the entire file corresponding to the output of the command is read in. Thus, if the output of the command is large it is possible to exhaust the memory or the disk space of the node when CRI-O reads the output of the command. The highest threat from this vulnerability is system availability.
cves:
  - CVE-2022-1708
links:
    commit: https://github.com/cri-o/cri-o/commit/f032cf649ecc7e0c46718bd9e7814bfb317cb544
    context:
      - https://bugzilla.redhat.com/show_bug.cgi?id=2085361
      - https://github.com/cri-o/cri-o/security/advisories/GHSA-fcm2-6c3h-pg6j

```
