### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containerd/containerd: CVE-2022-31030

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#482]
CVE-2022-31030 references [github.com/containerd/containerd](https://github.com/containerd/containerd), which may be a Go module.

Description:
containerd is an open source container runtime. A bug was found in the containerd's CRI implementation where programs inside a container can cause the containerd daemon to consume memory without bound during invocation of the `ExecSync` API. This can cause containerd to consume all available memory on the computer, denying service to other legitimate workloads. Kubernetes and crictl can both be configured to use containerd's CRI implementation; `ExecSync` may be used when running probes or when executing processes via an "exec" facility. This bug has been fixed in containerd 1.6.6 and 1.5.13. Users should update to these versions to resolve the issue. Users unable to upgrade should ensure that only trusted images and commands are used.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31030
- JSON: https://github.com/CVEProject/cvelist/tree/f4ab4e3e569b356337a31992481f2d47ffe75337/2022/31xxx/CVE-2022-31030.json
- Commit: https://github.com/containerd/containerd/commit/c1bcabb4541930f643aa36a2b38655e131346382
- Imported by: https://pkg.go.dev/github.com/containerd/containerd?tab=importedby
- http://www.openwall.com/lists/oss-security/2022/06/07/1
- https://github.com/containerd/containerd/security/advisories/GHSA-5ffw-gxpp-mxpf

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/containerd/containerd
    package: containerd
description: |
    containerd is an open source container runtime. A bug was found in the containerd's CRI implementation where programs inside a container can cause the containerd daemon to consume memory without bound during invocation of the `ExecSync` API. This can cause containerd to consume all available memory on the computer, denying service to other legitimate workloads. Kubernetes and crictl can both be configured to use containerd's CRI implementation; `ExecSync` may be used when running probes or when executing processes via an "exec" facility. This bug has been fixed in containerd 1.6.6 and 1.5.13. Users should update to these versions to resolve the issue. Users unable to upgrade should ensure that only trusted images and commands are used.
cves:
  - CVE-2022-31030
links:
    commit: https://github.com/containerd/containerd/commit/c1bcabb4541930f643aa36a2b38655e131346382
    context:
      - http://www.openwall.com/lists/oss-security/2022/06/07/1
      - https://github.com/containerd/containerd/security/advisories/GHSA-5ffw-gxpp-mxpf

```
