### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/gogs/gogs: CVE-2022-31038

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#483]
CVE-2022-31038 references [github.com/gogs/gogs](https://github.com/gogs/gogs), which may be a Go module.

Description:
 Gogs is an open source self-hosted Git service. In versions of gogs prior to 0.12.9 `DisplayName` does not filter characters input from users, which leads to an XSS vulnerability when directly displayed in the issue list. This issue has been resolved in commit 155cae1d which sanitizes `DisplayName` prior to display to the user. All users of gogs are advised to upgrade. Users unable to upgrade should check their users' display names for malicious characters.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31038
- JSON: https://github.com/CVEProject/cvelist/tree/5325189439198ca253edea48e239f483abe36753/2022/31xxx/CVE-2022-31038.json
- Commit: https://github.com/gogs/gogs/commit/155cae1de8916fc3fde78f350763034b7422caee
- PR: https://github.com/gogs/gogs/pull/7009
- Imported by: https://pkg.go.dev/github.com/gogs/gogs?tab=importedby
- https://github.com/gogs/gogs/security/advisories/GHSA-xq4v-vrp9-vcf2

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/gogs/gogs
    package: gogs
description: |4
     Gogs is an open source self-hosted Git service. In versions of gogs prior to 0.12.9 `DisplayName` does not filter characters input from users, which leads to an XSS vulnerability when directly displayed in the issue list. This issue has been resolved in commit 155cae1d which sanitizes `DisplayName` prior to display to the user. All users of gogs are advised to upgrade. Users unable to upgrade should check their users' display names for malicious characters.
cves:
  - CVE-2022-31038
links:
    pr: https://github.com/gogs/gogs/pull/7009
    commit: https://github.com/gogs/gogs/commit/155cae1de8916fc3fde78f350763034b7422caee
    context:
      - https://github.com/gogs/gogs/security/advisories/GHSA-xq4v-vrp9-vcf2

```
