### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/envoyproxy/envoy: CVE-2022-29227

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#487]
CVE-2022-29227 references [github.com/envoyproxy/envoy](https://github.com/envoyproxy/envoy), which may be a Go module.

Description:
Envoy is a cloud-native high-performance edge/middle/service proxy. In versions prior to 1.22.1 if Envoy attempts to send an internal redirect of an HTTP request consisting of more than HTTP headers, there’s a lifetime bug which can be triggered. If while replaying the request Envoy sends a local reply when the redirect headers are processed, the downstream state indicates that the downstream stream is not complete. On sending the local reply, Envoy will attempt to reset the upstream stream, but as it is actually complete, and deleted, this result in a use-after-free. Users are advised to upgrade. Users unable to upgrade are advised to disable internal redirects if crashes are observed.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29227
- JSON: https://github.com/CVEProject/cvelist/tree/72f081cb3697a960cc2c49a3f0187f129bf20341/2022/29xxx/CVE-2022-29227.json
- Commit: https://github.com/envoyproxy/envoy/commit/fe7c69c248f4fe5a9080c7ccb35275b5218bb5ab
- Imported by: https://pkg.go.dev/github.com/envoyproxy/envoy?tab=importedby
- https://github.com/envoyproxy/envoy/security/advisories/GHSA-rm2p-qvf6-pvr6

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/envoyproxy/envoy
    package: envoy
description: |
    Envoy is a cloud-native high-performance edge/middle/service proxy. In versions prior to 1.22.1 if Envoy attempts to send an internal redirect of an HTTP request consisting of more than HTTP headers, there’s a lifetime bug which can be triggered. If while replaying the request Envoy sends a local reply when the redirect headers are processed, the downstream state indicates that the downstream stream is not complete. On sending the local reply, Envoy will attempt to reset the upstream stream, but as it is actually complete, and deleted, this result in a use-after-free. Users are advised to upgrade. Users unable to upgrade are advised to disable internal redirects if crashes are observed.
cves:
  - CVE-2022-29227
links:
    commit: https://github.com/envoyproxy/envoy/commit/fe7c69c248f4fe5a9080c7ccb35275b5218bb5ab
    context:
      - https://github.com/envoyproxy/envoy/security/advisories/GHSA-rm2p-qvf6-pvr6

```
