### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/istio/istio/security: CVE-2022-31045

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#489]
CVE-2022-31045 references [github.com/istio/istio/security](https://github.com/istio/istio/security), which may be a Go module.

Description:
Istio is an open platform to connect, manage, and secure microservices. In affected versions ill-formed headers sent to Envoy in certain configurations can lead to unexpected memory access resulting in undefined behavior or crashing. Users are most likely at risk if they have an Istio ingress Gateway exposed to external traffic. This vulnerability has been resolved in versions 1.12.8, 1.13.5, and 1.14.1. Users are advised to upgrade. There are no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31045
- JSON: https://github.com/CVEProject/cvelist/tree/f8f69ecfe4247ec0cc756cccd6637187782e47e2/2022/31xxx/CVE-2022-31045.json
- Imported by: https://pkg.go.dev/github.com/istio/istio/security?tab=importedby
- https://github.com/istio/istio/security/advisories/GHSA-xwx5-5c9g-x68x
- https://istio.io/latest/news/security/istio-security-2022-05

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/istio/istio/security
    package: istio
description: |+
    Istio is an open platform to connect, manage, and secure microservices. In affected versions ill-formed headers sent to Envoy in certain configurations can lead to unexpected memory access resulting in undefined behavior or crashing. Users are most likely at risk if they have an Istio ingress Gateway exposed to external traffic. This vulnerability has been resolved in versions 1.12.8, 1.13.5, and 1.14.1. Users are advised to upgrade. There are no known workarounds for this issue.

cves:
  - CVE-2022-31045
links:
    context:
      - https://github.com/istio/istio/security/advisories/GHSA-xwx5-5c9g-x68x
      - https://istio.io/latest/news/security/istio-security-2022-05

```
