### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/edgexfoundry/edgex-go: CVE-2022-31066

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#491]
CVE-2022-31066 references [github.com/edgexfoundry/edgex-go](https://github.com/edgexfoundry/edgex-go), which may be a Go module.

Description:
EdgeX Foundry is an open source project for building a common open framework for Internet of Things edge computing. Prior to version 2.1.1, the /api/v2/config endpoint exposes message bus credentials to local unauthenticated users. In security-enabled mode, message bus credentials are supposed to be kept in the EdgeX secret store and require authentication to access.  This vulnerability bypasses the access controls on message bus credentials when running in security-enabled mode.  (No credentials are required when running in security-disabled mode.)  As a result, attackers could intercept data or inject fake data into the EdgeX message bus. Users should upgrade to EdgeXFoundry Kamakura release (2.2.0) or to the June 2022 EdgeXFoundry LTS Jakarta release (2.1.1) to receive a patch. More information about which go modules, docker containers, and snaps contain patches is available in the GitHub Security Advisory. There are currently no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31066
- JSON: https://github.com/CVEProject/cvelist/tree/f06aac7adfb6568a42f5c813aaf8eb75951c113c/2022/31xxx/CVE-2022-31066.json
- PR: https://github.com/edgexfoundry/edgex-go/pull/4016
- Imported by: https://pkg.go.dev/github.com/edgexfoundry/edgex-go?tab=importedby
- https://github.com/edgexfoundry/edgex-go/security/advisories/GHSA-g63h-q855-vp3q

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/edgexfoundry/edgex-go
    package: edgex-go
description: |
    EdgeX Foundry is an open source project for building a common open framework for Internet of Things edge computing. Prior to version 2.1.1, the /api/v2/config endpoint exposes message bus credentials to local unauthenticated users. In security-enabled mode, message bus credentials are supposed to be kept in the EdgeX secret store and require authentication to access.  This vulnerability bypasses the access controls on message bus credentials when running in security-enabled mode.  (No credentials are required when running in security-disabled mode.)  As a result, attackers could intercept data or inject fake data into the EdgeX message bus. Users should upgrade to EdgeXFoundry Kamakura release (2.2.0) or to the June 2022 EdgeXFoundry LTS Jakarta release (2.1.1) to receive a patch. More information about which go modules, docker containers, and snaps contain patches is available in the GitHub Security Advisory. There are currently no known workarounds for this issue.
cves:
  - CVE-2022-31066
links:
    pr: https://github.com/edgexfoundry/edgex-go/pull/4016
    context:
      - https://github.com/edgexfoundry/edgex-go/security/advisories/GHSA-g63h-q855-vp3q

```
