### ISSUE TITLE
x/vulndb: potential Go vuln in Path is unknown: CVE-2022-25856

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#492]
CVE-2022-25856 references [Path is unknown](https://Path is unknown), which may be a Go module.

Description:
The package github.com/argoproj/argo-events/sensors/artifacts before 1.7.1 are vulnerable to Directory Traversal in the (g *GitArtifactReader).Read() API in git.go. This could allow arbitrary file reads if the GitArtifactReader is provided a pathname containing a symbolic link or an implicit directory name such as ...

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-25856
- JSON: https://github.com/CVEProject/cvelist/tree/c4b1a41ef5257c959f3803d1382ff0f0c1291d42/2022/25xxx/CVE-2022-25856.json
- Commit: https://github.com/argoproj/argo-events/commit/d0f66dbce78bc31923ca057b20fc722aa24ca961
- Imported by: https://pkg.go.dev/Path is unknown?tab=importedby
- https://github.com/argoproj/argo-events/issues/1947
- https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMARGOPROJARGOEVENTSSENSORSARTIFACTS-2864522

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: std
    package: Path is unknown
description: |+
    The package github.com/argoproj/argo-events/sensors/artifacts before 1.7.1 are vulnerable to Directory Traversal in the (g *GitArtifactReader).Read() API in git.go. This could allow arbitrary file reads if the GitArtifactReader is provided a pathname containing a symbolic link or an implicit directory name such as ...

cves:
  - CVE-2022-25856
credit: Derek Wang
links:
    commit: https://github.com/argoproj/argo-events/commit/d0f66dbce78bc31923ca057b20fc722aa24ca961
    context:
      - https://github.com/argoproj/argo-events/issues/1947
      - https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMARGOPROJARGOEVENTSSENSORSARTIFACTS-2864522

```
