### ISSUE TITLE
x/vulndb: potential Go vuln in std: CVE-2022-29526

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#493]
CVE-2022-29526 references [std](https://std), which may be a Go module.

Description:
Go before 1.17.10 and 1.18.x before 1.18.2 has Incorrect Privilege Assignment. When called with a non-zero flags parameter, the Faccessat function could incorrectly report that a file is accessible.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29526
- JSON: https://github.com/CVEProject/cvelist/tree/d015b1d2359d4a40204697a7ef10c0963270fcf9/2022/29xxx/CVE-2022-29526.json
- Imported by: https://pkg.go.dev/std?tab=importedby
- https://go.dev/issue/52313
- https://groups.google.com/g/golang-announce
- https://groups.google.com/g/golang-announce/c/Y5qrqw_lWdU

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: std
    package: std
description: |
    Go before 1.17.10 and 1.18.x before 1.18.2 has Incorrect Privilege Assignment. When called with a non-zero flags parameter, the Faccessat function could incorrectly report that a file is accessible.
cves:
  - CVE-2022-29526
links:
    context:
      - https://go.dev/issue/52313
      - https://groups.google.com/g/golang-announce
      - https://groups.google.com/g/golang-announce/c/Y5qrqw_lWdU

```
