### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: CVE-2022-31035

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#498]
CVE-2022-31035 references [github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd), which may be a Go module.

Description:
Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. All versions of Argo CD starting with v1.0.0 are vulnerable to a cross-site scripting (XSS) bug allowing a malicious user to inject a `javascript:` link in the UI. When clicked by a victim user, the script will execute with the victim's permissions (up to and including admin). The script would be capable of doing anything which is possible in the UI or via the API, such as creating, modifying, and deleting Kubernetes resources. A patch for this vulnerability has been released in the following Argo CD versions: v2.4.1, v2.3.5, v2.2.10 and v2.1.16. There are no completely-safe workarounds besides upgrading.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31035
- JSON: https://github.com/CVEProject/cvelist/tree/8db96d2ce5e6420b643b5ed12ad5ed70376dd84b/2022/31xxx/CVE-2022-31035.json
- Commit: https://github.com/argoproj/argo-cd/commit/8bc3ef690de29c68a36f473908774346a44d4038
- Imported by: https://pkg.go.dev/github.com/argoproj/argo-cd?tab=importedby
- https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-h4w9-6x78-8vrj

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/argoproj/argo-cd
    package: argo-cd
description: |
    Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. All versions of Argo CD starting with v1.0.0 are vulnerable to a cross-site scripting (XSS) bug allowing a malicious user to inject a `javascript:` link in the UI. When clicked by a victim user, the script will execute with the victim's permissions (up to and including admin). The script would be capable of doing anything which is possible in the UI or via the API, such as creating, modifying, and deleting Kubernetes resources. A patch for this vulnerability has been released in the following Argo CD versions: v2.4.1, v2.3.5, v2.2.10 and v2.1.16. There are no completely-safe workarounds besides upgrading.
cves:
  - CVE-2022-31035
links:
    commit: https://github.com/argoproj/argo-cd/commit/8bc3ef690de29c68a36f473908774346a44d4038
    context:
      - https://argo-cd.readthedocs.io/en/stable/user-guide/external-url/
      - https://github.com/argoproj/argo-cd/security/advisories/GHSA-h4w9-6x78-8vrj

```
