### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: CVE-2022-31036

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#499]
CVE-2022-31036 references [github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd), which may be a Go module.

Description:
Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. All versions of Argo CD starting with v1.3.0 are vulnerable to a symlink following bug allowing a malicious user with repository write access to leak sensitive YAML files from Argo CD's repo-server. A malicious Argo CD user with write access for a repository which is (or may be) used in a Helm-type Application may commit a symlink which points to an out-of-bounds file. If the target file is a valid YAML file, the attacker can read the contents of that file. Sensitive files which could be leaked include manifest files from other Applications' source repositories (potentially decrypted files, if you are using a decryption plugin) or any YAML-formatted secrets which have been mounted as files on the repo-server. Patches for this vulnerability has been released in the following Argo CD versions: v2.4.1, v2.3.5, v2.2.10 and v2.1.16. If you are using a version >=v2.3.0 and do not have any Helm-type Applications you may disable the Helm config management tool as a workaround.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31036
- JSON: https://github.com/CVEProject/cvelist/tree/8db96d2ce5e6420b643b5ed12ad5ed70376dd84b/2022/31xxx/CVE-2022-31036.json
- Commit: https://github.com/argoproj/argo-cd/commit/04c305396458508a31d03d44afea07b1c620d7cd
- Imported by: https://pkg.go.dev/github.com/argoproj/argo-cd?tab=importedby
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-q4w5-4gq2-98vm

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/argoproj/argo-cd
    package: argo-cd
description: |+
    Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. All versions of Argo CD starting with v1.3.0 are vulnerable to a symlink following bug allowing a malicious user with repository write access to leak sensitive YAML files from Argo CD's repo-server. A malicious Argo CD user with write access for a repository which is (or may be) used in a Helm-type Application may commit a symlink which points to an out-of-bounds file. If the target file is a valid YAML file, the attacker can read the contents of that file. Sensitive files which could be leaked include manifest files from other Applications' source repositories (potentially decrypted files, if you are using a decryption plugin) or any YAML-formatted secrets which have been mounted as files on the repo-server. Patches for this vulnerability has been released in the following Argo CD versions: v2.4.1, v2.3.5, v2.2.10 and v2.1.16. If you are using a version >=v2.3.0 and do not have any Helm-type Applications you may disable the Helm config management tool as a workaround.

cves:
  - CVE-2022-31036
links:
    commit: https://github.com/argoproj/argo-cd/commit/04c305396458508a31d03d44afea07b1c620d7cd
    context:
      - https://github.com/argoproj/argo-cd/security/advisories/GHSA-q4w5-4gq2-98vm

```
