### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubeedge/kubeedge: CVE-2022-31076

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#500]
CVE-2022-31076 references [github.com/kubeedge/kubeedge](https://github.com/kubeedge/kubeedge), which may be a Go module.

Description:
KubeEdge is built upon Kubernetes and extends native containerized application orchestration and device management to hosts at the Edge. In affected versions a malicious message can crash CloudCore by triggering a nil-pointer dereference in the UDS Server. Since the UDS Server only communicates with the CSI Driver on the cloud side, the attack is limited to the local host network. As such, an attacker would already need to be an authenticated user of the Cloud. Additionally it will be affected only when users turn on the unixsocket switch in the config file cloudcore.yaml. This bug has been fixed in Kubeedge 1.11.0, 1.10.1, and 1.9.3. Users should update to these versions to resolve the issue. Users unable to upgrade should sisable the unixsocket switch of CloudHub in the config file cloudcore.yaml.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31076
- JSON: https://github.com/CVEProject/cvelist/tree/972fb21ae4831b9db56587edb6c17d63290f8b53/2022/31xxx/CVE-2022-31076.json
- Commit: https://github.com/kubeedge/kubeedge/pull/3899/commits/5d60ae9eabd6b6b7afe38758e19bbe8137664701
- Imported by: https://pkg.go.dev/github.com/kubeedge/kubeedge?tab=importedby
- https://github.com/kubeedge/kubeedge/security/advisories/GHSA-8f4f-v9x5-cg6j

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/kubeedge/kubeedge
    package: kubeedge
description: |
    KubeEdge is built upon Kubernetes and extends native containerized application orchestration and device management to hosts at the Edge. In affected versions a malicious message can crash CloudCore by triggering a nil-pointer dereference in the UDS Server. Since the UDS Server only communicates with the CSI Driver on the cloud side, the attack is limited to the local host network. As such, an attacker would already need to be an authenticated user of the Cloud. Additionally it will be affected only when users turn on the unixsocket switch in the config file cloudcore.yaml. This bug has been fixed in Kubeedge 1.11.0, 1.10.1, and 1.9.3. Users should update to these versions to resolve the issue. Users unable to upgrade should sisable the unixsocket switch of CloudHub in the config file cloudcore.yaml.
cves:
  - CVE-2022-31076
links:
    commit: https://github.com/kubeedge/kubeedge/pull/3899/commits/5d60ae9eabd6b6b7afe38758e19bbe8137664701
    context:
      - https://github.com/kubeedge/kubeedge/security/advisories/GHSA-8f4f-v9x5-cg6j

```
