### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubeedge/kubeedge: CVE-2022-31077

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#501]
CVE-2022-31077 references [github.com/kubeedge/kubeedge](https://github.com/kubeedge/kubeedge), which may be a Go module.

Description:
KubeEdge is built upon Kubernetes and extends native containerized application orchestration and device management to hosts at the Edge. In affected versions a malicious message response from KubeEdge can crash the CSI Driver controller server by triggering a nil-pointer dereference panic. As a consequence, the CSI Driver controller will be in denial of service. This bug has been fixed in Kubeedge 1.11.0, 1.10.1, and 1.9.3. Users should update to these versions to resolve the issue. At the time of writing, no workaround exists.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31077
- JSON: https://github.com/CVEProject/cvelist/tree/972fb21ae4831b9db56587edb6c17d63290f8b53/2022/31xxx/CVE-2022-31077.json
- Commit: https://github.com/kubeedge/kubeedge/pull/3899/commits/5d60ae9eabd6b6b7afe38758e19bbe8137664701
- PR: https://github.com/kubeedge/kubeedge/pull/3899
- Imported by: https://pkg.go.dev/github.com/kubeedge/kubeedge?tab=importedby
- https://github.com/kubeedge/kubeedge/security/advisories/GHSA-x938-fvfw-7jh5

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/kubeedge/kubeedge
    package: kubeedge
description: |+
    KubeEdge is built upon Kubernetes and extends native containerized application orchestration and device management to hosts at the Edge. In affected versions a malicious message response from KubeEdge can crash the CSI Driver controller server by triggering a nil-pointer dereference panic. As a consequence, the CSI Driver controller will be in denial of service. This bug has been fixed in Kubeedge 1.11.0, 1.10.1, and 1.9.3. Users should update to these versions to resolve the issue. At the time of writing, no workaround exists.

cves:
  - CVE-2022-31077
links:
    pr: https://github.com/kubeedge/kubeedge/pull/3899
    commit: https://github.com/kubeedge/kubeedge/pull/3899/commits/5d60ae9eabd6b6b7afe38758e19bbe8137664701
    context:
      - https://github.com/kubeedge/kubeedge/security/advisories/GHSA-x938-fvfw-7jh5

```
