### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/weaveworks/weave-gitops: CVE-2022-31098

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#502]
CVE-2022-31098 references [github.com/weaveworks/weave-gitops](https://github.com/weaveworks/weave-gitops), which may be a Go module.

Description:
Weave GitOps is a simple open source developer platform for people who want cloud native applications, without needing Kubernetes expertise. A vulnerability in the logging of Weave GitOps could allow an authenticated remote attacker to view sensitive cluster configurations, aka KubeConfg, of registered Kubernetes clusters, including the service account tokens in plain text from Weave GitOps's pod logs on the management cluster. An unauthorized remote attacker can also view these sensitive configurations from external log storage if enabled by the management cluster. This vulnerability is due to the client factory dumping cluster configurations and their service account tokens when the cluster manager tries to connect to an API server of a registered cluster, and a connection error occurs. An attacker could exploit this vulnerability by either accessing logs of a pod of Weave GitOps, or from external log storage and obtaining all cluster configurations of registered clusters. A successful exploit could allow the attacker to use those cluster configurations to manage the registered Kubernetes clusters. This vulnerability has been fixed by commit 567356f471353fb5c676c77f5abc2a04631d50ca. Users should upgrade to Weave GitOps core version v0.8.1-rc.6 or newer. There is no known workaround for this vulnerability.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31098
- JSON: https://github.com/CVEProject/cvelist/tree/198e47396c4bd9bfdb63664d5848885a92491c9f/2022/31xxx/CVE-2022-31098.json
- Commit: https://github.com/weaveworks/weave-gitops/commit/567356f471353fb5c676c77f5abc2a04631d50ca
- Imported by: https://pkg.go.dev/github.com/weaveworks/weave-gitops?tab=importedby
- https://github.com/weaveworks/weave-gitops/security/advisories/GHSA-xggc-qprg-x6mw

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/weaveworks/weave-gitops
    package: weave-gitops
description: |+
    Weave GitOps is a simple open source developer platform for people who want cloud native applications, without needing Kubernetes expertise. A vulnerability in the logging of Weave GitOps could allow an authenticated remote attacker to view sensitive cluster configurations, aka KubeConfg, of registered Kubernetes clusters, including the service account tokens in plain text from Weave GitOps's pod logs on the management cluster. An unauthorized remote attacker can also view these sensitive configurations from external log storage if enabled by the management cluster. This vulnerability is due to the client factory dumping cluster configurations and their service account tokens when the cluster manager tries to connect to an API server of a registered cluster, and a connection error occurs. An attacker could exploit this vulnerability by either accessing logs of a pod of Weave GitOps, or from external log storage and obtaining all cluster configurations of registered clusters. A successful exploit could allow the attacker to use those cluster configurations to manage the registered Kubernetes clusters. This vulnerability has been fixed by commit 567356f471353fb5c676c77f5abc2a04631d50ca. Users should upgrade to Weave GitOps core version v0.8.1-rc.6 or newer. There is no known workaround for this vulnerability.

cves:
  - CVE-2022-31098
links:
    commit: https://github.com/weaveworks/weave-gitops/commit/567356f471353fb5c676c77f5abc2a04631d50ca
    context:
      - https://github.com/weaveworks/weave-gitops/security/advisories/GHSA-xggc-qprg-x6mw

```
