### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hyperledger/fabric: CVE-2022-31121

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#506]
CVE-2022-31121 references [github.com/hyperledger/fabric](https://github.com/hyperledger/fabric), which may be a Go module.

Description:
Hyperledger Fabric is a permissioned distributed ledger framework. In affected versions if a consensus client sends a malformed consensus request to an orderer it may crash the orderer node. A fix has been added in commit 0f1835949 which checks for missing consensus messages and returns an error to the consensus client should the message be missing. Users are advised to upgrade to versions 2.2.7 or v2.4.5. There are no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31121
- JSON: https://github.com/CVEProject/cvelist/tree/776f3211646dd15c9b953d6b3616d88fb4738b7a/2022/31xxx/CVE-2022-31121.json
- Commit: https://github.com/hyperledger/fabric/commit/0f18359493bcbd5f9f9d1a9b05adabfe5da23b06
- Imported by: https://pkg.go.dev/github.com/hyperledger/fabric?tab=importedby
- https://github.com/hyperledger/fabric/releases/tag/v2.2.7
- https://github.com/hyperledger/fabric/releases/tag/v2.4.5
- https://github.com/hyperledger/fabric/security/advisories/GHSA-72x4-cq6r-jp4p

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/hyperledger/fabric
    package: fabric
description: |+
    Hyperledger Fabric is a permissioned distributed ledger framework. In affected versions if a consensus client sends a malformed consensus request to an orderer it may crash the orderer node. A fix has been added in commit 0f1835949 which checks for missing consensus messages and returns an error to the consensus client should the message be missing. Users are advised to upgrade to versions 2.2.7 or v2.4.5. There are no known workarounds for this issue.

cves:
  - CVE-2022-31121
links:
    commit: https://github.com/hyperledger/fabric/commit/0f18359493bcbd5f9f9d1a9b05adabfe5da23b06
    context:
      - https://github.com/hyperledger/fabric/releases/tag/v2.2.7
      - https://github.com/hyperledger/fabric/releases/tag/v2.4.5
      - https://github.com/hyperledger/fabric/security/advisories/GHSA-72x4-cq6r-jp4p

```
