### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubeedge/kubeedge: CVE-2022-31073

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#507]
CVE-2022-31073 references [github.com/kubeedge/kubeedge](https://github.com/kubeedge/kubeedge), which may be a Go module.

Description:
KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, the ServiceBus server on the edge side may be susceptible to a DoS attack if an HTTP request containing a very large Body is sent to it. It is possible for the node to be exhausted of memory. The consequence of the exhaustion is that other services on the node, e.g. other containers, will be unable to allocate memory and thus causing a denial of service. Malicious apps accidentally pulled by users on the host and have the access to send HTTP requests to localhost may make an attack. It will be affected only when users enable the `ServiceBus` module in the config file `edgecore.yaml`. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. As a workaround, disable the `ServiceBus` module in the config file `edgecore.yaml`.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31073
- JSON: https://github.com/CVEProject/cvelist/tree/bf22978fad2f0ca5f0b522bb88794d5c574e70da/2022/31xxx/CVE-2022-31073.json
- PR: https://github.com/kubeedge/kubeedge/pull/4042
- Imported by: https://pkg.go.dev/github.com/kubeedge/kubeedge?tab=importedby
- https://github.com/kubeedge/kubeedge/security/advisories/GHSA-vwm6-qc77-v2rh

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/kubeedge/kubeedge
    package: kubeedge
description: |
    KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, the ServiceBus server on the edge side may be susceptible to a DoS attack if an HTTP request containing a very large Body is sent to it. It is possible for the node to be exhausted of memory. The consequence of the exhaustion is that other services on the node, e.g. other containers, will be unable to allocate memory and thus causing a denial of service. Malicious apps accidentally pulled by users on the host and have the access to send HTTP requests to localhost may make an attack. It will be affected only when users enable the `ServiceBus` module in the config file `edgecore.yaml`. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. As a workaround, disable the `ServiceBus` module in the config file `edgecore.yaml`.
cves:
  - CVE-2022-31073
links:
    pr: https://github.com/kubeedge/kubeedge/pull/4042
    context:
      - https://github.com/kubeedge/kubeedge/security/advisories/GHSA-vwm6-qc77-v2rh

```
