### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubeedge/kubeedge: CVE-2022-31075

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#509]
CVE-2022-31075 references [github.com/kubeedge/kubeedge](https://github.com/kubeedge/kubeedge), which may be a Go module.

Description:
KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, EdgeCore may be susceptible to a DoS attack on CloudHub if an attacker was to send a well-crafted HTTP request to `/edge.crt`. If an attacker can send a well-crafted HTTP request to CloudHub, and that request has a very large body, that request can crash the HTTP service through a memory exhaustion vector. The request body is being read into memory, and a body that is larger than the available memory can lead to a successful attack. Because the request would have to make it through authorization, only authorized users may perform this attack. The consequence of the exhaustion is that CloudHub will be in denial of service. KubeEdge is affected only when users enable the CloudHub module in the file `cloudcore.yaml`. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. As a workaround, disable the CloudHub switch in the config file `cloudcore.yaml`.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31075
- JSON: https://github.com/CVEProject/cvelist/tree/bf22978fad2f0ca5f0b522bb88794d5c574e70da/2022/31xxx/CVE-2022-31075.json
- Imported by: https://pkg.go.dev/github.com/kubeedge/kubeedge?tab=importedby
- https://github.com/kubeedge/kubeedge/security/advisories/GHSA-x3px-2p95-f6jr

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/kubeedge/kubeedge
    package: kubeedge
description: |
    KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, EdgeCore may be susceptible to a DoS attack on CloudHub if an attacker was to send a well-crafted HTTP request to `/edge.crt`. If an attacker can send a well-crafted HTTP request to CloudHub, and that request has a very large body, that request can crash the HTTP service through a memory exhaustion vector. The request body is being read into memory, and a body that is larger than the available memory can lead to a successful attack. Because the request would have to make it through authorization, only authorized users may perform this attack. The consequence of the exhaustion is that CloudHub will be in denial of service. KubeEdge is affected only when users enable the CloudHub module in the file `cloudcore.yaml`. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. As a workaround, disable the CloudHub switch in the config file `cloudcore.yaml`.
cves:
  - CVE-2022-31075
links:
    context:
      - https://github.com/kubeedge/kubeedge/security/advisories/GHSA-x3px-2p95-f6jr

```
