### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubeedge/kubeedge: CVE-2022-31080

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#512]
CVE-2022-31080 references [github.com/kubeedge/kubeedge](https://github.com/kubeedge/kubeedge), which may be a Go module.

Description:
KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, a large response received by the viaduct WSClient can cause a DoS from memory exhaustion. The entire body of the response is being read into memory which could allow an attacker to send a request that returns a response with a large body. The consequence of the exhaustion is that the process which invokes a WSClient will be in a denial of service. The software is affected If users who are authenticated to the edge side connect to `cloudhub` from the edge side through WebSocket protocol. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. There are currently no known workarounds.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31080
- JSON: https://github.com/CVEProject/cvelist/tree/bf22978fad2f0ca5f0b522bb88794d5c574e70da/2022/31xxx/CVE-2022-31080.json
- Imported by: https://pkg.go.dev/github.com/kubeedge/kubeedge?tab=importedby
- https://github.com/kubeedge/kubeedge/security/advisories/GHSA-6wvc-6pww-qr4r

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/kubeedge/kubeedge
    package: kubeedge
description: |
    KubeEdge is an open source system for extending native containerized application orchestration capabilities to hosts at Edge. Prior to versions 1.11.1, 1.10.2, and 1.9.4, a large response received by the viaduct WSClient can cause a DoS from memory exhaustion. The entire body of the response is being read into memory which could allow an attacker to send a request that returns a response with a large body. The consequence of the exhaustion is that the process which invokes a WSClient will be in a denial of service. The software is affected If users who are authenticated to the edge side connect to `cloudhub` from the edge side through WebSocket protocol. This bug has been fixed in Kubeedge 1.11.1, 1.10.2, and 1.9.4. There are currently no known workarounds.
cves:
  - CVE-2022-31080
links:
    context:
      - https://github.com/kubeedge/kubeedge/security/advisories/GHSA-6wvc-6pww-qr4r

```
