### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/git/git: CVE-2022-29187

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#513]
CVE-2022-29187 references [github.com/git/git](https://github.com/git/git), which may be a Go module.

Description:
Git is a distributed revision control system. Git prior to versions 2.37.1, 2.36.2, 2.35.4, 2.34.4, 2.33.4, 2.32.3, 2.31.4, and 2.30.5, is vulnerable to privilege escalation in all platforms. An unsuspecting user could still be affected by the issue reported in CVE-2022-24765, for example when navigating as root into a shared tmp directory that is owned by them, but where an attacker could create a git repository. Versions 2.37.1, 2.36.2, 2.35.4, 2.34.4, 2.33.4, 2.32.3, 2.31.4, and 2.30.5 contain a patch for this issue. The simplest way to avoid being affected by the exploit described in the example is to avoid running git as root (or an Administrator in Windows), and if needed to reduce its use to a minimum. While a generic workaround is not possible, a system could be hardened from the exploit described in the example by removing any such repository if it exists already and creating one as root to block any future attacks.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-29187
- JSON: https://github.com/CVEProject/cvelist/tree/b0513a166295823b7b994e07fdfdb1eead86c764/2022/29xxx/CVE-2022-29187.json
- Imported by: https://pkg.go.dev/github.com/git/git?tab=importedby
- https://github.blog/2022-04-12-git-security-vulnerability-announced
- https://github.com/git/git/security/advisories/GHSA-j342-m5hw-rr3v
- https://lore.kernel.org/git/xmqqv8s2fefi.fsf@gitster.g/T/#u

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/git/git
    package: git
description: |
    Git is a distributed revision control system. Git prior to versions 2.37.1, 2.36.2, 2.35.4, 2.34.4, 2.33.4, 2.32.3, 2.31.4, and 2.30.5, is vulnerable to privilege escalation in all platforms. An unsuspecting user could still be affected by the issue reported in CVE-2022-24765, for example when navigating as root into a shared tmp directory that is owned by them, but where an attacker could create a git repository. Versions 2.37.1, 2.36.2, 2.35.4, 2.34.4, 2.33.4, 2.32.3, 2.31.4, and 2.30.5 contain a patch for this issue. The simplest way to avoid being affected by the exploit described in the example is to avoid running git as root (or an Administrator in Windows), and if needed to reduce its use to a minimum. While a generic workaround is not possible, a system could be hardened from the exploit described in the example by removing any such repository if it exists already and creating one as root to block any future attacks.
cves:
  - CVE-2022-29187
links:
    context:
      - https://github.blog/2022-04-12-git-security-vulnerability-announced
      - https://github.com/git/git/security/advisories/GHSA-j342-m5hw-rr3v
      - https://lore.kernel.org/git/xmqqv8s2fefi.fsf@gitster.g/T/#u

```
