### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/git-for-windows/git: CVE-2022-31012

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#514]
CVE-2022-31012 references [github.com/git-for-windows/git](https://github.com/git-for-windows/git), which may be a Go module.

Description:
Git for Windows is a fork of Git that contains Windows-specific patches. This vulnerability in versions prior to 2.37.1 lets Git for Windows' installer execute a binary into `C:\mingw64\bin\git.exe` by mistake. This only happens upon a fresh install, not when upgrading Git for Windows. A patch is included in version 2.37.1. Two workarounds are available. Create the `C:\mingw64` folder  and remove read/write access from this folder, or disallow arbitrary authenticated users to create folders in `C:\`.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31012
- JSON: https://github.com/CVEProject/cvelist/tree/b0513a166295823b7b994e07fdfdb1eead86c764/2022/31xxx/CVE-2022-31012.json
- Imported by: https://pkg.go.dev/github.com/git-for-windows/git?tab=importedby
- https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1
- https://github.com/git-for-windows/git/security/advisories/GHSA-gjrj-fxvp-hjj2

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/git-for-windows/git
    package: git
description: |
    Git for Windows is a fork of Git that contains Windows-specific patches. This vulnerability in versions prior to 2.37.1 lets Git for Windows' installer execute a binary into `C:\mingw64\bin\git.exe` by mistake. This only happens upon a fresh install, not when upgrading Git for Windows. A patch is included in version 2.37.1. Two workarounds are available. Create the `C:\mingw64` folder  and remove read/write access from this folder, or disallow arbitrary authenticated users to create folders in `C:\`.
cves:
  - CVE-2022-31012
links:
    context:
      - https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1
      - https://github.com/git-for-windows/git/security/advisories/GHSA-gjrj-fxvp-hjj2

```
