### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: CVE-2022-1025

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#516]
CVE-2022-1025 references [github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd), which may be a Go module.

Description:
All unpatched versions of Argo CD starting with v1.0.0 are vulnerable to an improper access control bug, allowing a malicious user to potentially escalate their privileges to admin-level.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-1025
- JSON: https://github.com/CVEProject/cvelist/tree/58f1d8346e46bf1fcf4b15d6f7ca601cca46996b/2022/1xxx/CVE-2022-1025.json
- Imported by: https://pkg.go.dev/github.com/argoproj/argo-cd?tab=importedby
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-2f5v-8r3f-8pww

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/argoproj/argo-cd
    package: ArgoCD
description: |
    All unpatched versions of Argo CD starting with v1.0.0 are vulnerable to an improper access control bug, allowing a malicious user to potentially escalate their privileges to admin-level.
cves:
  - CVE-2022-1025
links:
    context:
      - https://github.com/argoproj/argo-cd/security/advisories/GHSA-2f5v-8r3f-8pww

```
