### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: CVE-2022-31102

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#517]
CVE-2022-31102 references [github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd), which may be a Go module.

Description:
Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. Argo CD starting with 2.3.0 and prior to 2.3.6 and 2.4.5 is vulnerable to a cross-site scripting (XSS) bug which could allow an attacker to inject arbitrary JavaScript in the `/auth/callback` page in a victim's browser. This vulnerability only affects Argo CD instances which have single sign on (SSO) enabled. The exploit also assumes the attacker has 1) access to the API server's encryption key, 2) a method to add a cookie to the victim's browser, and 3) the ability to convince the victim to visit a malicious `/auth/callback` link. The vulnerability is classified as low severity because access to the API server's encryption key already grants a high level of access. Exploiting the XSS would allow the attacker to impersonate the victim, but would not grant any privileges which the attacker could not otherwise gain using the encryption key. A patch for this vulnerability has been released in the following Argo CD versions 2.4.5 and 2.3.6. There is currently no known workaround.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31102
- JSON: https://github.com/CVEProject/cvelist/tree/0dbfef96d363d1f2dae7591bef384a82b7590d54/2022/31xxx/CVE-2022-31102.json
- Imported by: https://pkg.go.dev/github.com/argoproj/argo-cd?tab=importedby
- https://github.com/argoproj/argo-cd/releases/tag/v2.3.6
- https://github.com/argoproj/argo-cd/releases/tag/v2.4.5
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-pmjg-52h9-72qv

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/argoproj/argo-cd
    package: argo-cd
description: |
    Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. Argo CD starting with 2.3.0 and prior to 2.3.6 and 2.4.5 is vulnerable to a cross-site scripting (XSS) bug which could allow an attacker to inject arbitrary JavaScript in the `/auth/callback` page in a victim's browser. This vulnerability only affects Argo CD instances which have single sign on (SSO) enabled. The exploit also assumes the attacker has 1) access to the API server's encryption key, 2) a method to add a cookie to the victim's browser, and 3) the ability to convince the victim to visit a malicious `/auth/callback` link. The vulnerability is classified as low severity because access to the API server's encryption key already grants a high level of access. Exploiting the XSS would allow the attacker to impersonate the victim, but would not grant any privileges which the attacker could not otherwise gain using the encryption key. A patch for this vulnerability has been released in the following Argo CD versions 2.4.5 and 2.3.6. There is currently no known workaround.
cves:
  - CVE-2022-31102
links:
    context:
      - https://github.com/argoproj/argo-cd/releases/tag/v2.3.6
      - https://github.com/argoproj/argo-cd/releases/tag/v2.4.5
      - https://github.com/argoproj/argo-cd/security/advisories/GHSA-pmjg-52h9-72qv

```
