### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/argoproj/argo-cd: CVE-2022-31105

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#518]
CVE-2022-31105 references [github.com/argoproj/argo-cd](https://github.com/argoproj/argo-cd), which may be a Go module.

Description:
Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. Argo CD starting with version 0.4.0 and prior to 2.2.11, 2.3.6, and 2.4.5 is vulnerable to an improper certificate validation bug which could cause Argo CD to trust a malicious (or otherwise untrustworthy) OpenID Connect (OIDC) provider. A patch for this vulnerability has been released in Argo CD versions 2.4.5, 2.3.6, and 2.2.11. There are no complete workarounds, but a partial workaround is available. Those who use an external OIDC provider (not the bundled Dex instance), can mitigate the issue by setting the `oidc.config.rootCA` field in the `argocd-cm` ConfigMap. This mitigation only forces certificate validation when the API server handles login flows. It does not force certificate verification when verifying tokens on API calls.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31105
- JSON: https://github.com/CVEProject/cvelist/tree/0dbfef96d363d1f2dae7591bef384a82b7590d54/2022/31xxx/CVE-2022-31105.json
- Imported by: https://pkg.go.dev/github.com/argoproj/argo-cd?tab=importedby
- https://github.com/argoproj/argo-cd/releases/tag/v2.3.6
- https://github.com/argoproj/argo-cd/releases/tag/v2.4.5
- https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/argoproj/argo-cd
    package: argo-cd
description: |
    Argo CD is a declarative, GitOps continuous delivery tool for Kubernetes. Argo CD starting with version 0.4.0 and prior to 2.2.11, 2.3.6, and 2.4.5 is vulnerable to an improper certificate validation bug which could cause Argo CD to trust a malicious (or otherwise untrustworthy) OpenID Connect (OIDC) provider. A patch for this vulnerability has been released in Argo CD versions 2.4.5, 2.3.6, and 2.2.11. There are no complete workarounds, but a partial workaround is available. Those who use an external OIDC provider (not the bundled Dex instance), can mitigate the issue by setting the `oidc.config.rootCA` field in the `argocd-cm` ConfigMap. This mitigation only forces certificate validation when the API server handles login flows. It does not force certificate verification when verifying tokens on API calls.
cves:
  - CVE-2022-31105
links:
    context:
      - https://github.com/argoproj/argo-cd/releases/tag/v2.3.6
      - https://github.com/argoproj/argo-cd/releases/tag/v2.4.5
      - https://github.com/argoproj/argo-cd/security/advisories/GHSA-7943-82jg-wmw5

```
