### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/flyteorg/flyteadmin: CVE-2022-31145

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#519]
CVE-2022-31145 references [github.com/flyteorg/flyteadmin](https://github.com/flyteorg/flyteadmin), which may be a Go module.

Description:
FlyteAdmin is the control plane for Flyte responsible for managing entities and administering workflow executions. In versions 1.1.30 and prior, authenticated users using an external identity provider can continue to use Access Tokens and ID Tokens even after they expire. Users who use FlyteAdmin as the OAuth2 Authorization Server are unaffected by this issue. A patch is available on the `master` branch of the repository. As a workaround, rotating signing keys immediately will invalidate all open sessions and force all users to attempt to obtain new tokens. Those who use this workaround should continue to rotate keys until FlyteAdmin has been upgraded and hide FlyteAdmin deployment ingress URL from the internet.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-31145
- JSON: https://github.com/CVEProject/cvelist/tree/6a3e4c10f4957bb316f091a88c5946831468b31b/2022/31xxx/CVE-2022-31145.json
- Commit: https://github.com/flyteorg/flyteadmin/commit/a1ec282d02706e074bc4986fd0412e5da3b9d00a
- PR: https://github.com/flyteorg/flyteadmin/pull/455
- Imported by: https://pkg.go.dev/github.com/flyteorg/flyteadmin?tab=importedby
- https://github.com/flyteorg/flyteadmin/security/advisories/GHSA-qwrj-9hmp-gpxh

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/flyteorg/flyteadmin
    package: flyteadmin
description: |
    FlyteAdmin is the control plane for Flyte responsible for managing entities and administering workflow executions. In versions 1.1.30 and prior, authenticated users using an external identity provider can continue to use Access Tokens and ID Tokens even after they expire. Users who use FlyteAdmin as the OAuth2 Authorization Server are unaffected by this issue. A patch is available on the `master` branch of the repository. As a workaround, rotating signing keys immediately will invalidate all open sessions and force all users to attempt to obtain new tokens. Those who use this workaround should continue to rotate keys until FlyteAdmin has been upgraded and hide FlyteAdmin deployment ingress URL from the internet.
cves:
  - CVE-2022-31145
links:
    pr: https://github.com/flyteorg/flyteadmin/pull/455
    commit: https://github.com/flyteorg/flyteadmin/commit/a1ec282d02706e074bc4986fd0412e5da3b9d00a
    context:
      - https://github.com/flyteorg/flyteadmin/security/advisories/GHSA-qwrj-9hmp-gpxh

```
