### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/cilium/cilium: GHSA-wc5v-r48v-g4vh

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#530]
In GitHub Security Advisory [GHSA-wc5v-r48v-g4vh](https://github.com/advisories/GHSA-wc5v-r48v-g4vh), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/cilium/cilium](https://pkg.go.dev/github.com/cilium/cilium) | 1.11.7 | >= 1.11.0, < 1.11.7 || [github.com/cilium/cilium](https://pkg.go.dev/github.com/cilium/cilium) | 1.10.13 | < 1.10.13 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/cilium/cilium
    versions:
      - introduced: 1.11.0
        fixed: 1.11.7
  - package: github.com/cilium/cilium
    versions:
      - fixed: 1.10.13
description: |-
    ### Impact

    This vulnerability allows bypassing host policies for IPv6 traffic coming from a Cilium-managed pod and destined to the host-network namespace (e.g., to a host-network pod). Host policy enforcement on IPv4 or for traffic coming from outside the node is not affected.

    Cilium is only affected by this vulnerability if IPv4, IPv6, endpoint routes, and the host firewall are enabled. Note that endpoint routes are typically only enabled in GKE, EKS, AKS, and OpenShift; in those environments, IPv6 is typically disabled. Host firewall is disabled by default.

    ### Patches

    The bug is fixed in versions v1.10.13 and v1.11.7 of Cilium.

    ### Workarounds

    For affected users who can't upgrade, one potential workaround is to ensure all pods have network policies that prevent sending arbitrary traffic to the local node.

    ### References

    N/A

    ### For more information

    If you have any questions or comments about this advisory, please reach out on [Slack](https://docs.cilium.io/en/latest/community/community/#slack).

    As usual, if you think you found a related vulnerability, we strongly encourage you to report security vulnerabilities to our private security mailing list: [security@cilium.io](mailto:security@cilium.io)---first, before disclosing them in any public forums. This is a private mailing list where only members of the Cilium internal security team are subscribed to, and is treated as top priority.
published: 2022-07-15T21:46:51Z
last_modified: 2022-07-15T21:46:52Z
ghsas:
  - GHSA-wc5v-r48v-g4vh
links:
    context:
      - https://github.com/advisories/GHSA-wc5v-r48v-g4vh

```
