### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/runatlantis/atlantis/server/controllers/events: CVE-2022-24912

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#534]
CVE-2022-24912 references [Path is unknown](https://Path is unknown), which may be a Go module.

Description:
The package github.com/runatlantis/atlantis/server/controllers/events before 0.19.7 are vulnerable to Timing Attack in the webhook event validator code, which does not use a constant-time comparison function to validate the webhook secret. It can allow an attacker to recover this secret as an attacker and then forge webhook events.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-24912
- JSON: https://github.com/CVEProject/cvelist/tree/612b564fc132f8c32988f03f9aff7fd65e84ff70/2022/24xxx/CVE-2022-24912.json
- Commit: https://github.com/runatlantis/atlantis/commit/48870911974adddaa4c99c8089e79b7d787fa820
- Imported by: https://pkg.go.dev/Path is unknown?tab=importedby
- https://github.com/runatlantis/atlantis/issues/2391
- https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMRUNATLANTISATLANTISSERVERCONTROLLERSEVENTS-2950851

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: std
    package: Path is unknown
description: |+
    The package github.com/runatlantis/atlantis/server/controllers/events before 0.19.7 are vulnerable to Timing Attack in the webhook event validator code, which does not use a constant-time comparison function to validate the webhook secret. It can allow an attacker to recover this secret as an attacker and then forge webhook events.

cves:
  - CVE-2022-24912
credit: cedws
links:
    commit: https://github.com/runatlantis/atlantis/commit/48870911974adddaa4c99c8089e79b7d787fa820
    context:
      - https://github.com/runatlantis/atlantis/issues/2391
      - https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMRUNATLANTISATLANTISSERVERCONTROLLERSEVENTS-2950851

```
