### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containrrr/shoutrrr/pkg/util: GHSA-477v-w82m-634j

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#538]
In GitHub Security Advisory [GHSA-477v-w82m-634j](https://github.com/advisories/GHSA-477v-w82m-634j), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/containrrr/shoutrrr/pkg/util](https://pkg.go.dev/github.com/containrrr/shoutrrr/pkg/util) | 0.6.0 | < 0.6.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/containrrr/shoutrrr/pkg/util
    versions:
      - fixed: 0.6.0
description: The package github.com/containrrr/shoutrrr/pkg/util before 0.6.0 are
    vulnerable to Denial of Service (DoS) via the util.PartitionMessage function.
    Exploiting this vulnerability is possible by sending exactly 2000, 4000, or 6000
    characters messages.
published: 2022-07-16T00:00:20Z
last_modified: 2022-07-22T16:31:26Z
cves:
  - CVE-2022-25891
ghsas:
  - GHSA-477v-w82m-634j
links:
    context:
      - https://github.com/advisories/GHSA-477v-w82m-634j

```
