### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/caddyserver/caddy: GHSA-m7gr-5w5g-36jf

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#544]
In GitHub Security Advisory [GHSA-m7gr-5w5g-36jf](https://github.com/advisories/GHSA-m7gr-5w5g-36jf), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/caddyserver/caddy](https://pkg.go.dev/github.com/caddyserver/caddy) | 2.5.2 | < 2.5.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/caddyserver/caddy
    versions:
      - fixed: 2.5.2
description: |-
    An out-of-bounds read in the rewrite function at /modules/caddyhttp/rewrite/rewrite.go in Caddy v2.5.1 allows attackers to cause a Denial of Service (DoS) on the client side via a crafted URI.

    According to the maintainer, the bug only affects the client side of the request and cannot cause a denial of service on the server.
published: 2022-07-23T00:00:22Z
last_modified: 2022-07-29T13:06:40Z
cves:
  - CVE-2022-34037
ghsas:
  - GHSA-m7gr-5w5g-36jf
links:
    context:
      - https://github.com/advisories/GHSA-m7gr-5w5g-36jf

```
