### ISSUE TITLE
x/vulndb: potential Go vuln in sigs.k8s.io/aws-iam-authenticator: GHSA-pp3f-98qg-5g75

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#548]
In GitHub Security Advisory [GHSA-pp3f-98qg-5g75](https://github.com/advisories/GHSA-pp3f-98qg-5g75), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [sigs.k8s.io/aws-iam-authenticator](https://pkg.go.dev/sigs.k8s.io/aws-iam-authenticator) | 0.5.9 | < 0.5.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: sigs.k8s.io/aws-iam-authenticator
    versions:
      - fixed: 0.5.9
description: A security issue was discovered in aws-iam-authenticator where an allow-listed
    IAM identity may be able to modify their username and escalate privileges.
published: 2022-07-13T00:00:41Z
last_modified: 2022-07-21T15:22:32Z
cves:
  - CVE-2022-2385
ghsas:
  - GHSA-pp3f-98qg-5g75
links:
    context:
      - https://github.com/advisories/GHSA-pp3f-98qg-5g75

```
