### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containous/traefik/api/v2: GHSA-6qq8-5wq3-86rp

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#549]
In GitHub Security Advisory [GHSA-6qq8-5wq3-86rp](https://github.com/advisories/GHSA-6qq8-5wq3-86rp), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/containous/traefik/api/v2](https://pkg.go.dev/github.com/containous/traefik/api/v2) | 2.2.8 | < 2.2.8 || [github.com/containous/traefik/api](https://pkg.go.dev/github.com/containous/traefik/api) | 1.7.26 | < 1.7.26 || [github.com/traefik/traefik/v2](https://pkg.go.dev/github.com/traefik/traefik/v2) | 2.3.0 | < 2.3.0 || [github.com/traefik/traefik](https://pkg.go.dev/github.com/traefik/traefik) | 1.7.26 | < 1.7.26 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/containous/traefik/api/v2
    versions:
      - fixed: 2.2.8
  - package: github.com/containous/traefik/api
    versions:
      - fixed: 1.7.26
  - package: github.com/traefik/traefik/v2
    versions:
      - fixed: 2.3.0
  - package: github.com/traefik/traefik
    versions:
      - fixed: 1.7.26
description: |-
    ## Summary

    There exists a potential open redirect vulnerability in Traefik's handling of the `X-Forwarded-Prefix` header. Active Exploitation of this issue is unlikely as it would require active header injection, however the Traefik team addressed this issue nonetheless to prevent abuse in e.g. cache poisoning scenarios.

    ## Details

    The Traefik API dashboard component doesn't validate that the value of the header `X-Forwarded-Prefix` is a site relative path and will redirect to any header provided URI.

    e.g.

    ```
    $ curl --header 'Host:traefik.localhost' --header 'X-Forwarded-Prefix:https://example.org' 'http://localhost:8081'
    <a href="https://example.org/dashboard/">Found</a>.`
    ```

    ### Impact
    A successful exploitation of an open redirect can be used to entice victims to disclose sensitive information.

    ### Workarounds

    By using the `headers` middleware, the request header `X-Forwarded-Prefix` value can be overridden by the value `.` (dot)

    - https://docs.traefik.io/v2.2/middlewares/headers/#customrequestheaders
    - https://docs.traefik.io/v1.7/basics/#custom-headers

    ### For more information

    If you have any questions or comments about this advisory, open an issue in [Traefik](https://github.com/containous/traefik/issues).

    ## Credit

    This issue was found by the GitHub Application Security Team and reported on behalf of the GHAS by the GitHub Security Lab Team.
published: 2022-02-11T23:19:21Z
last_modified: 2022-07-29T12:29:36Z
cves:
  - CVE-2020-15129
ghsas:
  - GHSA-6qq8-5wq3-86rp
links:
    context:
      - https://github.com/advisories/GHSA-6qq8-5wq3-86rp

```
