### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ethereum/go-ethereum: GHSA-5m8f-chrv-7rw5

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#555]
In GitHub Security Advisory [GHSA-5m8f-chrv-7rw5](https://github.com/advisories/GHSA-5m8f-chrv-7rw5), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/ethereum/go-ethereum](https://pkg.go.dev/github.com/ethereum/go-ethereum) |  | <= 1.10.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/ethereum/go-ethereum
    versions:
      - {}
description: 'Go-Ethereum 1.10.9 nodes crash (denial of service) after receiving a
    serial of messages and cannot be recovered. They will crash with "runtime error:
    invalid memory address or nil pointer dereference" and arise a SEGV signal.'
published: 2021-11-23T18:04:47Z
last_modified: 2021-11-24T19:38:54Z
cves:
  - CVE-2021-43668
ghsas:
  - GHSA-5m8f-chrv-7rw5
links:
    context:
      - https://github.com/advisories/GHSA-5m8f-chrv-7rw5

```
