### ISSUE TITLE
x/vulndb: potential Go vuln in gogs.io/gogs: GHSA-6vcc-v9vw-g2x5

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#562]
In GitHub Security Advisory [GHSA-6vcc-v9vw-g2x5](https://github.com/advisories/GHSA-6vcc-v9vw-g2x5), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [gogs.io/gogs](https://pkg.go.dev/gogs.io/gogs) | 0.12.9 | < 0.12.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: gogs.io/gogs
    versions:
      - fixed: 0.12.9
description: |
    ### Impact

    The malicious user is able to craft HTTP requests to access unauthorized Git directories. All installations with are affected.

    ### Patches

    Path cleaning has accommodated for Git HTTP endpoints. Users should upgrade to 0.12.9 or the latest 0.13.0+dev.

    ### Workarounds

    N/A

    ### References

    https://huntr.dev/bounties/22f9c074-cf60-4c67-b5c4-72fdf312609d/

    ### For more information

    If you have any questions or comments about this advisory, please post on #7002.
published: 2022-06-08T22:34:23Z
last_modified: 2022-06-17T19:20:57Z
cves:
  - CVE-2022-1993
ghsas:
  - GHSA-6vcc-v9vw-g2x5
links:
    context:
      - https://github.com/advisories/GHSA-6vcc-v9vw-g2x5

```
