### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/filebrowser/filebrowser: GHSA-72wf-hwcq-65h9

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#563]
In GitHub Security Advisory [GHSA-72wf-hwcq-65h9](https://github.com/advisories/GHSA-72wf-hwcq-65h9), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/filebrowser/filebrowser](https://pkg.go.dev/github.com/filebrowser/filebrowser) | 2.18.0 | < 2.18.0 || [github.com/filebrowser/filebrowser/v2](https://pkg.go.dev/github.com/filebrowser/filebrowser/v2) | 2.18.0 | < 2.18.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/filebrowser/filebrowser
    versions:
      - fixed: 2.18.0
  - package: github.com/filebrowser/filebrowser/v2
    versions:
      - fixed: 2.18.0
description: A Cross-Site Request Forgery (CSRF) vulnerability exists in Filebrowser
    < 2.18.0 that allows attackers to create a backdoor user with admin privilege
    and get access to the filesystem via a malicious HTML webpage that is sent to
    the victim.
published: 2022-02-05T00:00:31Z
last_modified: 2022-02-16T22:05:45Z
cves:
  - CVE-2021-46398
ghsas:
  - GHSA-72wf-hwcq-65h9
links:
    context:
      - https://github.com/advisories/GHSA-72wf-hwcq-65h9

```
