### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/open-falcon/falcon-plus: GHSA-76j4-gggq-7rg9

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#565]
In GitHub Security Advisory [GHSA-76j4-gggq-7rg9](https://github.com/advisories/GHSA-76j4-gggq-7rg9), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/open-falcon/falcon-plus](https://pkg.go.dev/github.com/open-falcon/falcon-plus) |  | <= 0.3.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/open-falcon/falcon-plus
    versions:
      - {}
description: Falcon-plus v0.3 was discovered to contain a SQL injection vulnerability
    via the parameter grpName in /config/service/host.go.
published: 2022-03-28T00:00:20Z
last_modified: 2022-04-12T21:59:37Z
cves:
  - CVE-2022-26245
ghsas:
  - GHSA-76j4-gggq-7rg9
links:
    context:
      - https://github.com/advisories/GHSA-76j4-gggq-7rg9

```
