### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/heroiclabs/nakama/v3: GHSA-8r94-4h3c-939f

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#567]
In GitHub Security Advisory [GHSA-8r94-4h3c-939f](https://github.com/advisories/GHSA-8r94-4h3c-939f), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/heroiclabs/nakama/v3](https://pkg.go.dev/github.com/heroiclabs/nakama/v3) |  | <= 3.12.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/heroiclabs/nakama/v3
    versions:
      - {}
description: Nakama Console does not enforce any limit for the number of unsuccessful
    login attempts.
published: 2022-07-06T00:00:26Z
last_modified: 2022-07-15T20:44:33Z
cves:
  - CVE-2022-2321
ghsas:
  - GHSA-8r94-4h3c-939f
links:
    context:
      - https://github.com/advisories/GHSA-8r94-4h3c-939f

```
