### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/beego/beego: GHSA-95f9-94vc-665h

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#569]
In GitHub Security Advisory [GHSA-95f9-94vc-665h](https://github.com/advisories/GHSA-95f9-94vc-665h), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/beego/beego](https://pkg.go.dev/github.com/beego/beego) | 2.0.4 | < 2.0.4 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/beego/beego
    versions:
      - fixed: 2.0.4
description: The leafInfo.match() function in Beego v2.0.3 and below uses path.join()
    to deal with wildcardvalues which can lead to cross directory risk.
published: 2022-07-06T00:00:28Z
last_modified: 2022-07-15T20:48:25Z
cves:
  - CVE-2022-31836
ghsas:
  - GHSA-95f9-94vc-665h
links:
    context:
      - https://github.com/advisories/GHSA-95f9-94vc-665h

```
