### ISSUE TITLE
x/vulndb: potential Go vuln in gogs.io/gogs: GHSA-994f-7g86-qr56

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#570]
In GitHub Security Advisory [GHSA-994f-7g86-qr56](https://github.com/advisories/GHSA-994f-7g86-qr56), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [gogs.io/gogs](https://pkg.go.dev/gogs.io/gogs) | 0.12.9 | < 0.12.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: gogs.io/gogs
    versions:
      - fixed: 0.12.9
description: |
    ### Impact

    The malicious user is able to delete and upload arbitrary file(s). All installations on Windows with [repository upload enabled (default)](https://github.com/gogs/gogs/blob/f36eeedbf89328ee70cc3a2e239f6314f9021f58/conf/app.ini#L127-L129) are affected.

    ### Patches

    Path cleaning has accommodated for Windows. Users should upgrade to 0.12.9 or the latest 0.13.0+dev.

    ### Workarounds

    N/A

    ### References

    https://huntr.dev/bounties/2e8cdc57-a9cf-46ae-9088-87f09e6c90ab/

    ### For more information

    If you have any questions or comments about this advisory, please post on #7001.
published: 2022-06-08T20:15:11Z
last_modified: 2022-06-17T19:21:01Z
cves:
  - CVE-2022-1992
ghsas:
  - GHSA-994f-7g86-qr56
links:
    context:
      - https://github.com/advisories/GHSA-994f-7g86-qr56

```
