### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/beego/beego: GHSA-28r6-jm5h-mrgg

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#572]
In GitHub Security Advisory [GHSA-28r6-jm5h-mrgg](https://github.com/advisories/GHSA-28r6-jm5h-mrgg), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/beego/beego](https://pkg.go.dev/github.com/beego/beego) |  | < 2.0.2 || [github.com/beego/beego/v2](https://pkg.go.dev/github.com/beego/beego/v2) | 2.0.2 | >= 2.0.0, < 2.0.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/beego/beego
    versions:
      - introduced: TODO (earliest fixed "", vuln range "< 2.0.2")
  - package: github.com/beego/beego/v2
    versions:
      - introduced: 2.0.0
        fixed: 2.0.2
description: An issue was discovered in the route lookup process in beego through
    2.0.1, allows attackers to bypass access control.
published: 2022-04-06T00:01:30Z
last_modified: 2022-04-12T21:53:25Z
cves:
  - CVE-2021-30080
ghsas:
  - GHSA-28r6-jm5h-mrgg
links:
    context:
      - https://github.com/advisories/GHSA-28r6-jm5h-mrgg

```
