### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/open-policy-agent/opa: GHSA-2m4x-4q9j-w97g

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#574]
In GitHub Security Advisory [GHSA-2m4x-4q9j-w97g](https://github.com/advisories/GHSA-2m4x-4q9j-w97g), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/open-policy-agent/opa](https://pkg.go.dev/github.com/open-policy-agent/opa) | 0.42.0 | < 0.42.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/open-policy-agent/opa
    versions:
      - fixed: 0.42.0
description: An issue in the AST parser (ast/compile.go) of Open Policy Agent v0.10.2
    allows attackers to cause a Denial of Service (DoS) via a crafted input.
published: 2022-07-01T00:01:03Z
last_modified: 2022-07-13T20:04:44Z
cves:
  - CVE-2022-33082
ghsas:
  - GHSA-2m4x-4q9j-w97g
links:
    context:
      - https://github.com/advisories/GHSA-2m4x-4q9j-w97g

```
