### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-3382-r9q8-4hfg

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#577]
In GitHub Security Advisory [GHSA-3382-r9q8-4hfg](https://github.com/advisories/GHSA-3382-r9q8-4hfg), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.2.6 | >= 1.2.0, < 1.2.6 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.1.12 | >= 1.1.0, < 1.1.12 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.17 | >= 1.0.0, < 1.0.17 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.2.0
        fixed: 1.2.6
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.1.0
        fixed: 1.1.12
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.0.0
        fixed: 1.0.17
description: HashiCorp Nomad and Nomad Enterprise 1.x before 1.0.17, 1.1.x before
    1.1.12, and 1.2.x before 1.2.6 is vulnerable to Allocation of Resources Without
    Limits or Throttling.
published: 2022-03-01T00:00:28Z
last_modified: 2022-04-01T20:11:34Z
cves:
  - CVE-2022-24685
ghsas:
  - GHSA-3382-r9q8-4hfg
links:
    context:
      - https://github.com/advisories/GHSA-3382-r9q8-4hfg

```
