### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/go-gitea/gitea: GHSA-36h2-95gj-w488

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#579]
In GitHub Security Advisory [GHSA-36h2-95gj-w488](https://github.com/advisories/GHSA-36h2-95gj-w488), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/go-gitea/gitea](https://pkg.go.dev/github.com/go-gitea/gitea) | 1.4.3 | < 1.4.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/go-gitea/gitea
    versions:
      - fixed: 1.4.3
description: Gitea before 1.4.3 is affected by URL Redirection to Untrusted Site ('Open
    Redirect') via internal URLs.
published: 2022-02-09T00:00:28Z
last_modified: 2022-02-15T00:18:11Z
cves:
  - CVE-2021-45328
ghsas:
  - GHSA-36h2-95gj-w488
links:
    context:
      - https://github.com/advisories/GHSA-36h2-95gj-w488

```
