### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ethereum/go-ethereum: GHSA-vmf7-hmh6-vv57

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#581]
In GitHub Security Advisory [GHSA-vmf7-hmh6-vv57](https://github.com/advisories/GHSA-vmf7-hmh6-vv57), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/ethereum/go-ethereum](https://pkg.go.dev/github.com/ethereum/go-ethereum) |  | <= 1.10.16 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/ethereum/go-ethereum
    versions:
      - {}
description: A design flaw in all versions of Go-Ethereum allows an attacker node
    to send 5120 pending transactions of a high gas price from one account that all
    fully spend the full balance of the account to a victim Geth node, which can purge
    all of pending transactions in a victim node's memory pool and then occupy the
    memory pool to prevent new transactions from entering the pool, resulting in a
    denial of service (DoS).
published: 2022-03-05T00:00:46Z
last_modified: 2022-03-18T20:07:00Z
cves:
  - CVE-2022-23328
ghsas:
  - GHSA-vmf7-hmh6-vv57
links:
    context:
      - https://github.com/advisories/GHSA-vmf7-hmh6-vv57

```
