### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ethereum/go-ethereum: GHSA-vrcc-g6vj-mh5w

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#582]
In GitHub Security Advisory [GHSA-vrcc-g6vj-mh5w](https://github.com/advisories/GHSA-vrcc-g6vj-mh5w), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/ethereum/go-ethereum](https://pkg.go.dev/github.com/ethereum/go-ethereum) |  | <= 1.10.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/ethereum/go-ethereum
    versions:
      - {}
description: Go-Ethereum v1.10.9 was discovered to contain an issue which allows attackers
    to cause a denial of service (DoS) via sending an excessive amount of messages
    to a node. This is caused by missing memory in the component /ethash/algorithm.go.
published: 2022-03-18T00:01:13Z
last_modified: 2022-03-30T20:05:14Z
cves:
  - CVE-2021-42219
ghsas:
  - GHSA-vrcc-g6vj-mh5w
links:
    context:
      - https://github.com/advisories/GHSA-vrcc-g6vj-mh5w

```
