### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/go-getter: GHSA-x24g-9w7v-vprh

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#586]
In GitHub Security Advisory [GHSA-x24g-9w7v-vprh](https://github.com/advisories/GHSA-x24g-9w7v-vprh), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/go-getter](https://pkg.go.dev/github.com/hashicorp/go-getter) | 2.1.0 | >= 2.0.0, < 2.1.0 || [github.com/hashicorp/go-getter](https://pkg.go.dev/github.com/hashicorp/go-getter) | 1.6.1 | < 1.6.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/go-getter
    versions:
      - introduced: 2.0.0
        fixed: 2.1.0
  - package: github.com/hashicorp/go-getter
    versions:
      - fixed: 1.6.1
description: HashiCorp go-getter before 2.0.2 allows Command Injection.
published: 2022-05-26T00:01:27Z
last_modified: 2022-06-01T21:20:55Z
cves:
  - CVE-2022-26945
ghsas:
  - GHSA-x24g-9w7v-vprh
links:
    context:
      - https://github.com/advisories/GHSA-x24g-9w7v-vprh

```
