### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/open-policy-agent/opa: GHSA-x7f3-62pm-9p38

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#587]
In GitHub Security Advisory [GHSA-x7f3-62pm-9p38](https://github.com/advisories/GHSA-x7f3-62pm-9p38), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/open-policy-agent/opa](https://pkg.go.dev/github.com/open-policy-agent/opa) | 0.40.0 | < 0.40.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/open-policy-agent/opa
    versions:
      - fixed: 0.40.0
description: An issue in the component ast/parser.go of Open Policy Agent v0.39.0
    causes the application to incorrectly interpret every expression, causing a Denial
    of Service (DoS) via triggering out-of-range memory access.
published: 2022-05-20T00:00:26Z
last_modified: 2022-05-31T23:27:53Z
cves:
  - CVE-2022-28946
ghsas:
  - GHSA-x7f3-62pm-9p38
links:
    context:
      - https://github.com/advisories/GHSA-x7f3-62pm-9p38

```
