### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/microcosm-cc/bluemonday: GHSA-x95h-979x-cf3j

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#588]
In GitHub Security Advisory [GHSA-x95h-979x-cf3j](https://github.com/advisories/GHSA-x95h-979x-cf3j), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/microcosm-cc/bluemonday](https://pkg.go.dev/github.com/microcosm-cc/bluemonday) | 1.0.16 | < 1.0.16 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/microcosm-cc/bluemonday
    versions:
      - fixed: 1.0.16
description: The bluemonday sanitizer before 1.0.16 for Go, and before 0.0.8 for Python
    (in pybluemonday), does not properly enforce policies associated with the SELECT,
    STYLE, and OPTION elements.
published: 2021-10-19T20:15:30Z
last_modified: 2021-10-25T20:07:10Z
cves:
  - CVE-2021-42576
ghsas:
  - GHSA-x95h-979x-cf3j
links:
    context:
      - https://github.com/advisories/GHSA-x95h-979x-cf3j

```
