### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/heroiclabs/nakama: GHSA-xv59-gc3r-rf92

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#589]
In GitHub Security Advisory [GHSA-xv59-gc3r-rf92](https://github.com/advisories/GHSA-xv59-gc3r-rf92), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/heroiclabs/nakama](https://pkg.go.dev/github.com/heroiclabs/nakama) |  | <= 3.12.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/heroiclabs/nakama
    versions:
      - {}
description: Old session tokens can be used to authenticate to the application and
    send authenticated requests.
published: 2022-07-06T00:00:30Z
last_modified: 2022-07-15T20:44:19Z
cves:
  - CVE-2022-2306
ghsas:
  - GHSA-xv59-gc3r-rf92
links:
    context:
      - https://github.com/advisories/GHSA-xv59-gc3r-rf92

```
