### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-c8x3-rg72-fwwg

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#591]
In GitHub Security Advisory [GHSA-c8x3-rg72-fwwg](https://github.com/advisories/GHSA-c8x3-rg72-fwwg), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.1.4 | >= 1.1.0, < 1.1.4 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.10 | < 1.0.10 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.1.0
        fixed: 1.1.4
  - package: github.com/hashicorp/nomad
    versions:
      - fixed: 1.0.10
description: HashiCorp Nomad and Nomad Enterprise Raft RPC layer allows non-server
    agents with a valid certificate signed by the same CA to access server-only functionality,
    enabling privilege escalation. Fixed in 1.0.10 and 1.1.4.
published: 2021-09-08T20:14:38Z
last_modified: 2021-09-14T18:46:55Z
cves:
  - CVE-2021-37218
ghsas:
  - GHSA-c8x3-rg72-fwwg
links:
    context:
      - https://github.com/advisories/GHSA-c8x3-rg72-fwwg

```
