### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/tidwall/gjson: GHSA-c9gm-7rfj-8w5h

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#592]
In GitHub Security Advisory [GHSA-c9gm-7rfj-8w5h](https://github.com/advisories/GHSA-c9gm-7rfj-8w5h), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/tidwall/gjson](https://pkg.go.dev/github.com/tidwall/gjson) | 1.9.3 | < 1.9.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/tidwall/gjson
    versions:
      - fixed: 1.9.3
description: GJSON <= 1.9.2 allows attackers to cause a redos via crafted JSON input.
published: 2022-05-25T00:00:38Z
last_modified: 2022-06-06T21:20:03Z
cves:
  - CVE-2021-42248
ghsas:
  - GHSA-c9gm-7rfj-8w5h
links:
    context:
      - https://github.com/advisories/GHSA-c9gm-7rfj-8w5h

```
