### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/fleetdm/fleet/v4: GHSA-ch68-7cf4-35vr

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#594]
In GitHub Security Advisory [GHSA-ch68-7cf4-35vr](https://github.com/advisories/GHSA-ch68-7cf4-35vr), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/fleetdm/fleet/v4](https://pkg.go.dev/github.com/fleetdm/fleet/v4) | 4.9.1 | < 4.9.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/fleetdm/fleet/v4
    versions:
      - fixed: 4.9.1
description: |-
    ### Impact

    This impacts deployments using SAML SSO in two specific cases:

    1. A malicious or compromised Service Provider (SP) could reuse the SAML response to log into Fleet as a user -- only if the user has an account with the same email in Fleet, _and_ the user signs into the malicious SP via SAML SSO from the same Identity Provider (IdP) configured with Fleet.
    2. A user with an account in Fleet could reuse a SAML response intended for another SP to log into Fleet. This is only a concern if the user is blocked from Fleet in the IdP, but continues to have an account in Fleet. If the user is blocked from the IdP entirely, this cannot be exploited.

    ### Patches
    Fleet 4.9.1 resolves this issue.

    ### Workarounds and good practices
    * Reduce the length of sessions on your IdP to reduce the window for malicious re-use.
    * Limit the amount of SAML Service Providers/Applications used by user accounts with access to Fleet.
    * When removing access to Fleet in the IdP, delete the Fleet user from Fleet as well.

    ### For more information
    If you have any questions or comments about this advisory:
    * Join us in the #fleet channel of [osquery Slack](https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw).
    * Email us at [security@fleetdm.com](mailto:security@fleetdm.com).
published: 2022-02-07T21:57:38Z
last_modified: 2022-04-19T19:03:21Z
cves:
  - CVE-2022-23600
ghsas:
  - GHSA-ch68-7cf4-35vr
links:
    context:
      - https://github.com/advisories/GHSA-ch68-7cf4-35vr

```
