### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/mindoc-org/mindoc: GHSA-f7ff-xf87-f22q

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#596]
In GitHub Security Advisory [GHSA-f7ff-xf87-f22q](https://github.com/advisories/GHSA-f7ff-xf87-f22q), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/mindoc-org/mindoc](https://pkg.go.dev/github.com/mindoc-org/mindoc) |  | <= 2.1-beta.5 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/mindoc-org/mindoc
    versions:
      - {}
description: An arbitrary file upload vulnerability in Mindoc v2.1-beta.5 allows attackers
    to execute arbitrary commands via a crafted Zip file.
published: 2022-05-27T00:00:29Z
last_modified: 2022-06-09T22:54:49Z
cves:
  - CVE-2022-29637
ghsas:
  - GHSA-f7ff-xf87-f22q
links:
    context:
      - https://github.com/advisories/GHSA-f7ff-xf87-f22q

```
