### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/beego/beego: GHSA-ffjp-66mx-3qpj

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#598]
In GitHub Security Advisory [GHSA-ffjp-66mx-3qpj](https://github.com/advisories/GHSA-ffjp-66mx-3qpj), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/beego/beego](https://pkg.go.dev/github.com/beego/beego) |  | < 2.0.2 || [github.com/beego/beego/v2](https://pkg.go.dev/github.com/beego/beego/v2) | 2.0.2 | >= 2.0.0, < 2.0.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/beego/beego
    versions:
      - introduced: TODO (earliest fixed "", vuln range "< 2.0.2")
  - package: github.com/beego/beego/v2
    versions:
      - introduced: 2.0.0
        fixed: 2.0.2
description: An issue was discovered in file profile.go. The MemProf and GetCPUProfile
    functions do not correctly check whether the created file exists. As a result
    attackers can launch attacks symlink attacks locally. Attackers can use this vulnerability
    to escalate privileges.
published: 2022-04-06T00:01:30Z
last_modified: 2022-04-19T14:07:24Z
cves:
  - CVE-2021-27116
ghsas:
  - GHSA-ffjp-66mx-3qpj
links:
    context:
      - https://github.com/advisories/GHSA-ffjp-66mx-3qpj

```
