### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/mattermost/mattermost-server/v6: GHSA-fxwj-v664-wv5g

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#599]
In GitHub Security Advisory [GHSA-fxwj-v664-wv5g](https://github.com/advisories/GHSA-fxwj-v664-wv5g), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/mattermost/mattermost-server/v6](https://pkg.go.dev/github.com/mattermost/mattermost-server/v6) | 6.5.0 | < 6.5.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/mattermost/mattermost-server/v6
    versions:
      - fixed: 6.5.0
description: Mattermost 6.4.x and earlier fails to properly invalidate pending email
    invitations when the action is performed from the system console, which allows
    accidentally invited users to join the workspace and access information from the
    public teams and channels.
published: 2022-04-20T00:00:30Z
last_modified: 2022-04-28T19:49:34Z
cves:
  - CVE-2022-1385
ghsas:
  - GHSA-fxwj-v664-wv5g
links:
    context:
      - https://github.com/advisories/GHSA-fxwj-v664-wv5g

```
