### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-gwmc-6795-qghj

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#600]
In GitHub Security Advisory [GHSA-gwmc-6795-qghj](https://github.com/advisories/GHSA-gwmc-6795-qghj), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.2.6 | >= 1.2.0, < 1.2.6 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.1.12 | >= 1.1.0, < 1.1.12 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.18 | >= 0.3.0, < 1.0.18 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.2.0
        fixed: 1.2.6
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.1.0
        fixed: 1.1.12
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 0.3.0
        fixed: 1.0.18
description: HashiCorp Nomad and Nomad Enterprise 0.3.0 through 1.0.17, 1.1.11, and
    1.2.5 artifact download functionality has a race condition such that the Nomad
    client agent could download the wrong artifact into the wrong destination. This
    issue is fixed in 1.0.18, 1.1.12, and 1.2.6.
published: 2022-02-15T00:02:46Z
last_modified: 2022-03-28T15:24:37Z
cves:
  - CVE-2022-24686
ghsas:
  - GHSA-gwmc-6795-qghj
links:
    context:
      - https://github.com/advisories/GHSA-gwmc-6795-qghj

```
