### ISSUE TITLE
x/vulndb: potential Go vuln in gopkg.in/yaml.v3: GHSA-hp87-p4gw-j4gq

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#603]
In GitHub Security Advisory [GHSA-hp87-p4gw-j4gq](https://github.com/advisories/GHSA-hp87-p4gw-j4gq), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [gopkg.in/yaml.v3](https://pkg.go.dev/gopkg.in/yaml.v3) | 3.0.0 | = 3.0.0-20130425192426-8171f560dedc |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: gopkg.in/yaml.v3
    versions:
      - introduced: TODO (earliest fixed "3.0.0", vuln range "= 3.0.0-20130425192426-8171f560dedc")
description: An issue in the Unmarshal function in Go-Yaml v3 causes the program to
    crash when attempting to deserialize invalid input.
published: 2022-05-20T00:00:17Z
last_modified: 2022-06-03T22:23:20Z
cves:
  - CVE-2022-28948
ghsas:
  - GHSA-hp87-p4gw-j4gq
links:
    context:
      - https://github.com/advisories/GHSA-hp87-p4gw-j4gq

```
