### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/Xhofe/alist: GHSA-jpj5-hg26-6jgc

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#607]
In GitHub Security Advisory [GHSA-jpj5-hg26-6jgc](https://github.com/advisories/GHSA-jpj5-hg26-6jgc), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/Xhofe/alist](https://pkg.go.dev/github.com/Xhofe/alist) | 2.1.1 | >= 2.0.10, < 2.1.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/Xhofe/alist
    versions:
      - introduced: 2.0.10
        fixed: 2.1.1
description: Alist versions 2.0.10 through 2.1.0 were discovered to contain a cross-site
    scripting (XSS) vulnerability via /i/:data/ipa.plist. This issue was fixed in
    version 2.1.1.
published: 2022-03-13T00:00:54Z
last_modified: 2022-03-23T15:50:07Z
cves:
  - CVE-2022-26533
ghsas:
  - GHSA-jpj5-hg26-6jgc
links:
    context:
      - https://github.com/advisories/GHSA-jpj5-hg26-6jgc

```
