### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/cri-o/cri-o: GHSA-jqmc-79gx-7g8p

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#608]
In GitHub Security Advisory [GHSA-jqmc-79gx-7g8p](https://github.com/advisories/GHSA-jqmc-79gx-7g8p), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/cri-o/cri-o](https://pkg.go.dev/github.com/cri-o/cri-o) | 1.23.1 | < 1.23.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/cri-o/cri-o
    versions:
      - fixed: 1.23.1
description: An incorrect sysctls validation vulnerability was found in CRI-O 1.18
    and earlier. The sysctls from the list of "safe" sysctls specified for the cluster
    will be applied to the host if an attacker is able to create a pod with a hostIPC
    and hostNetwork kernel namespace.
published: 2022-02-11T00:00:54Z
last_modified: 2022-02-23T22:00:52Z
cves:
  - CVE-2022-0532
ghsas:
  - GHSA-jqmc-79gx-7g8p
links:
    context:
      - https://github.com/advisories/GHSA-jqmc-79gx-7g8p

```
