### ISSUE TITLE
x/vulndb: potential Go vuln in code.gitea.io/gitea: GHSA-ph3w-2843-72mx

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#612]
In GitHub Security Advisory [GHSA-ph3w-2843-72mx](https://github.com/advisories/GHSA-ph3w-2843-72mx), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [code.gitea.io/gitea](https://pkg.go.dev/code.gitea.io/gitea) | 1.16.9 | < 1.16.9 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: code.gitea.io/gitea
    versions:
      - fixed: 1.16.9
description: Cross-site Scripting (XSS) - Stored in GitHub repository go-gitea/gitea
    prior to 1.16.9 via unfiltered pdfs
published: 2022-05-30T00:00:30Z
last_modified: 2022-06-02T20:36:41Z
cves:
  - CVE-2022-1928
ghsas:
  - GHSA-ph3w-2843-72mx
links:
    context:
      - https://github.com/advisories/GHSA-ph3w-2843-72mx

```
