### ISSUE TITLE
x/vulndb: potential Go vuln in k8s.io/ingress-nginx: GHSA-pvmg-xgmx-9mxh

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#613]
In GitHub Security Advisory [GHSA-pvmg-xgmx-9mxh](https://github.com/advisories/GHSA-pvmg-xgmx-9mxh), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [k8s.io/ingress-nginx](https://pkg.go.dev/k8s.io/ingress-nginx) | 1.2.0 | < 1.2.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: k8s.io/ingress-nginx
    versions:
      - fixed: 1.2.0
description: A security issue was discovered in ingress-nginx where a user that can
    create or update ingress objects can use the spec.rules[].http.paths[].path field
    of an Ingress object (in the networking.k8s.io or extensions API group) to obtain
    the credentials of the ingress-nginx controller. In the default configuration,
    that credential has access to all secrets in the cluster.
published: 2022-05-07T00:00:49Z
last_modified: 2022-06-15T19:46:00Z
cves:
  - CVE-2021-25745
ghsas:
  - GHSA-pvmg-xgmx-9mxh
links:
    context:
      - https://github.com/advisories/GHSA-pvmg-xgmx-9mxh

```
