### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ethereum/go-ethereum: GHSA-pvx3-gm3c-gmpr

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#614]
In GitHub Security Advisory [GHSA-pvx3-gm3c-gmpr](https://github.com/advisories/GHSA-pvx3-gm3c-gmpr), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/ethereum/go-ethereum](https://pkg.go.dev/github.com/ethereum/go-ethereum) |  | <= 1.10.12 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/ethereum/go-ethereum
    versions:
      - {}
description: A design flaw in Go-Ethereum 1.10.12 and older versions allows an attacker
    node to send 5120 future transactions with a high gas price in one message, which
    can purge all of pending transactions in a victim node's memory pool, causing
    a denial of service (DoS).
published: 2022-03-05T00:00:46Z
last_modified: 2022-03-18T20:06:44Z
cves:
  - CVE-2022-23327
ghsas:
  - GHSA-pvx3-gm3c-gmpr
links:
    context:
      - https://github.com/advisories/GHSA-pvx3-gm3c-gmpr

```
