### ISSUE TITLE
x/vulndb: potential Go vuln in k8s.io/kubernetes: GHSA-qh36-44jv-c8xj

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#617]
In GitHub Security Advisory [GHSA-qh36-44jv-c8xj](https://github.com/advisories/GHSA-qh36-44jv-c8xj), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [k8s.io/kubernetes](https://pkg.go.dev/k8s.io/kubernetes) | 1.18.19 | < 1.18.19 || [k8s.io/kubernetes](https://pkg.go.dev/k8s.io/kubernetes) | 1.19.11 | >= 1.19.0, < 1.19.11 || [k8s.io/kubernetes](https://pkg.go.dev/k8s.io/kubernetes) | 1.20.7 | >= 1.20.0, < 1.20.7 || [k8s.io/kubernetes](https://pkg.go.dev/k8s.io/kubernetes) | 1.21.1 | >= 1.21.0, < 1.21.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: k8s.io/kubernetes
    versions:
      - fixed: 1.18.19
  - package: k8s.io/kubernetes
    versions:
      - introduced: 1.19.0
        fixed: 1.19.11
  - package: k8s.io/kubernetes
    versions:
      - introduced: 1.20.0
        fixed: 1.20.7
  - package: k8s.io/kubernetes
    versions:
      - introduced: 1.21.0
        fixed: 1.21.1
description: As mitigations to a report from 2019 and CVE-2020-8555, Kubernetes attempts
    to prevent proxied connections from accessing link-local or localhost networks
    when making user-driven connections to Services, Pods, Nodes, or StorageClass
    service providers. As part of this mitigation Kubernetes does a DNS name resolution
    check and validates that response IPs are not in the link-local (169.254.0.0/16)
    or localhost (127.0.0.0/8) range. Kubernetes then performs a second DNS resolution
    without validation for the actual connection. If a non-standard DNS server returns
    different non-cached responses, a user may be able to bypass the proxy IP restriction
    and access private networks on the control plane.
published: 2022-02-02T00:01:58Z
last_modified: 2022-03-30T21:11:44Z
cves:
  - CVE-2020-8562
ghsas:
  - GHSA-qh36-44jv-c8xj
links:
    context:
      - https://github.com/advisories/GHSA-qh36-44jv-c8xj

```
