### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/emicklei/go-restful/v2: GHSA-r48q-9g5r-8q2h

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#619]
In GitHub Security Advisory [GHSA-r48q-9g5r-8q2h](https://github.com/advisories/GHSA-r48q-9g5r-8q2h), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/emicklei/go-restful/v2](https://pkg.go.dev/github.com/emicklei/go-restful/v2) | 2.16.0 | < 2.16.0 || [github.com/emicklei/go-restful/v3](https://pkg.go.dev/github.com/emicklei/go-restful/v3) | 3.8.0 | >= 3.0.0, < 3.8.0 || [github.com/emicklei/go-restful](https://pkg.go.dev/github.com/emicklei/go-restful) | 3.8.0 | <= 1.1.13 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/emicklei/go-restful/v2
    versions:
      - fixed: 2.16.0
  - package: github.com/emicklei/go-restful/v3
    versions:
      - introduced: 3.0.0
        fixed: 3.8.0
  - package: github.com/emicklei/go-restful
    versions:
      - introduced: TODO (earliest fixed "3.8.0", vuln range "<= 1.1.13")
description: Authorization Bypass Through User-Controlled Key in GitHub repository
    emicklei/go-restful prior to v3.8.0.
published: 2022-06-09T00:00:23Z
last_modified: 2022-07-18T19:59:00Z
cves:
  - CVE-2022-1996
ghsas:
  - GHSA-r48q-9g5r-8q2h
links:
    context:
      - https://github.com/advisories/GHSA-r48q-9g5r-8q2h

```
