### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubernetes/kube-state-metrics: GHSA-2v6x-frw8-7r7f

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#621]
In GitHub Security Advisory [GHSA-2v6x-frw8-7r7f](https://github.com/advisories/GHSA-2v6x-frw8-7r7f), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/kubernetes/kube-state-metrics](https://pkg.go.dev/github.com/kubernetes/kube-state-metrics) | 1.7.2 | >= 1.7.0, < 1.7.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/kubernetes/kube-state-metrics
    versions:
      - introduced: 1.7.0
        fixed: 1.7.2
description: A security issue was discovered in kube-state-metrics 1.7.x before 1.7.2.
    An experimental feature was added to v1.7.0 and v1.7.1 that enabled annotations
    to be exposed as metrics. By default, kube-state-metrics metrics only expose metadata
    about Secrets. However, a combination of the default kubectl behavior and this
    new feature can cause the entire secret content to end up in metric labels, thus
    inadvertently exposing the secret content in metrics.
published: 2021-05-18T15:38:54Z
last_modified: 2021-05-18T15:38:54Z
cves:
  - CVE-2019-17110
ghsas:
  - GHSA-2v6x-frw8-7r7f
links:
    context:
      - https://github.com/advisories/GHSA-2v6x-frw8-7r7f

```
