### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-35qp-xq9f-2rjx

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#622]
In GitHub Security Advisory [GHSA-35qp-xq9f-2rjx](https://github.com/advisories/GHSA-35qp-xq9f-2rjx), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 0.12.10 | < 0.12.10 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.3 | >= 1.0.0, < 1.0.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - fixed: 0.12.10
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.0.0
        fixed: 1.0.3
description: HashiCorp Nomad and Nomad Enterprise up to 0.12.9 exec and java task
    drivers can access processes associated with other tasks on the same node. Fixed
    in 0.12.10, and 1.0.3.
published: 2021-06-24T20:28:28Z
last_modified: 2021-06-24T20:28:28Z
cves:
  - CVE-2021-3283
ghsas:
  - GHSA-35qp-xq9f-2rjx
links:
    context:
      - https://github.com/advisories/GHSA-35qp-xq9f-2rjx

```
