### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/login: GHSA-3f8r-4qwm-r7jf

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#624]
In GitHub Security Advisory [GHSA-3f8r-4qwm-r7jf](https://github.com/advisories/GHSA-3f8r-4qwm-r7jf), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/login](https://pkg.go.dev/github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/login) | 3.0.2-RC1 | >= 3.0.0, <= 3.0.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/apache/trafficcontrol/traffic_ops/traffic_ops_golang/login
    versions:
      - introduced: TODO (earliest fixed "3.0.2-RC1", vuln range ">= 3.0.0, <= 3.0.1")
description: Improper authentication is possible in Apache Traffic Control versions
    3.0.0 and 3.0.1 if LDAP is enabled for login in the Traffic Ops API component.
    Given a username for a user that can be authenticated via LDAP, it is possible
    to improperly authenticate as that user without that user's correct password.
published: 2021-05-18T15:39:16Z
last_modified: 2021-10-13T17:25:42Z
cves:
  - CVE-2019-12405
ghsas:
  - GHSA-3f8r-4qwm-r7jf
links:
    context:
      - https://github.com/advisories/GHSA-3f8r-4qwm-r7jf

```
