### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/docker/docker: GHSA-44gg-pmqr-4669

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#625]
In GitHub Security Advisory [GHSA-44gg-pmqr-4669](https://github.com/advisories/GHSA-44gg-pmqr-4669), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/docker/docker](https://pkg.go.dev/github.com/docker/docker) | 1.3.2 | >= 1.3.0, < 1.3.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/docker/docker
    versions:
      - introduced: 1.3.0
        fixed: 1.3.2
description: Docker 1.3.0 through 1.3.1 allows remote attackers to modify the default
    run profile of image containers and possibly bypass the container by applying
    unspecified security options to an image.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:38:18Z
cves:
  - CVE-2014-6408
ghsas:
  - GHSA-44gg-pmqr-4669
links:
    context:
      - https://github.com/advisories/GHSA-44gg-pmqr-4669

```
