### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kiali/kiali: GHSA-465w-gg5p-85c9

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#626]
In GitHub Security Advisory [GHSA-465w-gg5p-85c9](https://github.com/advisories/GHSA-465w-gg5p-85c9), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/kiali/kiali](https://pkg.go.dev/github.com/kiali/kiali) | 1.15.1 | >= 0.4.0, < 1.15.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/kiali/kiali
    versions:
      - introduced: 0.4.0
        fixed: 1.15.1
description: An insufficient JWT validation vulnerability was found in Kiali versions
    0.4.0 to 1.15.0 and was fixed in Kiali version 1.15.1, wherein a remote attacker
    could abuse this flaw by stealing a valid JWT cookie and using that to spoof a
    user session, possibly gaining privileges to view and alter the Istio configuration.
published: 2021-05-18T21:09:01Z
last_modified: 2021-05-18T21:09:01Z
cves:
  - CVE-2020-1762
ghsas:
  - GHSA-465w-gg5p-85c9
links:
    context:
      - https://github.com/advisories/GHSA-465w-gg5p-85c9

```
