### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/concourse/concourse/atc/db: GHSA-4fqx-74rv-638w

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#627]
In GitHub Security Advisory [GHSA-4fqx-74rv-638w](https://github.com/advisories/GHSA-4fqx-74rv-638w), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/concourse/concourse/atc/db](https://pkg.go.dev/github.com/concourse/concourse/atc/db) | 5.0.1 | < 5.0.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/concourse/concourse/atc/db
    versions:
      - fixed: 5.0.1
description: Pivotal Concourse version 5.0.0, contains an API that is vulnerable to
    SQL injection. An Concourse resource can craft a version identifier that can carry
    a SQL injection payload to the Concourse server, allowing the attacker to read
    privileged data.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:10:26Z
cves:
  - CVE-2019-3792
ghsas:
  - GHSA-4fqx-74rv-638w
links:
    context:
      - https://github.com/advisories/GHSA-4fqx-74rv-638w

```
