### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/ovn-org/ovn-kubernetes: GHSA-57v4-m9jx-mh8r

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#628]
In GitHub Security Advisory [GHSA-57v4-m9jx-mh8r](https://github.com/advisories/GHSA-57v4-m9jx-mh8r), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/ovn-org/ovn-kubernetes](https://pkg.go.dev/github.com/ovn-org/ovn-kubernetes) |  | <= 0.3.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/ovn-org/ovn-kubernetes
    versions:
      - {}
description: A vulnerability was found in OVN Kubernetes in versions up to and including
    0.3.0 where the Egress Firewall does not reliably apply firewall rules when there
    is multiple DNS rules. It could lead to potentially lose of confidentiality, integrity
    or availability of a service.
published: 2021-06-08T23:05:19Z
last_modified: 2022-03-15T21:36:54Z
cves:
  - CVE-2021-3499
ghsas:
  - GHSA-57v4-m9jx-mh8r
links:
    context:
      - https://github.com/advisories/GHSA-57v4-m9jx-mh8r

```
