### ISSUE TITLE
x/vulndb: potential Go vuln in sigs.k8s.io/secrets-store-csi-driver/pkg/secrets-store: GHSA-5cgx-vhfp-6cf9

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#629]
In GitHub Security Advisory [GHSA-5cgx-vhfp-6cf9](https://github.com/advisories/GHSA-5cgx-vhfp-6cf9), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [sigs.k8s.io/secrets-store-csi-driver/pkg/secrets-store](https://pkg.go.dev/sigs.k8s.io/secrets-store-csi-driver/pkg/secrets-store) | 0.0.17 | >= 0.0.15, < 0.0.17 || [sigs.k8s.io/secrets-store-csi-driver](https://pkg.go.dev/sigs.k8s.io/secrets-store-csi-driver) | 0.0.17 | >= 0.0.15, < 0.0.17 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: sigs.k8s.io/secrets-store-csi-driver/pkg/secrets-store
    versions:
      - introduced: 0.0.15
        fixed: 0.0.17
  - package: sigs.k8s.io/secrets-store-csi-driver
    versions:
      - introduced: 0.0.15
        fixed: 0.0.17
description: Kubernetes Secrets Store CSI Driver versions v0.0.15 and v0.0.16 allow
    an attacker who can modify a SecretProviderClassPodStatus/Status resource the
    ability to write content to the host filesystem and sync file contents to Kubernetes
    Secrets. This includes paths under var/lib/kubelet/pods that contain other Kubernetes
    Secrets.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-20T20:56:50Z
cves:
  - CVE-2020-8568
ghsas:
  - GHSA-5cgx-vhfp-6cf9
links:
    context:
      - https://github.com/advisories/GHSA-5cgx-vhfp-6cf9

```
