### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/docker/docker: GHSA-5qgp-p5jc-w2rm

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#630]
In GitHub Security Advisory [GHSA-5qgp-p5jc-w2rm](https://github.com/advisories/GHSA-5qgp-p5jc-w2rm), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/docker/docker](https://pkg.go.dev/github.com/docker/docker) | 1.3.2 | < 1.3.2 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/docker/docker
    versions:
      - fixed: 1.3.2
description: Docker before 1.3.2 allows remote attackers to write to arbitrary files
    and execute arbitrary code via a (1) symlink or (2) hard link attack in an image
    archive in a (a) pull or (b) load operation.
published: 2022-02-15T00:41:12Z
last_modified: 2022-02-15T00:41:12Z
cves:
  - CVE-2014-6407
ghsas:
  - GHSA-5qgp-p5jc-w2rm
links:
    context:
      - https://github.com/advisories/GHSA-5qgp-p5jc-w2rm

```
