### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kiali/kiali/config: GHSA-64rh-r86q-75ff

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#631]
In GitHub Security Advisory [GHSA-64rh-r86q-75ff](https://github.com/advisories/GHSA-64rh-r86q-75ff), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/kiali/kiali/config](https://pkg.go.dev/github.com/kiali/kiali/config) | 1.16.0-snapshot.1 | <= 1.16.0-snapshot.0 || [github.com/kiali/kiali](https://pkg.go.dev/github.com/kiali/kiali) | 1.15.1 | < 1.15.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/kiali/kiali/config
    versions:
      - introduced: TODO (earliest fixed "1.16.0-snapshot.1", vuln range "<= 1.16.0-snapshot.0")
  - package: github.com/kiali/kiali
    versions:
      - fixed: 1.15.1
description: A hard-coded cryptographic key vulnerability in the default configuration
    file was found in Kiali, all versions prior to 1.15.1. A remote attacker could
    abuse this flaw by creating their own JWT signed tokens and bypass Kiali authentication
    mechanisms, possibly gaining privileges to view and alter the Istio configuration.
published: 2021-05-18T18:28:59Z
last_modified: 2021-05-18T18:28:59Z
cves:
  - CVE-2020-1764
ghsas:
  - GHSA-64rh-r86q-75ff
links:
    context:
      - https://github.com/advisories/GHSA-64rh-r86q-75ff

```
