### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/vault: GHSA-6239-28c2-9mrm

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#632]
In GitHub Security Advisory [GHSA-6239-28c2-9mrm](https://github.com/advisories/GHSA-6239-28c2-9mrm), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/vault](https://pkg.go.dev/github.com/hashicorp/vault) | 1.7.4 | >= 1.7.0, < 1.7.4 || [github.com/hashicorp/vault](https://pkg.go.dev/github.com/hashicorp/vault) | 1.6.6 | < 1.6.6 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/vault
    versions:
      - introduced: 1.7.0
        fixed: 1.7.4
  - package: github.com/hashicorp/vault
    versions:
      - fixed: 1.6.6
description: HashiCorp Vault and Vault Enterprise’s UI erroneously cached and exposed
    user-viewed secrets between sessions in a single shared browser. Fixed in 1.8.0
    and pending 1.7.4 / 1.6.6 releases.
published: 2021-08-30T17:22:38Z
last_modified: 2021-10-21T14:19:31Z
cves:
  - CVE-2021-38554
ghsas:
  - GHSA-6239-28c2-9mrm
links:
    context:
      - https://github.com/advisories/GHSA-6239-28c2-9mrm

```
