### ISSUE TITLE
x/vulndb: potential Go vuln in istio.io/istio/pkg/log: GHSA-6g5f-f5pm-mjrg

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#633]
In GitHub Security Advisory [GHSA-6g5f-f5pm-mjrg](https://github.com/advisories/GHSA-6g5f-f5pm-mjrg), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [istio.io/istio/pkg/log](https://pkg.go.dev/istio.io/istio/pkg/log) |  | >= 1.1.0, < 1.1.7 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: istio.io/istio/pkg/log
    versions:
      - introduced: TODO (earliest fixed "", vuln range ">= 1.1.0, < 1.1.7")
description: Istio 1.1.x through 1.1.6 has Incorrect Access Control.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-20T21:05:19Z
cves:
  - CVE-2019-12243
ghsas:
  - GHSA-6g5f-f5pm-mjrg
links:
    context:
      - https://github.com/advisories/GHSA-6g5f-f5pm-mjrg

```
