### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad/client/allocrunner/taskrunner/template: GHSA-6hv3-7c34-4hx8

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#634]
In GitHub Security Advisory [GHSA-6hv3-7c34-4hx8](https://github.com/advisories/GHSA-6hv3-7c34-4hx8), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad/client/allocrunner/taskrunner/template](https://pkg.go.dev/github.com/hashicorp/nomad/client/allocrunner/taskrunner/template) | 0.9.5 | < 0.9.5 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad/client/allocrunner/taskrunner/template
    versions:
      - fixed: 0.9.5
description: In Nomad before version 0.9.5, when rendering a task template, all environment
    variables were available to the rendering task.  As a fix, only task environment
    variables are used.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:02:18Z
cves:
  - CVE-2019-14802
ghsas:
  - GHSA-6hv3-7c34-4hx8
links:
    context:
      - https://github.com/advisories/GHSA-6hv3-7c34-4hx8

```
