### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kongchuanhujiao/server: GHSA-8wrg-m8vm-5fvj

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#637]
In GitHub Security Advisory [GHSA-8wrg-m8vm-5fvj](https://github.com/advisories/GHSA-8wrg-m8vm-5fvj), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/kongchuanhujiao/server](https://pkg.go.dev/github.com/kongchuanhujiao/server) | 1.3.21 | < 1.3.21 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/kongchuanhujiao/server
    versions:
      - fixed: 1.3.21
description: |-
    ### Impact

    Authentication Bypass by Primary Weakness (CWE-305)

    Commit:

    https://github.com/kongchuanhujiao/server/commit/9a125624f219e496bdf4b07b404816d5a309bdc1

    ALL Users  is impacted.

    ### Patches

    Yes, PLEASE UPGRADE TO v1.3.21-beta.d0ffc0a6
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-19T19:02:51Z
cves:
  - CVE-2021-21403
ghsas:
  - GHSA-8wrg-m8vm-5fvj
links:
    context:
      - https://github.com/advisories/GHSA-8wrg-m8vm-5fvj

```
