### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/concourse/concourse/skymarshal/skyserver: GHSA-9689-rx4v-cqgc

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#639]
In GitHub Security Advisory [GHSA-9689-rx4v-cqgc](https://github.com/advisories/GHSA-9689-rx4v-cqgc), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/concourse/concourse/skymarshal/skyserver](https://pkg.go.dev/github.com/concourse/concourse/skymarshal/skyserver) | 5.8.1 | >= 5.6.0, < 5.8.1 || [github.com/concourse/concourse/skymarshal/skyserver](https://pkg.go.dev/github.com/concourse/concourse/skymarshal/skyserver) | 5.5.10 | >= 5.3.0, < 5.5.10 || [github.com/concourse/concourse/skymarshal/skyserver](https://pkg.go.dev/github.com/concourse/concourse/skymarshal/skyserver) | 5.2.8 | < 5.2.8 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/concourse/concourse/skymarshal/skyserver
    versions:
      - introduced: 5.6.0
        fixed: 5.8.1
  - package: github.com/concourse/concourse/skymarshal/skyserver
    versions:
      - introduced: 5.3.0
        fixed: 5.5.10
  - package: github.com/concourse/concourse/skymarshal/skyserver
    versions:
      - fixed: 5.2.8
description: Pivotal Concourse Release, versions 4.x prior to 4.2.2, login flow allows
    redirects to untrusted websites. A remote unauthenticated attacker could convince
    a user to click on a link using the oAuth redirect link with an untrusted website
    and gain access to that user's access token in Concourse.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:10:05Z
cves:
  - CVE-2018-15798
ghsas:
  - GHSA-9689-rx4v-cqgc
links:
    context:
      - https://github.com/advisories/GHSA-9689-rx4v-cqgc

```
