### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/docker/docker: GHSA-997c-fj8j-rq5h

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#640]
In GitHub Security Advisory [GHSA-997c-fj8j-rq5h](https://github.com/advisories/GHSA-997c-fj8j-rq5h), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/docker/docker](https://pkg.go.dev/github.com/docker/docker) | 1.3.3 | < 1.3.3 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/docker/docker
    versions:
      - fixed: 1.3.3
description: Docker 1.3.2 allows remote attackers to execute arbitrary code with root
    privileges via a crafted (1) image or (2) build in a Dockerfile in an LZMA (.xz)
    archive, related to the chroot for archive extraction.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:01:45Z
cves:
  - CVE-2014-9357
ghsas:
  - GHSA-997c-fj8j-rq5h
links:
    context:
      - https://github.com/advisories/GHSA-997c-fj8j-rq5h

```
