### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/elastic/beats/packetbeat/protos/pgsql: GHSA-9q3g-m353-cp4p

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#643]
In GitHub Security Advisory [GHSA-9q3g-m353-cp4p](https://github.com/advisories/GHSA-9q3g-m353-cp4p), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/elastic/beats/packetbeat/protos/pgsql](https://pkg.go.dev/github.com/elastic/beats/packetbeat/protos/pgsql) | 6.5.4 | < 6.5.4 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/elastic/beats/packetbeat/protos/pgsql
    versions:
      - fixed: 6.5.4
description: Packetbeat versions prior to 5.6.4 are affected by a denial of service
    flaw in the PostgreSQL protocol handler. If Packetbeat is listening for PostgreSQL
    traffic and a user is able to send arbitrary network traffic to the monitored
    port, the attacker could prevent Packetbeat from properly logging other PostgreSQL
    traffic.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:39:26Z
cves:
  - CVE-2017-11480
ghsas:
  - GHSA-9q3g-m353-cp4p
links:
    context:
      - https://github.com/advisories/GHSA-9q3g-m353-cp4p

```
