### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/docker/docker: GHSA-g7v2-2qxx-wjrw

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#649]
In GitHub Security Advisory [GHSA-g7v2-2qxx-wjrw](https://github.com/advisories/GHSA-g7v2-2qxx-wjrw), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/docker/docker](https://pkg.go.dev/github.com/docker/docker) | 1.6.1 | < 1.6.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/docker/docker
    versions:
      - fixed: 1.6.1
description: Libcontainer and Docker Engine before 1.6.1 opens the file-descriptor
    passed to the pid-1 process before performing the chroot, which allows local users
    to gain privileges via a symlink attack in an image.
published: 2022-02-15T01:18:02Z
last_modified: 2022-02-15T01:18:02Z
cves:
  - CVE-2015-3627
ghsas:
  - GHSA-g7v2-2qxx-wjrw
links:
    context:
      - https://github.com/advisories/GHSA-g7v2-2qxx-wjrw

```
