### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/gphper/ginadmin: GHSA-5824-6jfv-xr3r

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#653]
In GitHub Security Advisory [GHSA-5824-6jfv-xr3r](https://github.com/advisories/GHSA-5824-6jfv-xr3r), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/gphper/ginadmin](https://pkg.go.dev/github.com/gphper/ginadmin) |  | <= 0.1.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/gphper/ginadmin
    versions:
      - {}
description: In ginadmin through 05-10-2022, the incoming path value is not filtered,
    resulting in arbitrary file reading. A [patch](https://github.com/gphper/ginadmin/commit/726109f01ad23523715f36f7d272958064666a30)
    is available on the `master` branch of the repository.
published: 2022-05-26T00:01:22Z
last_modified: 2022-06-09T22:55:52Z
cves:
  - CVE-2022-30428
ghsas:
  - GHSA-5824-6jfv-xr3r
links:
    context:
      - https://github.com/advisories/GHSA-5824-6jfv-xr3r

```
