### ISSUE TITLE
x/vulndb: potential Go vuln in gogs.io/gogs: GHSA-5gjh-5j4f-cpwv

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#654]
In GitHub Security Advisory [GHSA-5gjh-5j4f-cpwv](https://github.com/advisories/GHSA-5gjh-5j4f-cpwv), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [gogs.io/gogs](https://pkg.go.dev/gogs.io/gogs) | 0.12.6 | < 0.12.6 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: gogs.io/gogs
    versions:
      - fixed: 0.12.6
description: |
    ### Impact

    The malicious user is able to upload a crafted `config` file into repository's `.git` directory with to gain SSH access to the server. All installations with [repository upload enabled (default)](https://github.com/gogs/gogs/blob/f36eeedbf89328ee70cc3a2e239f6314f9021f58/conf/app.ini#L127-L129) are affected.

    ### Patches

    Repository file uploads are prohibited to its `.git` directory. Users should upgrade to 0.12.6 or the latest 0.13.0+dev.

    ### Workarounds

    [Disable repository files upload](https://github.com/gogs/gogs/blob/f36eeedbf89328ee70cc3a2e239f6314f9021f58/conf/app.ini#L128-L129).

    ### References

    https://huntr.dev/bounties/b4928cfe-4110-462f-a180-6d5673797902/

    ### For more information

    If you have any questions or comments about this advisory, please post on #6833.
published: 2022-03-28T16:46:41Z
last_modified: 2022-05-13T18:50:27Z
cves:
  - CVE-2022-0415
ghsas:
  - GHSA-5gjh-5j4f-cpwv
links:
    context:
      - https://github.com/advisories/GHSA-5gjh-5j4f-cpwv

```
