### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/containers/podman: GHSA-66vw-v2x9-hw75

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#658]
In GitHub Security Advisory [GHSA-66vw-v2x9-hw75](https://github.com/advisories/GHSA-66vw-v2x9-hw75), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/containers/podman](https://pkg.go.dev/github.com/containers/podman) | 4.0.0 | < 4.0.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/containers/podman
    versions:
      - fixed: 4.0.0
description: Podman is a tool for managing OCI containers and pods. A privilege escalation
    flaw was found in Podman. This flaw allows an attacker to publish a malicious
    image to a public registry. Once this image is downloaded by a potential victim,
    the vulnerability is triggered after a user runs the 'podman top' command. This
    action gives the attacker access to the host filesystem, leading to information
    disclosure or denial of service.
published: 2022-04-30T00:00:35Z
last_modified: 2022-05-26T19:48:01Z
cves:
  - CVE-2022-1227
ghsas:
  - GHSA-66vw-v2x9-hw75
links:
    context:
      - https://github.com/advisories/GHSA-66vw-v2x9-hw75

```
