### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/consul: GHSA-6hw5-6gcx-phmw

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#659]
In GitHub Security Advisory [GHSA-6hw5-6gcx-phmw](https://github.com/advisories/GHSA-6hw5-6gcx-phmw), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/consul](https://pkg.go.dev/github.com/hashicorp/consul) | 1.8.15 | < 1.8.15 || [github.com/hashicorp/consul](https://pkg.go.dev/github.com/hashicorp/consul) | 1.9.9 | >= 1.9.0, < 1.9.9 || [github.com/hashicorp/consul](https://pkg.go.dev/github.com/hashicorp/consul) | 1.10.2 | = 1.10.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/consul
    versions:
      - fixed: 1.8.15
  - package: github.com/hashicorp/consul
    versions:
      - introduced: 1.9.0
        fixed: 1.9.9
  - package: github.com/hashicorp/consul
    versions:
      - introduced: TODO (earliest fixed "1.10.2", vuln range "= 1.10.1")
description: HashiCorp Consul and Consul Enterprise 1.10.1 Txn.Apply endpoint allowed
    services to register proxies for other services, enabling access to service traffic.
    Fixed in 1.8.15, 1.9.9 and 1.10.2.
published: 2021-09-08T20:14:56Z
last_modified: 2021-09-16T18:57:25Z
cves:
  - CVE-2021-38698
ghsas:
  - GHSA-6hw5-6gcx-phmw
links:
    context:
      - https://github.com/advisories/GHSA-6hw5-6gcx-phmw

```
