### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-6jm6-cmcp-fqjq

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#660]
In GitHub Security Advisory [GHSA-6jm6-cmcp-fqjq](https://github.com/advisories/GHSA-6jm6-cmcp-fqjq), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.2.6 | >= 1.2.0, < 1.2.6 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.1.12 | >= 1.1.0, < 1.1.12 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.18 | >= 0.9.0, < 1.0.18 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.2.0
        fixed: 1.2.6
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.1.0
        fixed: 1.1.12
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 0.9.0
        fixed: 1.0.18
description: Nomad and Nomad Enterprise allows operators with job-submit capabilities
    to use the spread stanza in a way such that it can cause panic in Nomad servers.
    This vulnerability, CVE-2022-24684, was fixed in Nomad 1.0.18, 1.1.12, and 1.2.6.
published: 2022-02-16T00:01:42Z
last_modified: 2022-04-05T21:09:26Z
cves:
  - CVE-2022-24684
ghsas:
  - GHSA-6jm6-cmcp-fqjq
links:
    context:
      - https://github.com/advisories/GHSA-6jm6-cmcp-fqjq

```
