### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/gravitl/netmaker: GHSA-6rrw-4fm9-rghv

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#661]
In GitHub Security Advisory [GHSA-6rrw-4fm9-rghv](https://github.com/advisories/GHSA-6rrw-4fm9-rghv), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/gravitl/netmaker](https://pkg.go.dev/github.com/gravitl/netmaker) | 0.9.4 | >= 0.9.0, < 0.9.4 || [github.com/gravitl/netmaker](https://pkg.go.dev/github.com/gravitl/netmaker) | 0.8.5 | < 0.8.5 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/gravitl/netmaker
    versions:
      - introduced: 0.9.0
        fixed: 0.9.4
  - package: github.com/gravitl/netmaker
    versions:
      - fixed: 0.8.5
description: Netmaker prior to versions 0.8.5, 0.9.4, 0.10.0, and 0.10.1 uses a hard-coded
    cryptographic key.
published: 2022-02-19T00:01:36Z
last_modified: 2022-02-26T01:51:36Z
cves:
  - CVE-2022-0664
ghsas:
  - GHSA-6rrw-4fm9-rghv
links:
    context:
      - https://github.com/advisories/GHSA-6rrw-4fm9-rghv

```
