### ISSUE TITLE
x/vulndb: potential Go vuln in gogs.io/gogs: GHSA-7v5r-r995-q2x2

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#667]
In GitHub Security Advisory [GHSA-7v5r-r995-q2x2](https://github.com/advisories/GHSA-7v5r-r995-q2x2), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [gogs.io/gogs](https://pkg.go.dev/gogs.io/gogs) | 0.12.5 | < 0.12.5 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: gogs.io/gogs
    versions:
      - fixed: 0.12.5
description: Gogs is a self-hosted Git service. The malicious user is able to discover
    services in the internal network through repository migration functionality. All
    installations accepting public traffic are affected. Internal network CIDRs are
    prohibited to be used as repository migration targets. Users should upgrade to
    0.12.5 or the latest 0.13.0+dev. Gogs should be ran in its own private network
    until users can update.
published: 2022-03-12T00:00:34Z
last_modified: 2022-03-24T23:23:22Z
cves:
  - CVE-2022-0870
ghsas:
  - GHSA-7v5r-r995-q2x2
links:
    context:
      - https://github.com/advisories/GHSA-7v5r-r995-q2x2

```
