### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/kubernetes/kubernetes: GHSA-jp32-vmm6-3vf5

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#701]
In GitHub Security Advisory [GHSA-jp32-vmm6-3vf5](https://github.com/advisories/GHSA-jp32-vmm6-3vf5), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/kubernetes/kubernetes](https://pkg.go.dev/github.com/kubernetes/kubernetes) | 1.1.1 | < 1.1.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/kubernetes/kubernetes
    versions:
      - fixed: 1.1.1
description: Directory traversal vulnerability in Kubernetes, as used in Red Hat OpenShift
    Enterprise 3.0, allows attackers to write to arbitrary files via a crafted object
    type name, which is not properly handled before passing it to etcd.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:38:09Z
cves:
  - CVE-2015-5305
ghsas:
  - GHSA-jp32-vmm6-3vf5
links:
    context:
      - https://github.com/advisories/GHSA-jp32-vmm6-3vf5

```
