### ISSUE TITLE
x/vulndb: potential Go vuln in k8s.io/kubernetes/pkg/apiserver: GHSA-pmqp-h87c-mr78

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#703]
In GitHub Security Advisory [GHSA-pmqp-h87c-mr78](https://github.com/advisories/GHSA-pmqp-h87c-mr78), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [k8s.io/kubernetes/pkg/apiserver](https://pkg.go.dev/k8s.io/kubernetes/pkg/apiserver) | 1.16.2 | >= 1.16.0, < 1.16.2 || [k8s.io/kubernetes/pkg/apiserver](https://pkg.go.dev/k8s.io/kubernetes/pkg/apiserver) | 1.15.5 | >= 1.15.0, < 1.15.5 || [k8s.io/kubernetes/pkg/apiserver](https://pkg.go.dev/k8s.io/kubernetes/pkg/apiserver) | 1.14.8 | >= 1.14.0, < 1.14.8 || [k8s.io/kubernetes/pkg/apiserver](https://pkg.go.dev/k8s.io/kubernetes/pkg/apiserver) | 1.13.12 | >= 1.0.0, < 1.13.12 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: k8s.io/kubernetes/pkg/apiserver
    versions:
      - introduced: 1.16.0
        fixed: 1.16.2
  - package: k8s.io/kubernetes/pkg/apiserver
    versions:
      - introduced: 1.15.0
        fixed: 1.15.5
  - package: k8s.io/kubernetes/pkg/apiserver
    versions:
      - introduced: 1.14.0
        fixed: 1.14.8
  - package: k8s.io/kubernetes/pkg/apiserver
    versions:
      - introduced: 1.0.0
        fixed: 1.13.12
description: Improper input validation in the Kubernetes API server in versions v1.0-1.12
    and versions prior to v1.13.12, v1.14.8, v1.15.5, and v1.16.2 allows authorized
    users to send malicious YAML or JSON payloads, causing the API server to consume
    excessive CPU or memory, potentially crashing and becoming unavailable. Prior
    to v1.14.0, default RBAC policy authorized anonymous users to submit requests
    that could trigger this vulnerability. Clusters upgraded from a version prior
    to v1.14.0 keep the more permissive policy by default for backwards compatibility.
published: 2021-05-18T15:38:48Z
last_modified: 2021-05-18T15:38:48Z
cves:
  - CVE-2019-11253
ghsas:
  - GHSA-pmqp-h87c-mr78
links:
    context:
      - https://github.com/advisories/GHSA-pmqp-h87c-mr78

```
