### ISSUE TITLE
x/vulndb: potential Go vuln in go.elastic.co/apm: GHSA-qqc5-rgcc-cjqh

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#706]
In GitHub Security Advisory [GHSA-qqc5-rgcc-cjqh](https://github.com/advisories/GHSA-qqc5-rgcc-cjqh), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [go.elastic.co/apm](https://pkg.go.dev/go.elastic.co/apm) | 1.11.0 | < 1.11.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: go.elastic.co/apm
    versions:
      - fixed: 1.11.0
description: The Elastic APM agent for Go versions before 1.11.0 can leak sensitive
    HTTP header information when logging the details during an application panic.
    Normally, the APM agent will sanitize sensitive HTTP header details before sending
    the information to the APM server. During an application panic it is possible
    the headers will not be sanitized before being sent.
published: 2021-05-18T18:34:18Z
last_modified: 2021-05-18T18:34:18Z
cves:
  - CVE-2021-22133
ghsas:
  - GHSA-qqc5-rgcc-cjqh
links:
    context:
      - https://github.com/advisories/GHSA-qqc5-rgcc-cjqh

```
