### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/moby/moby: GHSA-v4h8-794j-g8mm

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#708]
In GitHub Security Advisory [GHSA-v4h8-794j-g8mm](https://github.com/advisories/GHSA-v4h8-794j-g8mm), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/moby/moby](https://pkg.go.dev/github.com/moby/moby) | 1.6.1 | < 1.6.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/moby/moby
    versions:
      - fixed: 1.6.1
description: Docker Engine before 1.6.1 allows local users to set arbitrary Linux
    Security Modules (LSM) and docker_t policies via an image that allows volumes
    to override files in /proc.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:13:10Z
cves:
  - CVE-2015-3631
ghsas:
  - GHSA-v4h8-794j-g8mm
links:
    context:
      - https://github.com/advisories/GHSA-v4h8-794j-g8mm

```
