### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hashicorp/nomad: GHSA-vf6q-9f2f-mwhv

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#709]
In GitHub Security Advisory [GHSA-vf6q-9f2f-mwhv](https://github.com/advisories/GHSA-vf6q-9f2f-mwhv), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 0.12.12 | < 0.12.12 || [github.com/hashicorp/nomad](https://pkg.go.dev/github.com/hashicorp/nomad) | 1.0.5 | >= 1.0.0, < 1.0.5 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/hashicorp/nomad
    versions:
      - fixed: 0.12.12
  - package: github.com/hashicorp/nomad
    versions:
      - introduced: 1.0.0
        fixed: 1.0.5
description: HashiCorp Nomad and Nomad Enterprise up to version 1.0.4 bridge networking
    mode allows ARP spoofing from other bridged tasks on the same node. Fixed in 0.12.12,
    1.0.5, and 1.1.0 RC1.
published: 2021-06-24T20:28:21Z
last_modified: 2021-06-24T20:28:21Z
cves:
  - CVE-2021-32575
ghsas:
  - GHSA-vf6q-9f2f-mwhv
links:
    context:
      - https://github.com/advisories/GHSA-vf6q-9f2f-mwhv

```
