### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/elastic/cloud-on-k8s: GHSA-vfp4-xx6m-7vf6

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#750]
In GitHub Security Advisory [GHSA-vfp4-xx6m-7vf6](https://github.com/advisories/GHSA-vfp4-xx6m-7vf6), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/elastic/cloud-on-k8s](https://pkg.go.dev/github.com/elastic/cloud-on-k8s) | 1.1.0 | < 1.1.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/elastic/cloud-on-k8s
    versions:
      - fixed: 1.1.0
description: Elastic Cloud on Kubernetes (ECK) versions prior to 1.1.0 generate passwords
    using a weak random number generator. If an attacker is able to determine when
    the current Elastic Stack cluster was deployed they may be able to more easily
    brute force the Elasticsearch credentials generated by ECK.
published: 2022-02-15T01:57:18Z
last_modified: 2022-04-12T22:53:59Z
cves:
  - CVE-2020-7010
ghsas:
  - GHSA-vfp4-xx6m-7vf6
links:
    context:
      - https://github.com/advisories/GHSA-vfp4-xx6m-7vf6

```
