### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/docker/docker: GHSA-wxj3-qwv4-cvfm

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#752]
In GitHub Security Advisory [GHSA-wxj3-qwv4-cvfm](https://github.com/advisories/GHSA-wxj3-qwv4-cvfm), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/docker/docker](https://pkg.go.dev/github.com/docker/docker) | 1.0.1 | < 1.0.1 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/docker/docker
    versions:
      - fixed: 1.0.1
description: Docker 1.0.0 uses world-readable and world-writable permissions on the
    management socket, which allows local users to gain privileges via unspecified
    vectors.
published: 2022-02-15T00:40:44Z
last_modified: 2022-02-15T00:40:44Z
cves:
  - CVE-2014-3499
ghsas:
  - GHSA-wxj3-qwv4-cvfm
links:
    context:
      - https://github.com/advisories/GHSA-wxj3-qwv4-cvfm

```
