### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/apache/servicecomb-service-center: GHSA-x6jv-5vfg-gm7x

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#754]
In GitHub Security Advisory [GHSA-x6jv-5vfg-gm7x](https://github.com/advisories/GHSA-x6jv-5vfg-gm7x), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/apache/servicecomb-service-center](https://pkg.go.dev/github.com/apache/servicecomb-service-center) | 2.0.0 | < 2.0.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/apache/servicecomb-service-center
    versions:
      - fixed: 2.0.0
description: Improper configuration will cause ServiceComb ServiceCenter Directory
    Traversal problem in ServcieCenter 1.x.x versions and fixed in 2.0.0.
published: 2021-09-01T18:35:52Z
last_modified: 2021-09-01T18:35:52Z
cves:
  - CVE-2021-21501
ghsas:
  - GHSA-x6jv-5vfg-gm7x
links:
    context:
      - https://github.com/advisories/GHSA-x6jv-5vfg-gm7x

```
