### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/minio/minio: CVE-2022-35919

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#756]
CVE-2022-35919 references [github.com/minio/minio](https://github.com/minio/minio), which may be a Go module.

Description:
MinIO is a High Performance Object Storage released under GNU Affero General Public License v3.0. In affected versions all 'admin' users authorized for `admin:ServerUpdate` can selectively trigger an error that in response, returns the content of the path requested. Any normal OS system would allow access to contents at any arbitrary paths that are readable by MinIO process. Users are advised to upgrade. Users unable to upgrade may disable ServerUpdate API by denying the `admin:ServerUpdate` action for your admin users via IAM policies.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-35919
- JSON: https://github.com/CVEProject/cvelist/tree/8dba00f035a63bacc37213407f78d2db7d47d4b0/2022/35xxx/CVE-2022-35919.json
- Commit: https://github.com/minio/minio/commit/bc72e4226e669d98c8e0f3eccc9297be9251c692
- PR: https://github.com/minio/minio/pull/15429
- Imported by: https://pkg.go.dev/github.com/minio/minio?tab=importedby
- https://github.com/minio/minio/security/advisories/GHSA-gr9v-6pcm-rqvg

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/minio/minio
    package: minio
description: |
    MinIO is a High Performance Object Storage released under GNU Affero General Public License v3.0. In affected versions all 'admin' users authorized for `admin:ServerUpdate` can selectively trigger an error that in response, returns the content of the path requested. Any normal OS system would allow access to contents at any arbitrary paths that are readable by MinIO process. Users are advised to upgrade. Users unable to upgrade may disable ServerUpdate API by denying the `admin:ServerUpdate` action for your admin users via IAM policies.
cves:
  - CVE-2022-35919
links:
    pr: https://github.com/minio/minio/pull/15429
    commit: https://github.com/minio/minio/commit/bc72e4226e669d98c8e0f3eccc9297be9251c692
    context:
      - https://github.com/minio/minio/security/advisories/GHSA-gr9v-6pcm-rqvg

```
