### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sanic-org/sanic: CVE-2022-35920

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#757]
CVE-2022-35920 references [github.com/sanic-org/sanic](https://github.com/sanic-org/sanic), which may be a Go module.

Description:
Sanic is an opensource python web server/framework. Affected versions of sanic allow access to lateral directories when using `app.static` if using encoded `%2F` URLs. Parent directory traversal is not impacted. Users are advised to upgrade. There is no known workaround for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-35920
- JSON: https://github.com/CVEProject/cvelist/tree/8dba00f035a63bacc37213407f78d2db7d47d4b0/2022/35xxx/CVE-2022-35920.json
- PR: https://github.com/sanic-org/sanic/pull/2495
- Imported by: https://pkg.go.dev/github.com/sanic-org/sanic?tab=importedby
- https://github.com/sanic-org/sanic/issues/2478
- https://github.com/sanic-org/sanic/security/advisories/GHSA-8cw9-5hmv-77w6

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/sanic-org/sanic
    package: sanic
description: |
    Sanic is an opensource python web server/framework. Affected versions of sanic allow access to lateral directories when using `app.static` if using encoded `%2F` URLs. Parent directory traversal is not impacted. Users are advised to upgrade. There is no known workaround for this issue.
cves:
  - CVE-2022-35920
links:
    pr: https://github.com/sanic-org/sanic/pull/2495
    context:
      - https://github.com/sanic-org/sanic/issues/2478
      - https://github.com/sanic-org/sanic/security/advisories/GHSA-8cw9-5hmv-77w6

```
