### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sigstore/cosign: CVE-2022-35929

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#758]
CVE-2022-35929 references [github.com/sigstore/cosign](https://github.com/sigstore/cosign), which may be a Go module.

Description:
cosign is a container signing and verification utility. In versions prior to 1.10.1 cosign can report a false positive if any attestation exists. `cosign verify-attestation` used with the `--type` flag will report a false positive verification when there is at least one attestation with a valid signature and there are NO attestations of the type being verified (--type defaults to "custom"). This can happen when signing with a standard keypair and with "keyless" signing with Fulcio. This vulnerability can be reproduced with the `distroless.dev/static@sha256:dd7614b5a12bc4d617b223c588b4e0c833402b8f4991fb5702ea83afad1986e2` image. This image has a `vuln` attestation but not an `spdx` attestation. However, if you run `cosign verify-attestation --type=spdx` on this image, it incorrectly succeeds. This issue has been addressed in version 1.10.1 of cosign. Users are advised to upgrade. There are no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-35929
- JSON: https://github.com/CVEProject/cvelist/tree/2e606574bae1db3c7b8442616a37f47f22336ec9/2022/35xxx/CVE-2022-35929.json
- Commit: https://github.com/sigstore/cosign/commit/c5fda01a8ff33ca981f45a9f13e7fb6bd2080b94
- Imported by: https://pkg.go.dev/github.com/sigstore/cosign?tab=importedby
- https://github.com/sigstore/cosign/security/advisories/GHSA-vjxv-45g9-9296

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/sigstore/cosign
    package: cosign
description: |
    cosign is a container signing and verification utility. In versions prior to 1.10.1 cosign can report a false positive if any attestation exists. `cosign verify-attestation` used with the `--type` flag will report a false positive verification when there is at least one attestation with a valid signature and there are NO attestations of the type being verified (--type defaults to "custom"). This can happen when signing with a standard keypair and with "keyless" signing with Fulcio. This vulnerability can be reproduced with the `distroless.dev/static@sha256:dd7614b5a12bc4d617b223c588b4e0c833402b8f4991fb5702ea83afad1986e2` image. This image has a `vuln` attestation but not an `spdx` attestation. However, if you run `cosign verify-attestation --type=spdx` on this image, it incorrectly succeeds. This issue has been addressed in version 1.10.1 of cosign. Users are advised to upgrade. There are no known workarounds for this issue.
cves:
  - CVE-2022-35929
links:
    commit: https://github.com/sigstore/cosign/commit/c5fda01a8ff33ca981f45a9f13e7fb6bd2080b94
    context:
      - https://github.com/sigstore/cosign/security/advisories/GHSA-vjxv-45g9-9296

```
