### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/sigstore/policy-controller: CVE-2022-35930

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#759]
CVE-2022-35930 references [github.com/sigstore/policy-controller](https://github.com/sigstore/policy-controller), which may be a Go module.

Description:
PolicyController is a utility used to enforce supply chain policy in Kubernetes clusters. In versions prior to 0.2.1 PolicyController will report a false positive, resulting in an admission when it should not be admitted when there is at least one attestation with a valid signature and there are NO attestations of the type being verified (--type defaults to "custom"). An example image that can be used to test this is `ghcr.io/distroless/static@sha256:dd7614b5a12bc4d617b223c588b4e0c833402b8f4991fb5702ea83afad1986e2`. Users should upgrade to version 0.2.1 to resolve this issue. There are no workarounds for users unable to upgrade.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-35930
- JSON: https://github.com/CVEProject/cvelist/tree/2dfa304bffdc94b40efb2f5f83a0125ca88e0258/2022/35xxx/CVE-2022-35930.json
- Commit: https://github.com/sigstore/policy-controller/commit/e852af36fb7d42678b21d7e97503c25bd1fd05c8
- Imported by: https://pkg.go.dev/github.com/sigstore/policy-controller?tab=importedby
- https://github.com/sigstore/policy-controller/releases/tag/v0.2.1
- https://github.com/sigstore/policy-controller/security/advisories/GHSA-739f-hw6h-7wq8

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/sigstore/policy-controller
    package: policy-controller
description: |
    PolicyController is a utility used to enforce supply chain policy in Kubernetes clusters. In versions prior to 0.2.1 PolicyController will report a false positive, resulting in an admission when it should not be admitted when there is at least one attestation with a valid signature and there are NO attestations of the type being verified (--type defaults to "custom"). An example image that can be used to test this is `ghcr.io/distroless/static@sha256:dd7614b5a12bc4d617b223c588b4e0c833402b8f4991fb5702ea83afad1986e2`. Users should upgrade to version 0.2.1 to resolve this issue. There are no workarounds for users unable to upgrade.
cves:
  - CVE-2022-35930
links:
    commit: https://github.com/sigstore/policy-controller/commit/e852af36fb7d42678b21d7e97503c25bd1fd05c8
    context:
      - https://github.com/sigstore/policy-controller/releases/tag/v0.2.1
      - https://github.com/sigstore/policy-controller/security/advisories/GHSA-739f-hw6h-7wq8

```
