### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/crypto-org-chain/cronos: GHSA-gwj5-wp6r-5q9f

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#829]
In GitHub Security Advisory [GHSA-gwj5-wp6r-5q9f](https://github.com/advisories/GHSA-gwj5-wp6r-5q9f), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/crypto-org-chain/cronos](https://pkg.go.dev/github.com/crypto-org-chain/cronos) | 0.8.0 | <= 0.7.0 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/crypto-org-chain/cronos
    versions:
      - introduced: TODO (earliest fixed "0.8.0", vuln range "<= 0.7.0")
description: |
    In Cronos nodes running versions before v0.7.0, the contract selfdestruct invocation permanently removes the corresponding bytecode from the internal database storage. However, due to a bug in Ethermint, all contracts that used the identical bytecode (i.e shared the same CodeHash) will also stop working once one contract invokes selfdestruct, even though the other contracts did not invoke the selfdestruct OPCODE. Thanks to the successfully coordinated security vulnerability disclosure, no smart contracts were impacted through the use of this vulnerability. Smart contract states and storage values are not affected by this vulnerability. This problem has been patched in Cronos v0.8.0. The patch has state machine-breaking changes and the required coordinated network upgrade was done on the block height 3982500 on the Cronos mainnet beta network. If a contract is subject to DoS due to this issue, the user can redeploy the same contract, i.e with identical bytecode, so that the original contract's code is recovered.
published: 2022-08-11T18:08:57Z
last_modified: 2022-08-11T18:08:58Z
ghsas:
  - GHSA-gwj5-wp6r-5q9f
links:
    context:
      - https://github.com/advisories/GHSA-gwj5-wp6r-5q9f

```
