### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/arvados/arvados: CVE-2022-36006

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#946]
CVE-2022-36006 references [github.com/arvados/arvados](https://github.com/arvados/arvados), which may be a Go module.

Description:
Arvados is an open source platform for managing, processing, and sharing genomic and other large scientific and biomedical data. A remote code execution (RCE) vulnerability in the Arvados Workbench allows authenticated attackers to execute arbitrary code via specially crafted JSON payloads.  This exists in all versions up to 2.4.1 and is fixed in 2.4.2.

This vulnerability is specific to the Ruby on Rails Workbench application (“Workbench 1”). We do not believe any other Arvados components, including the TypesScript browser-based Workbench application (“Workbench 2”) or API Server, are vulnerable to this attack. For versions of Arvados earlier than 2.4.2: remove the Ruby-based "Workbench 1" app ("apt-get remove arvados-workbench") from your installation as a workaround.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-36006
- JSON: https://github.com/CVEProject/cvelist/tree/815b92fa217617dbd5bc47c692988a823af3f56a/2022/36xxx/CVE-2022-36006.json
- Imported by: https://pkg.go.dev/github.com/arvados/arvados?tab=importedby
- https://arvados.org/release-notes/2.4.2/
- https://dev.arvados.org/issues/19316
- https://github.com/arvados/arvados/security/advisories/GHSA-8867-q4xf-cqgm

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/arvados/arvados
    package: arvados
description: |
    Arvados is an open source platform for managing, processing, and sharing genomic and other large scientific and biomedical data. A remote code execution (RCE) vulnerability in the Arvados Workbench allows authenticated attackers to execute arbitrary code via specially crafted JSON payloads.  This exists in all versions up to 2.4.1 and is fixed in 2.4.2.

    This vulnerability is specific to the Ruby on Rails Workbench application (“Workbench 1”). We do not believe any other Arvados components, including the TypesScript browser-based Workbench application (“Workbench 2”) or API Server, are vulnerable to this attack. For versions of Arvados earlier than 2.4.2: remove the Ruby-based "Workbench 1" app ("apt-get remove arvados-workbench") from your installation as a workaround.
cves:
  - CVE-2022-36006
links:
    context:
      - https://arvados.org/release-notes/2.4.2/
      - https://dev.arvados.org/issues/19316
      - https://github.com/arvados/arvados/security/advisories/GHSA-8867-q4xf-cqgm

```
