### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/hyperledger/fabric: CVE-2022-36023

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#949]
CVE-2022-36023 references [github.com/hyperledger/fabric](https://github.com/hyperledger/fabric), which may be a Go module.

Description:
Hyperledger Fabric is an enterprise-grade permissioned distributed ledger framework for developing solutions and applications. If a gateway client application sends a malformed request to a gateway peer it may crash the peer node. Version 2.4.6 checks for the malformed gateway request and returns an error to the gateway client. There are no known workarounds, users must upgrade to version 2.4.6.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-36023
- JSON: https://github.com/CVEProject/cvelist/tree/396e68feacb9dd9296ec904c9e22f5a415003db5/2022/36xxx/CVE-2022-36023.json
- Imported by: https://pkg.go.dev/github.com/hyperledger/fabric?tab=importedby
- https://github.com/hyperledger/fabric/releases/tag/v2.4.6
- https://github.com/hyperledger/fabric/security/advisories/GHSA-qj6r-fhrc-jj5r

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/hyperledger/fabric
    package: fabric
description: |
    Hyperledger Fabric is an enterprise-grade permissioned distributed ledger framework for developing solutions and applications. If a gateway client application sends a malformed request to a gateway peer it may crash the peer node. Version 2.4.6 checks for the malformed gateway request and returns an error to the gateway client. There are no known workarounds, users must upgrade to version 2.4.6.
cves:
  - CVE-2022-36023
links:
    context:
      - https://github.com/hyperledger/fabric/releases/tag/v2.4.6
      - https://github.com/hyperledger/fabric/security/advisories/GHSA-qj6r-fhrc-jj5r

```
