### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/keycloak/keycloak-gatekeeper: CVE-2020-14359, GHSA-jh6m-3pqw-242h

### ISSUE THREAD

**Issue by julieqiu** [golang/vulndb#951]
In GitHub Security Advisory [GHSA-jh6m-3pqw-242h](https://github.com/advisories/GHSA-jh6m-3pqw-242h), there is a vulnerability in the following Go packages or modules:

| Unit | Fixed | Vulnerable Ranges |
| - | - | - |
| [github.com/keycloak/keycloak-gatekeeper](https://pkg.go.dev/github.com/keycloak/keycloak-gatekeeper) |  | <= 1.2.8 |

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - package: github.com/keycloak/keycloak-gatekeeper
    versions:
      - {}
description: A vulnerability was found in all versions of the deprecated package Keycloak
    Gatekeeper, where on using lower case HTTP headers (via cURL) we can bypass our
    Gatekeeper. Lower case headers are also accepted by some webservers (e.g. Jetty).
    This means there is no protection when we put a Gatekeeper in front of a Jetty
    server and use lowercase headers.
published: 2022-02-09T00:56:04Z
last_modified: 2022-08-12T20:52:15Z
cves:
  - CVE-2020-14359
ghsas:
  - GHSA-jh6m-3pqw-242h
links:
    context:
      - https://github.com/advisories/GHSA-jh6m-3pqw-242h

```
