### ISSUE TITLE
x/vulndb: potential Go vuln in github.com/matrix-org/gomatrixserverlib: CVE-2022-36009

### ISSUE THREAD

**Issue by GoVulnBot** [golang/vulndb#952]
CVE-2022-36009 references [github.com/matrix-org/gomatrixserverlib](https://github.com/matrix-org/gomatrixserverlib), which may be a Go module.

Description:
gomatrixserverlib is a Go library for matrix protocol federation. Dendrite is a Matrix homeserver written in Go, an alternative to Synapse. The power level parsing within gomatrixserverlib was failing to parse the `"events_default"` key of the `m.room.power_levels` event, defaulting the event default power level to zero in all cases. Power levels are the matrix terminology for user access level. In rooms where the `"events_default"` power level had been changed, this could result in events either being incorrectly authorised or rejected by Dendrite servers. gomatrixserverlib contains a fix as of commit `723fd49` and Dendrite 0.9.3 has been updated accordingly. Matrix rooms where the `"events_default"` power level has not been changed from the default of zero are not vulnerable. Users are advised to upgrade. There are no known workarounds for this issue.

Links:
- NIST: https://nvd.nist.gov/vuln/detail/CVE-2022-36009
- JSON: https://github.com/CVEProject/cvelist/tree/761fd3cbf6f1c94558aa8656a65034316aa69a43/2022/36xxx/CVE-2022-36009.json
- Commit: https://github.com/matrix-org/gomatrixserverlib/commit/723fd495dde835d078b9f2074b6b62c06dea4575
- Imported by: https://pkg.go.dev/github.com/matrix-org/gomatrixserverlib?tab=importedby
- https://github.com/matrix-org/gomatrixserverlib/security/advisories/GHSA-grvv-h2f9-7v9c
- https://matrix.org/docs/guides/moderation/#power-levels

See [doc/triage.md](https://github.com/golang/vulndb/blob/master/doc/triage.md) for instructions on how to triage this report.

```
packages:
  - module: github.com/matrix-org/gomatrixserverlib
    package: gomatrixserverlib
description: |
    gomatrixserverlib is a Go library for matrix protocol federation. Dendrite is a Matrix homeserver written in Go, an alternative to Synapse. The power level parsing within gomatrixserverlib was failing to parse the `"events_default"` key of the `m.room.power_levels` event, defaulting the event default power level to zero in all cases. Power levels are the matrix terminology for user access level. In rooms where the `"events_default"` power level had been changed, this could result in events either being incorrectly authorised or rejected by Dendrite servers. gomatrixserverlib contains a fix as of commit `723fd49` and Dendrite 0.9.3 has been updated accordingly. Matrix rooms where the `"events_default"` power level has not been changed from the default of zero are not vulnerable. Users are advised to upgrade. There are no known workarounds for this issue.
cves:
  - CVE-2022-36009
links:
    commit: https://github.com/matrix-org/gomatrixserverlib/commit/723fd495dde835d078b9f2074b6b62c06dea4575
    context:
      - https://github.com/matrix-org/gomatrixserverlib/security/advisories/GHSA-grvv-h2f9-7v9c
      - https://matrix.org/docs/guides/moderation/#power-levels

```
